create table ACT_HI_VARINST (
    ID_ NVARCHAR(64) not null,
    REV_ INTEGER default 1,
    PROC_INST_ID_ NVARCHAR(64),
    EXECUTION_ID_ NVARCHAR(64),
    TASK_ID_ NVARCHAR(64),
    NAME_ NVARCHAR(255) not null,
    VAR_TYPE_ NVARCHAR(100),
    SCOPE_ID_ NVARCHAR(255),
    SUB_SCOPE_ID_ NVARCHAR(255),
    SCOPE_TYPE_ NVARCHAR(255),
    BYTEARRAY_ID_ NVARCHAR(64),
    DOUBLE_ FLOAT,
    LONG_ BIGINT,
    TEXT_ NVARCHAR(2000),
    TEXT2_ NVARCHAR(2000),
    CREATE_TIME_ TIMESTAMP,
    LAST_UPDATED_TIME_ TIMESTAMP,
    primary key ("ID_")
);

create index ACT_IDX_HI_PROCVAR_NAME_TYPE on ACT_HI_VARINST(NAME_, VAR_TYPE_);
create index ACT_IDX_HI_VAR_SCOPE_ID_TYPE on ACT_HI_VARINST(SCOPE_ID_, SCOPE_TYPE_);
create index ACT_IDX_HI_VAR_SUB_ID_TYPE on ACT_HI_VARINST(SUB_SCOPE_ID_, SCOPE_TYPE_);
