CREATE TABLE ACT_GE_PROPERTY (
    NAME_ STRING(64) NOT NULL,
    VALUE_ STRING(300),
    REV_ INT64
) PRIMARY KEY (NAME_);

CREATE TABLE ACT_GE_BYTEARRAY (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    NAME_ STRING(255),
    DEPLOYMENT_ID_ STRING(64),
    BYTES_ BYTES(MAX),
    GENERATED_ BOOL
) PRIMARY KEY (ID_);

INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_) VALUES ('common.schema.version', '8.1.0.1', 1);
INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_) VALUES ('next.dbid', '1', 1);

CREATE TABLE ACT_RU_ENTITYLINK (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    CREATE_TIME_ TIMESTAMP,
    LINK_TYPE_ STRING(255),
    SCOPE_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    SCOPE_DEFINITION_ID_ STRING(255),
    PARENT_ELEMENT_ID_ STRING(255),
    REF_SCOPE_ID_ STRING(255),
    REF_SCOPE_TYPE_ STRING(255),
    REF_SCOPE_DEFINITION_ID_ STRING(255),
    ROOT_SCOPE_ID_ STRING(255),
    ROOT_SCOPE_TYPE_ STRING(255),
    HIERARCHY_TYPE_ STRING(255)
) PRIMARY KEY (ID_);

CREATE INDEX ACT_IDX_ENT_LNK_SCOPE ON ACT_RU_ENTITYLINK(SCOPE_ID_, SCOPE_TYPE_, LINK_TYPE_);
CREATE INDEX ACT_IDX_ENT_LNK_REF_SCOPE ON ACT_RU_ENTITYLINK(REF_SCOPE_ID_, REF_SCOPE_TYPE_, LINK_TYPE_);
CREATE INDEX ACT_IDX_ENT_LNK_ROOT_SCOPE ON ACT_RU_ENTITYLINK(ROOT_SCOPE_ID_, ROOT_SCOPE_TYPE_, LINK_TYPE_);
CREATE INDEX ACT_IDX_ENT_LNK_SCOPE_DEF ON ACT_RU_ENTITYLINK(SCOPE_DEFINITION_ID_, SCOPE_TYPE_, LINK_TYPE_);

CREATE TABLE ACT_HI_ENTITYLINK (
    ID_ STRING(64) NOT NULL,
    LINK_TYPE_ STRING(255),
    CREATE_TIME_ TIMESTAMP,
    SCOPE_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    SCOPE_DEFINITION_ID_ STRING(255),
    PARENT_ELEMENT_ID_ STRING(255),
    REF_SCOPE_ID_ STRING(255),
    REF_SCOPE_TYPE_ STRING(255),
    REF_SCOPE_DEFINITION_ID_ STRING(255),
    ROOT_SCOPE_ID_ STRING(255),
    ROOT_SCOPE_TYPE_ STRING(255),
    HIERARCHY_TYPE_ STRING(255)
) PRIMARY KEY (ID_);

CREATE INDEX ACT_IDX_HI_ENT_LNK_SCOPE ON ACT_HI_ENTITYLINK(SCOPE_ID_, SCOPE_TYPE_, LINK_TYPE_);
CREATE INDEX ACT_IDX_HI_ENT_LNK_REF_SCOPE ON ACT_HI_ENTITYLINK(REF_SCOPE_ID_, REF_SCOPE_TYPE_, LINK_TYPE_);
CREATE INDEX ACT_IDX_HI_ENT_LNK_ROOT_SCOPE ON ACT_HI_ENTITYLINK(ROOT_SCOPE_ID_, ROOT_SCOPE_TYPE_, LINK_TYPE_);
CREATE INDEX ACT_IDX_HI_ENT_LNK_SCOPE_DEF ON ACT_HI_ENTITYLINK(SCOPE_DEFINITION_ID_, SCOPE_TYPE_, LINK_TYPE_);

CREATE TABLE ACT_RU_IDENTITYLINK (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    GROUP_ID_ STRING(255),
    TYPE_ STRING(255),
    USER_ID_ STRING(255),
    TASK_ID_ STRING(64),
    PROC_INST_ID_ STRING(64),
    PROC_DEF_ID_ STRING(64),
    SCOPE_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    SCOPE_DEFINITION_ID_ STRING(255)
) PRIMARY KEY (ID_);

CREATE INDEX ACT_IDX_IDENT_LNK_USER ON ACT_RU_IDENTITYLINK(USER_ID_);
CREATE INDEX ACT_IDX_IDENT_LNK_GROUP ON ACT_RU_IDENTITYLINK(GROUP_ID_);
CREATE INDEX ACT_IDX_IDENT_LNK_SCOPE ON ACT_RU_IDENTITYLINK(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_IDENT_LNK_SUB_SCOPE ON ACT_RU_IDENTITYLINK(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_IDENT_LNK_SCOPE_DEF ON ACT_RU_IDENTITYLINK(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);

CREATE TABLE ACT_HI_IDENTITYLINK (
    ID_ STRING(64) NOT NULL,
    GROUP_ID_ STRING(255),
    TYPE_ STRING(255),
    USER_ID_ STRING(255),
    TASK_ID_ STRING(64),
    CREATE_TIME_ TIMESTAMP,
    PROC_INST_ID_ STRING(64),
    SCOPE_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    SCOPE_DEFINITION_ID_ STRING(255)
) PRIMARY KEY (ID_);

CREATE INDEX ACT_IDX_HI_IDENT_LNK_USER ON ACT_HI_IDENTITYLINK(USER_ID_);
CREATE INDEX ACT_IDX_HI_IDENT_LNK_SCOPE ON ACT_HI_IDENTITYLINK(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_HI_IDENT_LNK_SUB_SCOPE ON ACT_HI_IDENTITYLINK(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_HI_IDENT_LNK_SCOPE_DEF ON ACT_HI_IDENTITYLINK(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);

CREATE TABLE ACT_RU_JOB (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    CATEGORY_ STRING(255),
    TYPE_ STRING(255) NOT NULL,
    LOCK_EXP_TIME_ TIMESTAMP,
    LOCK_OWNER_ STRING(255),
    EXCLUSIVE_ BOOL,
    EXECUTION_ID_ STRING(64),
    PROCESS_INSTANCE_ID_ STRING(64),
    PROC_DEF_ID_ STRING(64),
    ELEMENT_ID_ STRING(255),
    ELEMENT_NAME_ STRING(255),
    SCOPE_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    SCOPE_DEFINITION_ID_ STRING(255),
    CORRELATION_ID_ STRING(255),
    RETRIES_ INT64,
    EXCEPTION_STACK_ID_ STRING(64),
    EXCEPTION_MSG_ STRING(4000),
    DUEDATE_ TIMESTAMP,
    REPEAT_ STRING(255),
    HANDLER_TYPE_ STRING(255),
    HANDLER_CFG_ STRING(4000),
    CUSTOM_VALUES_ID_ STRING(64),
    CREATE_TIME_ TIMESTAMP,
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_RU_TIMER_JOB (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    CATEGORY_ STRING(255),
    TYPE_ STRING(255) NOT NULL,
    LOCK_EXP_TIME_ TIMESTAMP,
    LOCK_OWNER_ STRING(255),
    EXCLUSIVE_ BOOL,
    EXECUTION_ID_ STRING(64),
    PROCESS_INSTANCE_ID_ STRING(64),
    PROC_DEF_ID_ STRING(64),
    ELEMENT_ID_ STRING(255),
    ELEMENT_NAME_ STRING(255),
    SCOPE_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    SCOPE_DEFINITION_ID_ STRING(255),
    CORRELATION_ID_ STRING(255),
    RETRIES_ INT64,
    EXCEPTION_STACK_ID_ STRING(64),
    EXCEPTION_MSG_ STRING(4000),
    DUEDATE_ TIMESTAMP,
    REPEAT_ STRING(255),
    HANDLER_TYPE_ STRING(255),
    HANDLER_CFG_ STRING(4000),
    CUSTOM_VALUES_ID_ STRING(64),
    CREATE_TIME_ TIMESTAMP,
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_RU_SUSPENDED_JOB (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    CATEGORY_ STRING(255),
    TYPE_ STRING(255) NOT NULL,
    EXCLUSIVE_ BOOL,
    EXECUTION_ID_ STRING(64),
    PROCESS_INSTANCE_ID_ STRING(64),
    PROC_DEF_ID_ STRING(64),
    ELEMENT_ID_ STRING(255),
    ELEMENT_NAME_ STRING(255),
    SCOPE_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    SCOPE_DEFINITION_ID_ STRING(255),
    CORRELATION_ID_ STRING(255),
    RETRIES_ INT64,
    EXCEPTION_STACK_ID_ STRING(64),
    EXCEPTION_MSG_ STRING(4000),
    DUEDATE_ TIMESTAMP,
    REPEAT_ STRING(255),
    HANDLER_TYPE_ STRING(255),
    HANDLER_CFG_ STRING(4000),
    CUSTOM_VALUES_ID_ STRING(64),
    CREATE_TIME_ TIMESTAMP,
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_RU_DEADLETTER_JOB (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    CATEGORY_ STRING(255),
    TYPE_ STRING(255) NOT NULL,
    EXCLUSIVE_ BOOL,
    EXECUTION_ID_ STRING(64),
    PROCESS_INSTANCE_ID_ STRING(64),
    PROC_DEF_ID_ STRING(64),
    ELEMENT_ID_ STRING(255),
    ELEMENT_NAME_ STRING(255),
    SCOPE_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    SCOPE_DEFINITION_ID_ STRING(255),
    CORRELATION_ID_ STRING(255),
    EXCEPTION_STACK_ID_ STRING(64),
    EXCEPTION_MSG_ STRING(4000),
    DUEDATE_ TIMESTAMP,
    REPEAT_ STRING(255),
    HANDLER_TYPE_ STRING(255),
    HANDLER_CFG_ STRING(4000),
    CUSTOM_VALUES_ID_ STRING(64),
    CREATE_TIME_ TIMESTAMP,
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_RU_HISTORY_JOB (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    LOCK_EXP_TIME_ TIMESTAMP,
    LOCK_OWNER_ STRING(255),
    RETRIES_ INT64,
    EXCEPTION_STACK_ID_ STRING(64),
    EXCEPTION_MSG_ STRING(4000),
    HANDLER_TYPE_ STRING(255),
    HANDLER_CFG_ STRING(4000),
    CUSTOM_VALUES_ID_ STRING(64),
    ADV_HANDLER_CFG_ID_ STRING(64),
    CREATE_TIME_ TIMESTAMP,
    SCOPE_TYPE_ STRING(255),
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_RU_EXTERNAL_JOB (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    CATEGORY_ STRING(255),
    TYPE_ STRING(255) NOT NULL,
    LOCK_EXP_TIME_ TIMESTAMP,
    LOCK_OWNER_ STRING(255),
    EXCLUSIVE_ BOOL,
    EXECUTION_ID_ STRING(64),
    PROCESS_INSTANCE_ID_ STRING(64),
    PROC_DEF_ID_ STRING(64),
    ELEMENT_ID_ STRING(255),
    ELEMENT_NAME_ STRING(255),
    SCOPE_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    SCOPE_DEFINITION_ID_ STRING(255),
    CORRELATION_ID_ STRING(255),
    RETRIES_ INT64,
    EXCEPTION_STACK_ID_ STRING(64),
    EXCEPTION_MSG_ STRING(4000),
    DUEDATE_ TIMESTAMP,
    REPEAT_ STRING(255),
    HANDLER_TYPE_ STRING(255),
    HANDLER_CFG_ STRING(4000),
    CUSTOM_VALUES_ID_ STRING(64),
    CREATE_TIME_ TIMESTAMP,
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE INDEX ACT_IDX_JOB_EXCEPTION_STACK_ID ON ACT_RU_JOB(EXCEPTION_STACK_ID_);
CREATE INDEX ACT_IDX_JOB_CUSTOM_VALUES_ID ON ACT_RU_JOB(CUSTOM_VALUES_ID_);
CREATE INDEX ACT_IDX_JOB_CORRELATION_ID ON ACT_RU_JOB(CORRELATION_ID_);

CREATE INDEX ACT_IDX_TIMER_JOB_EXCEPTION_STACK_ID ON ACT_RU_TIMER_JOB(EXCEPTION_STACK_ID_);
CREATE INDEX ACT_IDX_TIMER_JOB_CUSTOM_VALUES_ID ON ACT_RU_TIMER_JOB(CUSTOM_VALUES_ID_);
CREATE INDEX ACT_IDX_TIMER_JOB_CORRELATION_ID ON ACT_RU_TIMER_JOB(CORRELATION_ID_);
CREATE INDEX ACT_IDX_TIMER_JOB_DUEDATE ON ACT_RU_TIMER_JOB(DUEDATE_);

CREATE INDEX ACT_IDX_SUSPENDED_JOB_EXCEPTION_STACK_ID ON ACT_RU_SUSPENDED_JOB(EXCEPTION_STACK_ID_);
CREATE INDEX ACT_IDX_SUSPENDED_JOB_CUSTOM_VALUES_ID ON ACT_RU_SUSPENDED_JOB(CUSTOM_VALUES_ID_);
CREATE INDEX ACT_IDX_SUSPENDED_JOB_CORRELATION_ID ON ACT_RU_SUSPENDED_JOB(CORRELATION_ID_);

CREATE INDEX ACT_IDX_DEADLETTER_JOB_EXCEPTION_STACK_ID ON ACT_RU_DEADLETTER_JOB(EXCEPTION_STACK_ID_);
CREATE INDEX ACT_IDX_DEADLETTER_JOB_CUSTOM_VALUES_ID ON ACT_RU_DEADLETTER_JOB(CUSTOM_VALUES_ID_);
CREATE INDEX ACT_IDX_DEADLETTER_JOB_CORRELATION_ID ON ACT_RU_DEADLETTER_JOB(CORRELATION_ID_);

CREATE INDEX ACT_IDX_EXTERNAL_JOB_EXCEPTION_STACK_ID ON ACT_RU_EXTERNAL_JOB(EXCEPTION_STACK_ID_);
CREATE INDEX ACT_IDX_EXTERNAL_JOB_CUSTOM_VALUES_ID ON ACT_RU_EXTERNAL_JOB(CUSTOM_VALUES_ID_);
CREATE INDEX ACT_IDX_EXTERNAL_JOB_CORRELATION_ID ON ACT_RU_EXTERNAL_JOB(CORRELATION_ID_);

ALTER TABLE ACT_RU_JOB
    ADD CONSTRAINT ACT_FK_JOB_EXCEPTION
    FOREIGN KEY (EXCEPTION_STACK_ID_)
    REFERENCES ACT_GE_BYTEARRAY (ID_);

ALTER TABLE ACT_RU_JOB
    ADD CONSTRAINT ACT_FK_JOB_CUSTOM_VALUES
    FOREIGN KEY (CUSTOM_VALUES_ID_)
    REFERENCES ACT_GE_BYTEARRAY (ID_);

ALTER TABLE ACT_RU_TIMER_JOB
    ADD CONSTRAINT ACT_FK_TIMER_JOB_EXCEPTION
    FOREIGN KEY (EXCEPTION_STACK_ID_)
    REFERENCES ACT_GE_BYTEARRAY (ID_);

ALTER TABLE ACT_RU_TIMER_JOB
    ADD CONSTRAINT ACT_FK_TIMER_JOB_CUSTOM_VALUES
    FOREIGN KEY (CUSTOM_VALUES_ID_)
    REFERENCES ACT_GE_BYTEARRAY (ID_);

ALTER TABLE ACT_RU_SUSPENDED_JOB
    ADD CONSTRAINT ACT_FK_SUSPENDED_JOB_EXCEPTION
    FOREIGN KEY (EXCEPTION_STACK_ID_)
    REFERENCES ACT_GE_BYTEARRAY (ID_);

ALTER TABLE ACT_RU_SUSPENDED_JOB
    ADD CONSTRAINT ACT_FK_SUSPENDED_JOB_CUSTOM_VALUES
    FOREIGN KEY (CUSTOM_VALUES_ID_)
    REFERENCES ACT_GE_BYTEARRAY (ID_);

ALTER TABLE ACT_RU_DEADLETTER_JOB
    ADD CONSTRAINT ACT_FK_DEADLETTER_JOB_EXCEPTION
    FOREIGN KEY (EXCEPTION_STACK_ID_)
    REFERENCES ACT_GE_BYTEARRAY (ID_);

ALTER TABLE ACT_RU_DEADLETTER_JOB
    ADD CONSTRAINT ACT_FK_DEADLETTER_JOB_CUSTOM_VALUES
    FOREIGN KEY (CUSTOM_VALUES_ID_)
    REFERENCES ACT_GE_BYTEARRAY (ID_);

ALTER TABLE ACT_RU_EXTERNAL_JOB
    ADD CONSTRAINT ACT_FK_EXTERNAL_JOB_EXCEPTION
    FOREIGN KEY (EXCEPTION_STACK_ID_)
    REFERENCES ACT_GE_BYTEARRAY (ID_);

ALTER TABLE ACT_RU_EXTERNAL_JOB
    ADD CONSTRAINT ACT_FK_EXTERNAL_JOB_CUSTOM_VALUES
    FOREIGN KEY (CUSTOM_VALUES_ID_)
    REFERENCES ACT_GE_BYTEARRAY (ID_);

CREATE INDEX ACT_IDX_JOB_SCOPE ON ACT_RU_JOB(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_JOB_SUB_SCOPE ON ACT_RU_JOB(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_JOB_SCOPE_DEF ON ACT_RU_JOB(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);

CREATE INDEX ACT_IDX_TJOB_SCOPE ON ACT_RU_TIMER_JOB(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_TJOB_SUB_SCOPE ON ACT_RU_TIMER_JOB(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_TJOB_SCOPE_DEF ON ACT_RU_TIMER_JOB(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);

CREATE INDEX ACT_IDX_SJOB_SCOPE ON ACT_RU_SUSPENDED_JOB(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_SJOB_SUB_SCOPE ON ACT_RU_SUSPENDED_JOB(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_SJOB_SCOPE_DEF ON ACT_RU_SUSPENDED_JOB(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);

CREATE INDEX ACT_IDX_DJOB_SCOPE ON ACT_RU_DEADLETTER_JOB(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_DJOB_SUB_SCOPE ON ACT_RU_DEADLETTER_JOB(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_DJOB_SCOPE_DEF ON ACT_RU_DEADLETTER_JOB(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);

CREATE INDEX ACT_IDX_EJOB_SCOPE ON ACT_RU_EXTERNAL_JOB(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_EJOB_SUB_SCOPE ON ACT_RU_EXTERNAL_JOB(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_EJOB_SCOPE_DEF ON ACT_RU_EXTERNAL_JOB(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);

CREATE TABLE FLW_RU_BATCH (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    TYPE_ STRING(64) NOT NULL,
    SEARCH_KEY_ STRING(255),
    SEARCH_KEY2_ STRING(255),
    CREATE_TIME_ TIMESTAMP NOT NULL,
    COMPLETE_TIME_ TIMESTAMP,
    STATUS_ STRING(255),
    BATCH_DOC_ID_ STRING(64),
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE FLW_RU_BATCH_PART (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    BATCH_ID_ STRING(64),
    TYPE_ STRING(64) NOT NULL,
    SCOPE_ID_ STRING(64),
    SUB_SCOPE_ID_ STRING(64),
    SCOPE_TYPE_ STRING(64),
    SEARCH_KEY_ STRING(255),
    SEARCH_KEY2_ STRING(255),
    CREATE_TIME_ TIMESTAMP NOT NULL,
    COMPLETE_TIME_ TIMESTAMP,
    STATUS_ STRING(255),
    RESULT_DOC_ID_ STRING(64),
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE INDEX FLW_IDX_BATCH_PART ON FLW_RU_BATCH_PART(BATCH_ID_);

ALTER TABLE FLW_RU_BATCH_PART
    ADD CONSTRAINT FLW_FK_BATCH_PART_PARENT
    FOREIGN KEY (BATCH_ID_)
    REFERENCES FLW_RU_BATCH (ID_);

CREATE TABLE ACT_RU_TASK (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    EXECUTION_ID_ STRING(64),
    PROC_INST_ID_ STRING(64),
    PROC_DEF_ID_ STRING(64),
    TASK_DEF_ID_ STRING(64),
    SCOPE_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    SCOPE_DEFINITION_ID_ STRING(255),
    PROPAGATED_STAGE_INST_ID_ STRING(255),
    STATE_ STRING(255),
    NAME_ STRING(255),
    PARENT_TASK_ID_ STRING(64),
    DESCRIPTION_ STRING(4000),
    TASK_DEF_KEY_ STRING(255),
    OWNER_ STRING(255),
    ASSIGNEE_ STRING(255),
    DELEGATION_ STRING(64),
    PRIORITY_ INT64,
    CREATE_TIME_ TIMESTAMP,
    IN_PROGRESS_TIME_ TIMESTAMP,
    IN_PROGRESS_STARTED_BY_ STRING(255),
    CLAIM_TIME_ TIMESTAMP,
    CLAIMED_BY_ STRING(255),
    SUSPENDED_TIME_ TIMESTAMP,
    SUSPENDED_BY_ STRING(255),
    IN_PROGRESS_DUE_DATE_ TIMESTAMP,
    DUE_DATE_ TIMESTAMP,
    CATEGORY_ STRING(255),
    SUSPENSION_STATE_ INT64,
    TENANT_ID_ STRING(255) DEFAULT (''),
    FORM_KEY_ STRING(255),
    IS_COUNT_ENABLED_ BOOL,
    VAR_COUNT_ INT64,
    ID_LINK_COUNT_ INT64,
    SUB_TASK_COUNT_ INT64
) PRIMARY KEY (ID_);

CREATE INDEX ACT_IDX_TASK_CREATE ON ACT_RU_TASK(CREATE_TIME_);
CREATE INDEX ACT_IDX_TASK_SCOPE ON ACT_RU_TASK(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_TASK_SUB_SCOPE ON ACT_RU_TASK(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_TASK_SCOPE_DEF ON ACT_RU_TASK(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);

CREATE TABLE ACT_HI_TASKINST (
    ID_ STRING(64) NOT NULL,
    REV_ INT64 DEFAULT (1),
    PROC_DEF_ID_ STRING(64),
    TASK_DEF_ID_ STRING(64),
    TASK_DEF_KEY_ STRING(255),
    PROC_INST_ID_ STRING(64),
    EXECUTION_ID_ STRING(64),
    SCOPE_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    SCOPE_DEFINITION_ID_ STRING(255),
    PROPAGATED_STAGE_INST_ID_ STRING(255),
    STATE_ STRING(255),
    NAME_ STRING(255),
    PARENT_TASK_ID_ STRING(64),
    DESCRIPTION_ STRING(4000),
    OWNER_ STRING(255),
    ASSIGNEE_ STRING(255),
    START_TIME_ TIMESTAMP NOT NULL,
    IN_PROGRESS_TIME_ TIMESTAMP,
    IN_PROGRESS_STARTED_BY_ STRING(255),
    CLAIM_TIME_ TIMESTAMP,
    CLAIMED_BY_ STRING(255),
    SUSPENDED_TIME_ TIMESTAMP,
    SUSPENDED_BY_ STRING(255),
    END_TIME_ TIMESTAMP,
    COMPLETED_BY_ STRING(255),
    DURATION_ INT64,
    DELETE_REASON_ STRING(4000),
    PRIORITY_ INT64,
    IN_PROGRESS_DUE_DATE_ TIMESTAMP,
    DUE_DATE_ TIMESTAMP,
    FORM_KEY_ STRING(255),
    CATEGORY_ STRING(255),
    TENANT_ID_ STRING(255) DEFAULT (''),
    LAST_UPDATED_TIME_ TIMESTAMP
) PRIMARY KEY (ID_);

CREATE TABLE ACT_HI_TSK_LOG (
    ID_ INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE),
    TYPE_ STRING(64),
    TASK_ID_ STRING(64) NOT NULL,
    TIME_STAMP_ TIMESTAMP NOT NULL,
    USER_ID_ STRING(255),
    DATA_ STRING(4000),
    EXECUTION_ID_ STRING(64),
    PROC_INST_ID_ STRING(64),
    PROC_DEF_ID_ STRING(64),
    SCOPE_ID_ STRING(255),
    SCOPE_DEFINITION_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE INDEX ACT_IDX_HI_TASK_SCOPE ON ACT_HI_TASKINST(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_HI_TASK_SUB_SCOPE ON ACT_HI_TASKINST(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_HI_TASK_SCOPE_DEF ON ACT_HI_TASKINST(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_ACT_HI_TSK_LOG_TASK ON ACT_HI_TSK_LOG(TASK_ID_);

CREATE TABLE ACT_RU_VARIABLE (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    TYPE_ STRING(255) NOT NULL,
    NAME_ STRING(255) NOT NULL,
    EXECUTION_ID_ STRING(64),
    PROC_INST_ID_ STRING(64),
    TASK_ID_ STRING(64),
    SCOPE_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    BYTEARRAY_ID_ STRING(64),
    DOUBLE_ FLOAT64,
    LONG_ INT64,
    TEXT_ STRING(4000),
    TEXT2_ STRING(4000),
    META_INFO_ STRING(4000)
) PRIMARY KEY (ID_);

CREATE INDEX ACT_IDX_RU_VAR_SCOPE_ID_TYPE ON ACT_RU_VARIABLE(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_RU_VAR_SUB_ID_TYPE ON ACT_RU_VARIABLE(SUB_SCOPE_ID_, SCOPE_TYPE_);

CREATE INDEX ACT_IDX_VAR_BYTEARRAY ON ACT_RU_VARIABLE(BYTEARRAY_ID_);
ALTER TABLE ACT_RU_VARIABLE 
    ADD CONSTRAINT ACT_FK_VAR_BYTEARRAY 
    FOREIGN KEY (BYTEARRAY_ID_) 
    REFERENCES ACT_GE_BYTEARRAY (ID_);

CREATE TABLE ACT_HI_VARINST (
    ID_ STRING(64) NOT NULL,
    REV_ INT64 DEFAULT (1),
    PROC_INST_ID_ STRING(64),
    EXECUTION_ID_ STRING(64),
    TASK_ID_ STRING(64),
    NAME_ STRING(255) NOT NULL,
    VAR_TYPE_ STRING(100),
    SCOPE_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    BYTEARRAY_ID_ STRING(64),
    DOUBLE_ FLOAT64,
    LONG_ INT64,
    TEXT_ STRING(4000),
    TEXT2_ STRING(4000),
    META_INFO_ STRING(4000),
    CREATE_TIME_ TIMESTAMP,
    LAST_UPDATED_TIME_ TIMESTAMP
) PRIMARY KEY (ID_);

CREATE INDEX ACT_IDX_HI_PROCVAR_NAME_TYPE ON ACT_HI_VARINST(NAME_, VAR_TYPE_);
CREATE INDEX ACT_IDX_HI_VAR_SCOPE_ID_TYPE ON ACT_HI_VARINST(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_HI_VAR_SUB_ID_TYPE ON ACT_HI_VARINST(SUB_SCOPE_ID_, SCOPE_TYPE_);

CREATE TABLE ACT_RU_EVENT_SUBSCR (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    EVENT_TYPE_ STRING(255) NOT NULL,
    EVENT_NAME_ STRING(255),
    EXECUTION_ID_ STRING(64),
    PROC_INST_ID_ STRING(64),
    ACTIVITY_ID_ STRING(255),
    CONFIGURATION_ STRING(255),
    CREATED_ TIMESTAMP NOT NULL,
    PROC_DEF_ID_ STRING(64),
    SUB_SCOPE_ID_ STRING(64),
    SCOPE_ID_ STRING(64),
    SCOPE_DEFINITION_ID_ STRING(64),
    SCOPE_DEFINITION_KEY_ STRING(255),
    SCOPE_TYPE_ STRING(64),
    LOCK_TIME_ TIMESTAMP,
    LOCK_OWNER_ STRING(255),
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE INDEX ACT_IDX_EVENT_SUBSCR_CONFIG_ ON ACT_RU_EVENT_SUBSCR(CONFIGURATION_);
CREATE INDEX ACT_IDX_EVENT_SUBSCR ON ACT_RU_EVENT_SUBSCR(EXECUTION_ID_);
CREATE INDEX ACT_IDX_EVENT_SUBSCR_PROC_ID ON ACT_RU_EVENT_SUBSCR(PROC_INST_ID_);
CREATE INDEX ACT_IDX_EVENT_SUBSCR_SCOPEREF_ ON ACT_RU_EVENT_SUBSCR(SCOPE_ID_, SCOPE_TYPE_);

CREATE TABLE ACT_RE_DEPLOYMENT (
    ID_ STRING(64) NOT NULL,
    NAME_ STRING(255),
    CATEGORY_ STRING(255),
    KEY_ STRING(255),
    TENANT_ID_ STRING(255) DEFAULT (''),
    DEPLOY_TIME_ TIMESTAMP,
    DERIVED_FROM_ STRING(64),
    DERIVED_FROM_ROOT_ STRING(64),
    PARENT_DEPLOYMENT_ID_ STRING(255),
    ENGINE_VERSION_ STRING(255)
) PRIMARY KEY (ID_);

CREATE TABLE ACT_RE_MODEL (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    NAME_ STRING(255),
    KEY_ STRING(255),
    CATEGORY_ STRING(255),
    CREATE_TIME_ TIMESTAMP,
    LAST_UPDATE_TIME_ TIMESTAMP,
    VERSION_ INT64,
    META_INFO_ STRING(4000),
    DEPLOYMENT_ID_ STRING(64),
    EDITOR_SOURCE_VALUE_ID_ STRING(64),
    EDITOR_SOURCE_EXTRA_VALUE_ID_ STRING(64),
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_RU_EXECUTION (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    PROC_INST_ID_ STRING(64),
    BUSINESS_KEY_ STRING(255),
    PARENT_ID_ STRING(64),
    PROC_DEF_ID_ STRING(64),
    SUPER_EXEC_ STRING(64),
    ROOT_PROC_INST_ID_ STRING(64),
    ACT_ID_ STRING(255),
    IS_ACTIVE_ BOOL,
    IS_CONCURRENT_ BOOL,
    IS_SCOPE_ BOOL,
    IS_EVENT_SCOPE_ BOOL,
    IS_MI_ROOT_ BOOL,
    SUSPENSION_STATE_ INT64,
    CACHED_ENT_STATE_ INT64,
    TENANT_ID_ STRING(255) DEFAULT (''),
    NAME_ STRING(255),
    START_ACT_ID_ STRING(255),
    START_TIME_ TIMESTAMP,
    START_USER_ID_ STRING(255),
    LOCK_TIME_ TIMESTAMP,
    LOCK_OWNER_ STRING(255),
    IS_COUNT_ENABLED_ BOOL,
    EVT_SUBSCR_COUNT_ INT64,
    TASK_COUNT_ INT64,
    JOB_COUNT_ INT64,
    TIMER_JOB_COUNT_ INT64,
    SUSP_JOB_COUNT_ INT64,
    DEADLETTER_JOB_COUNT_ INT64,
    EXTERNAL_WORKER_JOB_COUNT_ INT64,
    VAR_COUNT_ INT64,
    ID_LINK_COUNT_ INT64,
    CALLBACK_ID_ STRING(255),
    CALLBACK_TYPE_ STRING(255),
    REFERENCE_ID_ STRING(255),
    REFERENCE_TYPE_ STRING(255),
    PROPAGATED_STAGE_INST_ID_ STRING(255),
    BUSINESS_STATUS_ STRING(255),
    DUE_DATE_ TIMESTAMP,
    CLAIM_TIME_ TIMESTAMP,
    CLAIMED_BY_ STRING(255)
) PRIMARY KEY (ID_);

CREATE TABLE ACT_RE_PROCDEF (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    CATEGORY_ STRING(255),
    NAME_ STRING(255),
    KEY_ STRING(255) NOT NULL,
    VERSION_ INT64 NOT NULL,
    DEPLOYMENT_ID_ STRING(64),
    RESOURCE_NAME_ STRING(4000),
    DGRM_RESOURCE_NAME_ STRING(4000),
    DESCRIPTION_ STRING(4000),
    HAS_START_FORM_KEY_ BOOL,
    HAS_GRAPHICAL_NOTATION_ BOOL,
    SUSPENSION_STATE_ INT64,
    TENANT_ID_ STRING(255) DEFAULT (''),
    DERIVED_FROM_ STRING(64),
    DERIVED_FROM_ROOT_ STRING(64),
    DERIVED_VERSION_ INT64 NOT NULL DEFAULT (0),
    ENGINE_VERSION_ STRING(255)
) PRIMARY KEY (ID_);

CREATE TABLE ACT_EVT_LOG (
    LOG_NR_ INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE),
    TYPE_ STRING(64),
    PROC_DEF_ID_ STRING(64),
    PROC_INST_ID_ STRING(64),
    EXECUTION_ID_ STRING(64),
    TASK_ID_ STRING(64),
    TIME_STAMP_ TIMESTAMP NOT NULL,
    USER_ID_ STRING(255),
    DATA_ BYTES(MAX),
    LOCK_OWNER_ STRING(255),
    LOCK_TIME_ TIMESTAMP,
    IS_PROCESSED_ INT64 DEFAULT (0)
) PRIMARY KEY (LOG_NR_);

CREATE TABLE ACT_PROCDEF_INFO (
    ID_ STRING(64) NOT NULL,
    PROC_DEF_ID_ STRING(64) NOT NULL,
    REV_ INT64,
    INFO_JSON_ID_ STRING(64)
) PRIMARY KEY (ID_);

CREATE TABLE ACT_RU_ACTINST (
    ID_ STRING(64) NOT NULL,
    REV_ INT64 DEFAULT (1),
    PROC_DEF_ID_ STRING(64) NOT NULL,
    PROC_INST_ID_ STRING(64) NOT NULL,
    EXECUTION_ID_ STRING(64) NOT NULL,
    ACT_ID_ STRING(255) NOT NULL,
    TASK_ID_ STRING(64),
    CALL_PROC_INST_ID_ STRING(64),
    ACT_NAME_ STRING(255),
    ACT_TYPE_ STRING(255) NOT NULL,
    ASSIGNEE_ STRING(255),
    COMPLETED_BY_ STRING(255),
    START_TIME_ TIMESTAMP NOT NULL,
    END_TIME_ TIMESTAMP,
    DURATION_ INT64,
    TRANSACTION_ORDER_ INT64,
    DELETE_REASON_ STRING(4000),
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE INDEX ACT_IDX_EXEC_BUSKEY ON ACT_RU_EXECUTION(BUSINESS_KEY_);
CREATE INDEX ACT_IDX_EXE_ROOT ON ACT_RU_EXECUTION(ROOT_PROC_INST_ID_);
CREATE INDEX ACT_IDX_EXEC_REF_ID_ ON ACT_RU_EXECUTION(REFERENCE_ID_);
CREATE INDEX ACT_IDX_VARIABLE_TASK_ID ON ACT_RU_VARIABLE(TASK_ID_);

CREATE INDEX ACT_IDX_BYTEAR_DEPL ON ACT_GE_BYTEARRAY(DEPLOYMENT_ID_);

CREATE INDEX ACT_IDX_RU_ACTI_START ON ACT_RU_ACTINST(START_TIME_);
CREATE INDEX ACT_IDX_RU_ACTI_END ON ACT_RU_ACTINST(END_TIME_);
CREATE INDEX ACT_IDX_RU_ACTI_PROC ON ACT_RU_ACTINST(PROC_INST_ID_);
CREATE INDEX ACT_IDX_RU_ACTI_PROC_ACT ON ACT_RU_ACTINST(PROC_INST_ID_, ACT_ID_);
CREATE INDEX ACT_IDX_RU_ACTI_EXEC ON ACT_RU_ACTINST(EXECUTION_ID_);
CREATE INDEX ACT_IDX_RU_ACTI_EXEC_ACT ON ACT_RU_ACTINST(EXECUTION_ID_, ACT_ID_);
CREATE INDEX ACT_IDX_RU_ACTI_TASK ON ACT_RU_ACTINST(TASK_ID_);

ALTER TABLE ACT_GE_BYTEARRAY
    ADD CONSTRAINT ACT_FK_BYTEARR_DEPL
    FOREIGN KEY (DEPLOYMENT_ID_) 
    REFERENCES ACT_RE_DEPLOYMENT (ID_);

CREATE UNIQUE NULL_FILTERED INDEX ACT_UNIQ_PROCDEF
    ON ACT_RE_PROCDEF (KEY_, VERSION_, DERIVED_VERSION_, TENANT_ID_);
    
CREATE INDEX ACT_IDX_EXE_PROCINST ON ACT_RU_EXECUTION(PROC_INST_ID_);
ALTER TABLE ACT_RU_EXECUTION
    ADD CONSTRAINT ACT_FK_EXE_PROCINST 
    FOREIGN KEY (PROC_INST_ID_) 
    REFERENCES ACT_RU_EXECUTION (ID_);

CREATE INDEX ACT_IDX_EXE_PARENT ON ACT_RU_EXECUTION(PARENT_ID_);
ALTER TABLE ACT_RU_EXECUTION
    ADD CONSTRAINT ACT_FK_EXE_PARENT
    FOREIGN KEY (PARENT_ID_) 
    REFERENCES ACT_RU_EXECUTION (ID_);
    
CREATE INDEX ACT_IDX_EXE_SUPER ON ACT_RU_EXECUTION(SUPER_EXEC_);
ALTER TABLE ACT_RU_EXECUTION
    ADD CONSTRAINT ACT_FK_EXE_SUPER
    FOREIGN KEY (SUPER_EXEC_) 
    REFERENCES ACT_RU_EXECUTION (ID_);

CREATE INDEX ACT_IDX_EXE_PROCDEF ON ACT_RU_EXECUTION(PROC_DEF_ID_); 
ALTER TABLE ACT_RU_EXECUTION
    ADD CONSTRAINT ACT_FK_EXE_PROCDEF 
    FOREIGN KEY (PROC_DEF_ID_) 
    REFERENCES ACT_RE_PROCDEF (ID_);    

CREATE INDEX ACT_IDX_TSKASS_TASK ON ACT_RU_IDENTITYLINK(TASK_ID_);
ALTER TABLE ACT_RU_IDENTITYLINK
    ADD CONSTRAINT ACT_FK_TSKASS_TASK
    FOREIGN KEY (TASK_ID_) 
    REFERENCES ACT_RU_TASK (ID_);
    
CREATE INDEX ACT_IDX_ATHRZ_PROCEDEF ON ACT_RU_IDENTITYLINK(PROC_DEF_ID_);
ALTER TABLE ACT_RU_IDENTITYLINK
    ADD CONSTRAINT ACT_FK_ATHRZ_PROCEDEF
    FOREIGN KEY (PROC_DEF_ID_) 
    REFERENCES ACT_RE_PROCDEF (ID_);
    
CREATE INDEX ACT_IDX_IDL_PROCINST ON ACT_RU_IDENTITYLINK(PROC_INST_ID_);
ALTER TABLE ACT_RU_IDENTITYLINK
    ADD CONSTRAINT ACT_FK_IDL_PROCINST
    FOREIGN KEY (PROC_INST_ID_) 
    REFERENCES ACT_RU_EXECUTION (ID_);    
    
CREATE INDEX ACT_IDX_TASK_EXEC ON ACT_RU_TASK(EXECUTION_ID_);
ALTER TABLE ACT_RU_TASK
    ADD CONSTRAINT ACT_FK_TASK_EXE
    FOREIGN KEY (EXECUTION_ID_)
    REFERENCES ACT_RU_EXECUTION (ID_);
    
CREATE INDEX ACT_IDX_TASK_PROCINST ON ACT_RU_TASK(PROC_INST_ID_);
ALTER TABLE ACT_RU_TASK
    ADD CONSTRAINT ACT_FK_TASK_PROCINST
    FOREIGN KEY (PROC_INST_ID_) 
    REFERENCES ACT_RU_EXECUTION (ID_);
    
CREATE INDEX ACT_IDX_TASK_PROCDEF ON ACT_RU_TASK(PROC_DEF_ID_);
ALTER TABLE ACT_RU_TASK
  ADD CONSTRAINT ACT_FK_TASK_PROCDEF
  FOREIGN KEY (PROC_DEF_ID_)
  REFERENCES ACT_RE_PROCDEF (ID_);
  
CREATE INDEX ACT_IDX_VAR_EXE ON ACT_RU_VARIABLE(EXECUTION_ID_);
ALTER TABLE ACT_RU_VARIABLE 
    ADD CONSTRAINT ACT_FK_VAR_EXE
    FOREIGN KEY (EXECUTION_ID_) 
    REFERENCES ACT_RU_EXECUTION (ID_);

CREATE INDEX ACT_IDX_VAR_PROCINST ON ACT_RU_VARIABLE(PROC_INST_ID_);
ALTER TABLE ACT_RU_VARIABLE
    ADD CONSTRAINT ACT_FK_VAR_PROCINST
    FOREIGN KEY (PROC_INST_ID_) 
    REFERENCES ACT_RU_EXECUTION (ID_);

CREATE INDEX ACT_IDX_JOB_EXECUTION_ID ON ACT_RU_JOB(EXECUTION_ID_);
ALTER TABLE ACT_RU_JOB 
    ADD CONSTRAINT ACT_FK_JOB_EXECUTION 
    FOREIGN KEY (EXECUTION_ID_) 
    REFERENCES ACT_RU_EXECUTION (ID_);

CREATE INDEX ACT_IDX_JOB_PROCESS_INSTANCE_ID ON ACT_RU_JOB(PROCESS_INSTANCE_ID_);
ALTER TABLE ACT_RU_JOB 
    ADD CONSTRAINT ACT_FK_JOB_PROCESS_INSTANCE 
    FOREIGN KEY (PROCESS_INSTANCE_ID_) 
    REFERENCES ACT_RU_EXECUTION (ID_);

CREATE INDEX ACT_IDX_JOB_PROC_DEF_ID ON ACT_RU_JOB(PROC_DEF_ID_);
ALTER TABLE ACT_RU_JOB 
    ADD CONSTRAINT ACT_FK_JOB_PROC_DEF
    FOREIGN KEY (PROC_DEF_ID_) 
    REFERENCES ACT_RE_PROCDEF (ID_);

CREATE INDEX ACT_IDX_TIMER_JOB_EXECUTION_ID ON ACT_RU_TIMER_JOB(EXECUTION_ID_);
ALTER TABLE ACT_RU_TIMER_JOB 
    ADD CONSTRAINT ACT_FK_TIMER_JOB_EXECUTION 
    FOREIGN KEY (EXECUTION_ID_) 
    REFERENCES ACT_RU_EXECUTION (ID_);

CREATE INDEX ACT_IDX_TIMER_JOB_PROCESS_INSTANCE_ID ON ACT_RU_TIMER_JOB(PROCESS_INSTANCE_ID_);
ALTER TABLE ACT_RU_TIMER_JOB 
    ADD CONSTRAINT ACT_FK_TIMER_JOB_PROCESS_INSTANCE 
    FOREIGN KEY (PROCESS_INSTANCE_ID_) 
    REFERENCES ACT_RU_EXECUTION (ID_);

CREATE INDEX ACT_IDX_TIMER_JOB_PROC_DEF_ID ON ACT_RU_TIMER_JOB(PROC_DEF_ID_);
ALTER TABLE ACT_RU_TIMER_JOB 
    ADD CONSTRAINT ACT_FK_TIMER_JOB_PROC_DEF
    FOREIGN KEY (PROC_DEF_ID_) 
    REFERENCES ACT_RE_PROCDEF (ID_);

CREATE INDEX ACT_IDX_SUSPENDED_JOB_EXECUTION_ID ON ACT_RU_SUSPENDED_JOB(EXECUTION_ID_);    
ALTER TABLE ACT_RU_SUSPENDED_JOB 
    ADD CONSTRAINT ACT_FK_SUSPENDED_JOB_EXECUTION 
    FOREIGN KEY (EXECUTION_ID_) 
    REFERENCES ACT_RU_EXECUTION (ID_);
    
CREATE INDEX ACT_IDX_SUSPENDED_JOB_PROCESS_INSTANCE_ID ON ACT_RU_SUSPENDED_JOB(PROCESS_INSTANCE_ID_);    
ALTER TABLE ACT_RU_SUSPENDED_JOB 
    ADD CONSTRAINT ACT_FK_SUSPENDED_JOB_PROCESS_INSTANCE 
    FOREIGN KEY (PROCESS_INSTANCE_ID_) 
    REFERENCES ACT_RU_EXECUTION (ID_);

CREATE INDEX ACT_IDX_SUSPENDED_JOB_PROC_DEF_ID ON ACT_RU_SUSPENDED_JOB(PROC_DEF_ID_);    
ALTER TABLE ACT_RU_SUSPENDED_JOB 
    ADD CONSTRAINT ACT_FK_SUSPENDED_JOB_PROC_DEF
    FOREIGN KEY (PROC_DEF_ID_) 
    REFERENCES ACT_RE_PROCDEF (ID_);

CREATE INDEX ACT_IDX_DEADLETTER_JOB_EXECUTION_ID ON ACT_RU_DEADLETTER_JOB(EXECUTION_ID_);      
ALTER TABLE ACT_RU_DEADLETTER_JOB 
    ADD CONSTRAINT ACT_FK_DEADLETTER_JOB_EXECUTION 
    FOREIGN KEY (EXECUTION_ID_) 
    REFERENCES ACT_RU_EXECUTION (ID_);
 
CREATE INDEX ACT_IDX_DEADLETTER_JOB_PROCESS_INSTANCE_ID ON ACT_RU_DEADLETTER_JOB(PROCESS_INSTANCE_ID_);        
ALTER TABLE ACT_RU_DEADLETTER_JOB 
    ADD CONSTRAINT ACT_FK_DEADLETTER_JOB_PROCESS_INSTANCE 
    FOREIGN KEY (PROCESS_INSTANCE_ID_) 
    REFERENCES ACT_RU_EXECUTION (ID_);
    
CREATE INDEX ACT_IDX_DEADLETTER_JOB_PROC_DEF_ID ON ACT_RU_DEADLETTER_JOB(PROC_DEF_ID_);    
ALTER TABLE ACT_RU_DEADLETTER_JOB 
    ADD CONSTRAINT ACT_FK_DEADLETTER_JOB_PROC_DEF
    FOREIGN KEY (PROC_DEF_ID_) 
    REFERENCES ACT_RE_PROCDEF (ID_);
    
ALTER TABLE ACT_RU_EVENT_SUBSCR
    ADD CONSTRAINT ACT_FK_EVENT_EXEC
    FOREIGN KEY (EXECUTION_ID_)
    REFERENCES ACT_RU_EXECUTION (ID_);

CREATE INDEX ACT_IDX_MODEL_SOURCE ON ACT_RE_MODEL(EDITOR_SOURCE_VALUE_ID_);
ALTER TABLE ACT_RE_MODEL 
    ADD CONSTRAINT ACT_FK_MODEL_SOURCE 
    FOREIGN KEY (EDITOR_SOURCE_VALUE_ID_) 
    REFERENCES ACT_GE_BYTEARRAY (ID_);

CREATE INDEX ACT_IDX_MODEL_SOURCE_EXTRA ON ACT_RE_MODEL(EDITOR_SOURCE_EXTRA_VALUE_ID_);
ALTER TABLE ACT_RE_MODEL 
    ADD CONSTRAINT ACT_FK_MODEL_SOURCE_EXTRA 
    FOREIGN KEY (EDITOR_SOURCE_EXTRA_VALUE_ID_) 
    REFERENCES ACT_GE_BYTEARRAY (ID_);
    
CREATE INDEX ACT_IDX_MODEL_DEPLOYMENT ON ACT_RE_MODEL(DEPLOYMENT_ID_);    
ALTER TABLE ACT_RE_MODEL 
    ADD CONSTRAINT ACT_FK_MODEL_DEPLOYMENT 
    FOREIGN KEY (DEPLOYMENT_ID_) 
    REFERENCES ACT_RE_DEPLOYMENT (ID_);        

CREATE INDEX ACT_IDX_PROCDEF_INFO_JSON ON ACT_PROCDEF_INFO(INFO_JSON_ID_);
ALTER TABLE ACT_PROCDEF_INFO 
    ADD CONSTRAINT ACT_FK_INFO_JSON_BA 
    FOREIGN KEY (INFO_JSON_ID_) 
    REFERENCES ACT_GE_BYTEARRAY (ID_);

CREATE INDEX ACT_IDX_PROCDEF_INFO_PROC ON ACT_PROCDEF_INFO(PROC_DEF_ID_);
ALTER TABLE ACT_PROCDEF_INFO 
    ADD CONSTRAINT ACT_FK_INFO_PROCDEF 
    FOREIGN KEY (PROC_DEF_ID_) 
    REFERENCES ACT_RE_PROCDEF (ID_);
    
CREATE UNIQUE NULL_FILTERED INDEX ACT_UNIQ_INFO_PROCDEF
    ON ACT_PROCDEF_INFO (PROC_DEF_ID_);

INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_)
VALUES ('schema.version', '8.1.0.1', 1);

INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_)
VALUES ('schema.history', 'create(8.1.0.1)', 1);

CREATE TABLE ACT_HI_PROCINST (
    ID_ STRING(64) NOT NULL,
    REV_ INT64 DEFAULT (1),
    PROC_INST_ID_ STRING(64) NOT NULL,
    BUSINESS_KEY_ STRING(255),
    PROC_DEF_ID_ STRING(64) NOT NULL,
    START_TIME_ TIMESTAMP NOT NULL,
    END_TIME_ TIMESTAMP,
    DURATION_ INT64,
    START_USER_ID_ STRING(255),
    START_ACT_ID_ STRING(255),
    END_ACT_ID_ STRING(255),
    SUPER_PROCESS_INSTANCE_ID_ STRING(64),
    DELETE_REASON_ STRING(4000),
    TENANT_ID_ STRING(255) DEFAULT (''),
    NAME_ STRING(255),
    CALLBACK_ID_ STRING(255),
    CALLBACK_TYPE_ STRING(255),
    REFERENCE_ID_ STRING(255),
    REFERENCE_TYPE_ STRING(255),
    PROPAGATED_STAGE_INST_ID_ STRING(255),
    BUSINESS_STATUS_ STRING(255),
    DUE_DATE_ TIMESTAMP,
    CLAIM_TIME_ TIMESTAMP,
    CLAIMED_BY_ STRING(255),
    END_USER_ID_ STRING(255),
    STATE_ STRING(255)
) PRIMARY KEY (ID_);

CREATE UNIQUE NULL_FILTERED INDEX ACT_UNIQ_HI_PROC_INST ON ACT_HI_PROCINST (PROC_INST_ID_);

CREATE TABLE ACT_HI_ACTINST (
    ID_ STRING(64) NOT NULL,
    REV_ INT64 DEFAULT (1),
    PROC_DEF_ID_ STRING(64) NOT NULL,
    PROC_INST_ID_ STRING(64) NOT NULL,
    EXECUTION_ID_ STRING(64) NOT NULL,
    ACT_ID_ STRING(255) NOT NULL,
    TASK_ID_ STRING(64),
    CALL_PROC_INST_ID_ STRING(64),
    ACT_NAME_ STRING(255),
    ACT_TYPE_ STRING(255) NOT NULL,
    ASSIGNEE_ STRING(255),
    COMPLETED_BY_ STRING(255),
    START_TIME_ TIMESTAMP NOT NULL,
    END_TIME_ TIMESTAMP,
    TRANSACTION_ORDER_ INT64,
    DURATION_ INT64,
    DELETE_REASON_ STRING(4000),
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_HI_DETAIL (
    ID_ STRING(64) NOT NULL,
    TYPE_ STRING(255) NOT NULL,
    PROC_INST_ID_ STRING(64),
    EXECUTION_ID_ STRING(64),
    TASK_ID_ STRING(64),
    ACT_INST_ID_ STRING(64),
    NAME_ STRING(255) NOT NULL,
    VAR_TYPE_ STRING(64),
    REV_ INT64,
    TIME_ TIMESTAMP NOT NULL,
    BYTEARRAY_ID_ STRING(64),
    DOUBLE_ FLOAT64,
    LONG_ INT64,
    TEXT_ STRING(4000),
    TEXT2_ STRING(4000)
) PRIMARY KEY (ID_);

CREATE TABLE ACT_HI_COMMENT (
    ID_ STRING(64) NOT NULL,
    TYPE_ STRING(255),
    TIME_ TIMESTAMP NOT NULL,
    USER_ID_ STRING(255),
    TASK_ID_ STRING(64),
    PROC_INST_ID_ STRING(64),
    ACTION_ STRING(255),
    MESSAGE_ STRING(4000),
    FULL_MSG_ BYTES(MAX)
) PRIMARY KEY (ID_);

CREATE TABLE ACT_HI_ATTACHMENT (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    USER_ID_ STRING(255),
    NAME_ STRING(255),
    DESCRIPTION_ STRING(4000),
    TYPE_ STRING(255),
    TASK_ID_ STRING(64),
    PROC_INST_ID_ STRING(64),
    URL_ STRING(4000),
    CONTENT_ID_ STRING(64),
    TIME_ TIMESTAMP
) PRIMARY KEY (ID_);

CREATE INDEX ACT_IDX_HI_PRO_INST_END ON ACT_HI_PROCINST(END_TIME_);
CREATE INDEX ACT_IDX_HI_PRO_I_BUSKEY ON ACT_HI_PROCINST(BUSINESS_KEY_);
CREATE INDEX ACT_IDX_HI_PRO_SUPER_PROCINST ON ACT_HI_PROCINST(SUPER_PROCESS_INSTANCE_ID_);
CREATE INDEX ACT_IDX_HI_ACT_INST_START ON ACT_HI_ACTINST(START_TIME_);
CREATE INDEX ACT_IDX_HI_ACT_INST_END ON ACT_HI_ACTINST(END_TIME_);
CREATE INDEX ACT_IDX_HI_DETAIL_PROC_INST ON ACT_HI_DETAIL(PROC_INST_ID_);
CREATE INDEX ACT_IDX_HI_DETAIL_ACT_INST ON ACT_HI_DETAIL(ACT_INST_ID_);
CREATE INDEX ACT_IDX_HI_DETAIL_TIME ON ACT_HI_DETAIL(TIME_);
CREATE INDEX ACT_IDX_HI_DETAIL_NAME ON ACT_HI_DETAIL(NAME_);
CREATE INDEX ACT_IDX_HI_DETAIL_TASK_ID ON ACT_HI_DETAIL(TASK_ID_);
CREATE INDEX ACT_IDX_HI_PROCVAR_PROC_INST ON ACT_HI_VARINST(PROC_INST_ID_);
CREATE INDEX ACT_IDX_HI_PROCVAR_TASK_ID ON ACT_HI_VARINST(TASK_ID_);
CREATE INDEX ACT_IDX_HI_PROCVAR_EXE ON ACT_HI_VARINST(EXECUTION_ID_);
CREATE INDEX ACT_IDX_HI_ACT_INST_PROCINST ON ACT_HI_ACTINST(PROC_INST_ID_, ACT_ID_);
CREATE INDEX ACT_IDX_HI_ACT_INST_EXEC ON ACT_HI_ACTINST(EXECUTION_ID_, ACT_ID_);
CREATE INDEX ACT_IDX_HI_IDENT_LNK_TASK ON ACT_HI_IDENTITYLINK(TASK_ID_);
CREATE INDEX ACT_IDX_HI_IDENT_LNK_PROCINST ON ACT_HI_IDENTITYLINK(PROC_INST_ID_);
CREATE INDEX ACT_IDX_HI_TASK_INST_PROCINST ON ACT_HI_TASKINST(PROC_INST_ID_);

CREATE TABLE ACT_APP_DEPLOYMENT (
    ID_ STRING(255) NOT NULL,
    NAME_ STRING(255),
    CATEGORY_ STRING(255),
    KEY_ STRING(255),
    DEPLOY_TIME_ TIMESTAMP,
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_APP_DEPLOYMENT_RESOURCE (
    ID_ STRING(255) NOT NULL,
    NAME_ STRING(255),
    DEPLOYMENT_ID_ STRING(255),
    RESOURCE_BYTES_ BYTES(MAX)
) PRIMARY KEY (ID_);

ALTER TABLE ACT_APP_DEPLOYMENT_RESOURCE
    ADD CONSTRAINT ACT_FK_APP_RSRC_DPL
    FOREIGN KEY (DEPLOYMENT_ID_)
    REFERENCES ACT_APP_DEPLOYMENT (ID_);

CREATE INDEX ACT_IDX_APP_RSRC_DPL ON ACT_APP_DEPLOYMENT_RESOURCE(DEPLOYMENT_ID_);

CREATE TABLE ACT_APP_APPDEF (
    ID_ STRING(255) NOT NULL,
    REV_ INT64 NOT NULL,
    NAME_ STRING(255),
    KEY_ STRING(255) NOT NULL,
    VERSION_ INT64 NOT NULL,
    CATEGORY_ STRING(255),
    DEPLOYMENT_ID_ STRING(255),
    RESOURCE_NAME_ STRING(4000),
    DESCRIPTION_ STRING(4000),
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

ALTER TABLE ACT_APP_APPDEF
    ADD CONSTRAINT ACT_FK_APP_DEF_DPLY
    FOREIGN KEY (DEPLOYMENT_ID_)
    REFERENCES ACT_APP_DEPLOYMENT (ID_);

CREATE INDEX ACT_IDX_APP_DEF_DPLY ON ACT_APP_APPDEF(DEPLOYMENT_ID_);

CREATE UNIQUE NULL_FILTERED INDEX ACT_IDX_APP_DEF_UNIQ ON ACT_APP_APPDEF(KEY_, VERSION_, TENANT_ID_);

INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_) VALUES ('app.schema.version', '8.1.0.1', 1);

CREATE TABLE ACT_CMMN_DEPLOYMENT (
    ID_ STRING(255) NOT NULL,
    NAME_ STRING(255),
    CATEGORY_ STRING(255),
    KEY_ STRING(255),
    DEPLOY_TIME_ TIMESTAMP,
    PARENT_DEPLOYMENT_ID_ STRING(255),
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_CMMN_DEPLOYMENT_RESOURCE (
    ID_ STRING(255) NOT NULL,
    NAME_ STRING(255),
    DEPLOYMENT_ID_ STRING(255),
    RESOURCE_BYTES_ BYTES(MAX),
    GENERATED_ BOOL
) PRIMARY KEY (ID_);

CREATE TABLE ACT_CMMN_CASEDEF (
    ID_ STRING(255) NOT NULL,
    REV_ INT64 NOT NULL,
    NAME_ STRING(255),
    KEY_ STRING(255) NOT NULL,
    VERSION_ INT64 NOT NULL,
    CATEGORY_ STRING(255),
    DEPLOYMENT_ID_ STRING(255),
    RESOURCE_NAME_ STRING(4000),
    DESCRIPTION_ STRING(4000),
    HAS_GRAPHICAL_NOTATION_ BOOL,
    DGRM_RESOURCE_NAME_ STRING(4000),
    HAS_START_FORM_KEY_ BOOL,
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_CMMN_RU_CASE_INST (
    ID_ STRING(255) NOT NULL,
    REV_ INT64 NOT NULL,
    BUSINESS_KEY_ STRING(255),
    NAME_ STRING(255),
    PARENT_ID_ STRING(255),
    CASE_DEF_ID_ STRING(255),
    STATE_ STRING(255),
    START_TIME_ TIMESTAMP,
    START_USER_ID_ STRING(255),
    CALLBACK_ID_ STRING(255),
    CALLBACK_TYPE_ STRING(255),
    LOCK_TIME_ TIMESTAMP,
    LOCK_OWNER_ STRING(255),
    IS_COMPLETEABLE_ BOOL,
    REFERENCE_ID_ STRING(255),
    REFERENCE_TYPE_ STRING(255),
    LAST_REACTIVATION_TIME_ TIMESTAMP,
    LAST_REACTIVATION_USER_ID_ STRING(255),
    BUSINESS_STATUS_ STRING(255),
    DUE_DATE_ TIMESTAMP,
    CLAIM_TIME_ TIMESTAMP,
    CLAIMED_BY_ STRING(255),
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_CMMN_RU_PLAN_ITEM_INST (
    ID_ STRING(255) NOT NULL,
    REV_ INT64 NOT NULL,
    CASE_DEF_ID_ STRING(255),
    CASE_INST_ID_ STRING(255),
    STAGE_INST_ID_ STRING(255),
    IS_STAGE_ BOOL,
    ELEMENT_ID_ STRING(255),
    NAME_ STRING(255),
    STATE_ STRING(255),
    CREATE_TIME_ TIMESTAMP,
    START_USER_ID_ STRING(255),
    ASSIGNEE_ STRING(255),
    COMPLETED_BY_ STRING(255),
    REFERENCE_ID_ STRING(255),
    REFERENCE_TYPE_ STRING(255),
    ITEM_DEFINITION_ID_ STRING(255),
    ITEM_DEFINITION_TYPE_ STRING(255),
    IS_COMPLETEABLE_ BOOL,
    IS_COUNT_ENABLED_ BOOL,
    VAR_COUNT_ INT64,
    SENTRY_PART_INST_COUNT_ INT64,
    LAST_AVAILABLE_TIME_ TIMESTAMP,
    LAST_ENABLED_TIME_ TIMESTAMP,
    LAST_DISABLED_TIME_ TIMESTAMP,
    LAST_STARTED_TIME_ TIMESTAMP,
    LAST_SUSPENDED_TIME_ TIMESTAMP,
    COMPLETED_TIME_ TIMESTAMP,
    OCCURRED_TIME_ TIMESTAMP,
    TERMINATED_TIME_ TIMESTAMP,
    FAILED_TIME_ TIMESTAMP,
    EXIT_TIME_ TIMESTAMP,
    ENDED_TIME_ TIMESTAMP,
    ENTRY_CRITERION_ID_ STRING(255),
    EXIT_CRITERION_ID_ STRING(255),
    EXTRA_VALUE_ STRING(255),
    DERIVED_CASE_DEF_ID_ STRING(255),
    LAST_UNAVAILABLE_TIME_ TIMESTAMP,
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_CMMN_RU_SENTRY_PART_INST (
    ID_ STRING(255) NOT NULL,
    REV_ INT64 NOT NULL,
    CASE_DEF_ID_ STRING(255),
    CASE_INST_ID_ STRING(255),
    PLAN_ITEM_INST_ID_ STRING(255),
    ON_PART_ID_ STRING(255),
    IF_PART_ID_ STRING(255),
    TIME_STAMP_ TIMESTAMP
) PRIMARY KEY (ID_);

CREATE TABLE ACT_CMMN_RU_MIL_INST (
    ID_ STRING(255) NOT NULL,
    NAME_ STRING(255) NOT NULL,
    TIME_STAMP_ TIMESTAMP NOT NULL,
    CASE_INST_ID_ STRING(255) NOT NULL,
    CASE_DEF_ID_ STRING(255) NOT NULL,
    ELEMENT_ID_ STRING(255) NOT NULL,
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_CMMN_HI_CASE_INST (
    ID_ STRING(255) NOT NULL,
    REV_ INT64 NOT NULL,
    BUSINESS_KEY_ STRING(255),
    NAME_ STRING(255),
    PARENT_ID_ STRING(255),
    CASE_DEF_ID_ STRING(255),
    STATE_ STRING(255),
    START_TIME_ TIMESTAMP,
    END_TIME_ TIMESTAMP,
    START_USER_ID_ STRING(255),
    CALLBACK_ID_ STRING(255),
    CALLBACK_TYPE_ STRING(255),
    REFERENCE_ID_ STRING(255),
    REFERENCE_TYPE_ STRING(255),
    LAST_REACTIVATION_TIME_ TIMESTAMP,
    LAST_REACTIVATION_USER_ID_ STRING(255),
    BUSINESS_STATUS_ STRING(255),
    DUE_DATE_ TIMESTAMP,
    CLAIM_TIME_ TIMESTAMP,
    CLAIMED_BY_ STRING(255),
    TENANT_ID_ STRING(255) DEFAULT (''),
    END_USER_ID_ STRING(255)
) PRIMARY KEY (ID_);

CREATE TABLE ACT_CMMN_HI_MIL_INST (
    ID_ STRING(255) NOT NULL,
    REV_ INT64 NOT NULL,
    NAME_ STRING(255) NOT NULL,
    TIME_STAMP_ TIMESTAMP NOT NULL,
    CASE_INST_ID_ STRING(255) NOT NULL,
    CASE_DEF_ID_ STRING(255) NOT NULL,
    ELEMENT_ID_ STRING(255) NOT NULL,
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_CMMN_HI_PLAN_ITEM_INST (
    ID_ STRING(255) NOT NULL,
    REV_ INT64 NOT NULL,
    NAME_ STRING(255),
    STATE_ STRING(255),
    CASE_DEF_ID_ STRING(255),
    CASE_INST_ID_ STRING(255),
    STAGE_INST_ID_ STRING(255),
    IS_STAGE_ BOOL,
    ELEMENT_ID_ STRING(255),
    ITEM_DEFINITION_ID_ STRING(255),
    ITEM_DEFINITION_TYPE_ STRING(255),
    CREATE_TIME_ TIMESTAMP,
    LAST_AVAILABLE_TIME_ TIMESTAMP,
    LAST_ENABLED_TIME_ TIMESTAMP,
    LAST_DISABLED_TIME_ TIMESTAMP,
    LAST_STARTED_TIME_ TIMESTAMP,
    LAST_SUSPENDED_TIME_ TIMESTAMP,
    COMPLETED_TIME_ TIMESTAMP,
    OCCURRED_TIME_ TIMESTAMP,
    TERMINATED_TIME_ TIMESTAMP,
    FAILED_TIME_ TIMESTAMP,
    EXIT_TIME_ TIMESTAMP,
    ENDED_TIME_ TIMESTAMP,
    LAST_UPDATED_TIME_ TIMESTAMP,
    START_USER_ID_ STRING(255),
    ASSIGNEE_ STRING(255),
    COMPLETED_BY_ STRING(255),
    REFERENCE_ID_ STRING(255),
    REFERENCE_TYPE_ STRING(255),
    ENTRY_CRITERION_ID_ STRING(255),
    EXIT_CRITERION_ID_ STRING(255),
    SHOW_IN_OVERVIEW_ BOOL,
    EXTRA_VALUE_ STRING(255),
    DERIVED_CASE_DEF_ID_ STRING(255),
    LAST_UNAVAILABLE_TIME_ TIMESTAMP,
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

ALTER TABLE ACT_CMMN_DEPLOYMENT_RESOURCE
    ADD CONSTRAINT ACT_FK_CMMN_RSRC_DPL
    FOREIGN KEY (DEPLOYMENT_ID_)
    REFERENCES ACT_CMMN_DEPLOYMENT (ID_);

CREATE INDEX ACT_IDX_CMMN_RSRC_DPL ON ACT_CMMN_DEPLOYMENT_RESOURCE (DEPLOYMENT_ID_);

ALTER TABLE ACT_CMMN_CASEDEF
    ADD CONSTRAINT ACT_FK_CASE_DEF_DPLY
    FOREIGN KEY (DEPLOYMENT_ID_)
    REFERENCES ACT_CMMN_DEPLOYMENT (ID_);

CREATE INDEX ACT_IDX_CASE_DEF_DPLY ON ACT_CMMN_CASEDEF (DEPLOYMENT_ID_);

CREATE UNIQUE NULL_FILTERED INDEX ACT_IDX_CASE_DEF_UNIQ ON ACT_CMMN_CASEDEF (KEY_, VERSION_, TENANT_ID_);

ALTER TABLE ACT_CMMN_RU_CASE_INST
    ADD CONSTRAINT ACT_FK_CASE_INST_CASE_DEF
    FOREIGN KEY (CASE_DEF_ID_)
    REFERENCES ACT_CMMN_CASEDEF (ID_);

CREATE INDEX ACT_IDX_CASE_INST_CASE_DEF ON ACT_CMMN_RU_CASE_INST (CASE_DEF_ID_);
CREATE INDEX ACT_IDX_CASE_INST_PARENT ON ACT_CMMN_RU_CASE_INST (PARENT_ID_);
CREATE INDEX ACT_IDX_CASE_INST_REF_ID_ ON ACT_CMMN_RU_CASE_INST (REFERENCE_ID_);

ALTER TABLE ACT_CMMN_RU_PLAN_ITEM_INST
    ADD CONSTRAINT ACT_FK_PLAN_ITEM_CASE_DEF
    FOREIGN KEY (CASE_DEF_ID_)
    REFERENCES ACT_CMMN_CASEDEF (ID_);

CREATE INDEX ACT_IDX_PLAN_ITEM_CASE_DEF ON ACT_CMMN_RU_PLAN_ITEM_INST (CASE_DEF_ID_);

ALTER TABLE ACT_CMMN_RU_PLAN_ITEM_INST
    ADD CONSTRAINT ACT_FK_PLAN_ITEM_CASE_INST
    FOREIGN KEY (CASE_INST_ID_)
    REFERENCES ACT_CMMN_RU_CASE_INST (ID_);

CREATE INDEX ACT_IDX_PLAN_ITEM_CASE_INST ON ACT_CMMN_RU_PLAN_ITEM_INST (CASE_INST_ID_);
CREATE INDEX ACT_IDX_PLAN_ITEM_STAGE_INST ON ACT_CMMN_RU_PLAN_ITEM_INST (STAGE_INST_ID_);

ALTER TABLE ACT_CMMN_RU_SENTRY_PART_INST
    ADD CONSTRAINT ACT_FK_SENTRY_CASE_DEF
    FOREIGN KEY (CASE_DEF_ID_)
    REFERENCES ACT_CMMN_CASEDEF (ID_);

CREATE INDEX ACT_IDX_SENTRY_CASE_DEF ON ACT_CMMN_RU_SENTRY_PART_INST (CASE_DEF_ID_);

ALTER TABLE ACT_CMMN_RU_SENTRY_PART_INST
    ADD CONSTRAINT ACT_FK_SENTRY_CASE_INST
    FOREIGN KEY (CASE_INST_ID_)
    REFERENCES ACT_CMMN_RU_CASE_INST (ID_);

CREATE INDEX ACT_IDX_SENTRY_CASE_INST ON ACT_CMMN_RU_SENTRY_PART_INST (CASE_INST_ID_);

ALTER TABLE ACT_CMMN_RU_SENTRY_PART_INST
    ADD CONSTRAINT ACT_FK_SENTRY_PLAN_ITEM
    FOREIGN KEY (PLAN_ITEM_INST_ID_)
    REFERENCES ACT_CMMN_RU_PLAN_ITEM_INST (ID_);

CREATE INDEX ACT_IDX_SENTRY_PLAN_ITEM ON ACT_CMMN_RU_SENTRY_PART_INST (PLAN_ITEM_INST_ID_);

ALTER TABLE ACT_CMMN_RU_MIL_INST
    ADD CONSTRAINT ACT_FK_MIL_CASE_DEF
    FOREIGN KEY (CASE_DEF_ID_)
    REFERENCES ACT_CMMN_CASEDEF (ID_);

CREATE INDEX ACT_IDX_MIL_CASE_DEF ON ACT_CMMN_RU_MIL_INST (CASE_DEF_ID_);

ALTER TABLE ACT_CMMN_RU_MIL_INST
    ADD CONSTRAINT ACT_FK_MIL_CASE_INST
    FOREIGN KEY (CASE_INST_ID_)
    REFERENCES ACT_CMMN_RU_CASE_INST (ID_);

CREATE INDEX ACT_IDX_MIL_CASE_INST ON ACT_CMMN_RU_MIL_INST (CASE_INST_ID_);

CREATE INDEX ACT_IDX_HI_CASE_INST_END ON ACT_CMMN_HI_CASE_INST (END_TIME_);
CREATE INDEX ACT_IDX_HI_PLAN_ITEM_INST_CASE ON ACT_CMMN_HI_PLAN_ITEM_INST (CASE_INST_ID_);

INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_) VALUES ('cmmn.schema.version', '8.1.0.1', 1);

CREATE TABLE ACT_DMN_DEPLOYMENT (
    ID_ STRING(255) NOT NULL,
    NAME_ STRING(255),
    CATEGORY_ STRING(255),
    DEPLOY_TIME_ TIMESTAMP,
    TENANT_ID_ STRING(255),
    PARENT_DEPLOYMENT_ID_ STRING(255)
) PRIMARY KEY (ID_);

CREATE TABLE ACT_DMN_DEPLOYMENT_RESOURCE (
    ID_ STRING(255) NOT NULL,
    NAME_ STRING(255),
    DEPLOYMENT_ID_ STRING(255),
    RESOURCE_BYTES_ BYTES(MAX)
) PRIMARY KEY (ID_);

CREATE TABLE ACT_DMN_DECISION (
    ID_ STRING(255) NOT NULL,
    NAME_ STRING(255),
    VERSION_ INT64,
    KEY_ STRING(255),
    CATEGORY_ STRING(255),
    DECISION_TYPE_ STRING(255),
    DEPLOYMENT_ID_ STRING(255),
    TENANT_ID_ STRING(255),
    RESOURCE_NAME_ STRING(255),
    DESCRIPTION_ STRING(255)
) PRIMARY KEY (ID_);

CREATE TABLE ACT_DMN_HI_DECISION_EXECUTION (
    ID_ STRING(255) NOT NULL,
    DECISION_DEFINITION_ID_ STRING(255),
    DEPLOYMENT_ID_ STRING(255),
    START_TIME_ TIMESTAMP,
    END_TIME_ TIMESTAMP,
    INSTANCE_ID_ STRING(255),
    EXECUTION_ID_ STRING(255),
    ACTIVITY_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    FAILED_ BOOL DEFAULT (FALSE),
    TENANT_ID_ STRING(255),
    EXECUTION_JSON_ STRING(MAX)
) PRIMARY KEY (ID_);

ALTER TABLE ACT_DMN_DEPLOYMENT_RESOURCE
    ADD CONSTRAINT ACT_FK_DMN_RSRC_DPL
    FOREIGN KEY (DEPLOYMENT_ID_)
    REFERENCES ACT_DMN_DEPLOYMENT (ID_);

CREATE INDEX ACT_IDX_DMN_RSRC_DPL ON ACT_DMN_DEPLOYMENT_RESOURCE (DEPLOYMENT_ID_);

CREATE UNIQUE NULL_FILTERED INDEX ACT_IDX_DMN_DEC_UNIQ ON ACT_DMN_DECISION(KEY_, VERSION_, TENANT_ID_);

CREATE INDEX ACT_IDX_DMN_INSTANCE_ID ON ACT_DMN_HI_DECISION_EXECUTION(INSTANCE_ID_);

INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_) VALUES ('dmn.schema.version', '8.1.0.1', 1);

CREATE TABLE FLW_EVENT_DEPLOYMENT (
    ID_ STRING(255) NOT NULL,
    NAME_ STRING(255),
    CATEGORY_ STRING(255),
    DEPLOY_TIME_ TIMESTAMP,
    TENANT_ID_ STRING(255),
    PARENT_DEPLOYMENT_ID_ STRING(255)
) PRIMARY KEY (ID_);

CREATE TABLE FLW_EVENT_RESOURCE (
    ID_ STRING(255) NOT NULL,
    NAME_ STRING(255),
    DEPLOYMENT_ID_ STRING(255),
    RESOURCE_BYTES_ BYTES(MAX)
) PRIMARY KEY (ID_);

CREATE TABLE FLW_EVENT_DEFINITION (
    ID_ STRING(255) NOT NULL,
    NAME_ STRING(255),
    VERSION_ INT64,
    KEY_ STRING(255),
    CATEGORY_ STRING(255),
    DEPLOYMENT_ID_ STRING(255),
    TENANT_ID_ STRING(255),
    RESOURCE_NAME_ STRING(255),
    DESCRIPTION_ STRING(255)
) PRIMARY KEY (ID_);

ALTER TABLE FLW_EVENT_RESOURCE
    ADD CONSTRAINT FLW_FK_EVENT_RSRC_DPL
    FOREIGN KEY (DEPLOYMENT_ID_)
    REFERENCES FLW_EVENT_DEPLOYMENT (ID_);

CREATE INDEX FLW_IDX_EVENT_RSRC_DPL ON FLW_EVENT_RESOURCE (DEPLOYMENT_ID_);

CREATE UNIQUE NULL_FILTERED INDEX ACT_IDX_EVENT_DEF_UNIQ ON FLW_EVENT_DEFINITION(KEY_, VERSION_, TENANT_ID_);

CREATE TABLE FLW_CHANNEL_DEFINITION (
    ID_ STRING(255) NOT NULL,
    NAME_ STRING(255),
    VERSION_ INT64,
    KEY_ STRING(255),
    CATEGORY_ STRING(255),
    TYPE_ STRING(255),
    IMPLEMENTATION_ STRING(255),
    DEPLOYMENT_ID_ STRING(255),
    CREATE_TIME_ TIMESTAMP,
    TENANT_ID_ STRING(255),
    RESOURCE_NAME_ STRING(255),
    DESCRIPTION_ STRING(255)
) PRIMARY KEY (ID_);

CREATE UNIQUE NULL_FILTERED INDEX ACT_IDX_CHANNEL_DEF_UNIQ ON FLW_CHANNEL_DEFINITION(KEY_, VERSION_, TENANT_ID_);

INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_) VALUES ('eventregistry.schema.version', '8.1.0.1', 1);

CREATE TABLE ACT_ID_PROPERTY (
    NAME_ STRING(64) NOT NULL,
    VALUE_ STRING(300),
    REV_ INT64
) PRIMARY KEY (NAME_);

INSERT INTO ACT_ID_PROPERTY (NAME_, VALUE_, REV_) VALUES ('schema.version', '8.1.0.1', 1);

CREATE TABLE ACT_ID_BYTEARRAY (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    NAME_ STRING(255),
    BYTES_ BYTES(MAX)
) PRIMARY KEY (ID_);

CREATE TABLE ACT_ID_GROUP (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    NAME_ STRING(255),
    TYPE_ STRING(255)
) PRIMARY KEY (ID_);

CREATE TABLE ACT_ID_MEMBERSHIP (
    USER_ID_ STRING(64) NOT NULL,
    GROUP_ID_ STRING(64) NOT NULL
) PRIMARY KEY (USER_ID_, GROUP_ID_);

CREATE TABLE ACT_ID_USER (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    FIRST_ STRING(255),
    LAST_ STRING(255),
    DISPLAY_NAME_ STRING(255),
    EMAIL_ STRING(255),
    PWD_ STRING(255),
    PICTURE_ID_ STRING(64),
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_ID_INFO (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    USER_ID_ STRING(64),
    TYPE_ STRING(64),
    KEY_ STRING(255),
    VALUE_ STRING(255),
    PASSWORD_ BYTES(MAX),
    PARENT_ID_ STRING(255)
) PRIMARY KEY (ID_);

CREATE TABLE ACT_ID_TOKEN (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    TOKEN_VALUE_ STRING(255),
    TOKEN_DATE_ TIMESTAMP,
    IP_ADDRESS_ STRING(255),
    USER_AGENT_ STRING(255),
    USER_ID_ STRING(255),
    TOKEN_DATA_ STRING(2000)
) PRIMARY KEY (ID_);

CREATE TABLE ACT_ID_PRIV (
    ID_ STRING(64) NOT NULL,
    NAME_ STRING(255) NOT NULL
) PRIMARY KEY (ID_);

CREATE TABLE ACT_ID_PRIV_MAPPING (
    ID_ STRING(64) NOT NULL,
    PRIV_ID_ STRING(64) NOT NULL,
    USER_ID_ STRING(255),
    GROUP_ID_ STRING(255)
) PRIMARY KEY (ID_);

CREATE INDEX ACT_IDX_MEMB_GROUP ON ACT_ID_MEMBERSHIP(GROUP_ID_);
ALTER TABLE ACT_ID_MEMBERSHIP
    ADD CONSTRAINT ACT_FK_MEMB_GROUP
    FOREIGN KEY (GROUP_ID_)
    REFERENCES ACT_ID_GROUP (ID_);

CREATE INDEX ACT_IDX_MEMB_USER ON ACT_ID_MEMBERSHIP(USER_ID_);
ALTER TABLE ACT_ID_MEMBERSHIP
    ADD CONSTRAINT ACT_FK_MEMB_USER
    FOREIGN KEY (USER_ID_)
    REFERENCES ACT_ID_USER (ID_);

CREATE INDEX ACT_IDX_PRIV_MAPPING ON ACT_ID_PRIV_MAPPING(PRIV_ID_);
ALTER TABLE ACT_ID_PRIV_MAPPING
    ADD CONSTRAINT ACT_FK_PRIV_MAPPING
    FOREIGN KEY (PRIV_ID_)
    REFERENCES ACT_ID_PRIV (ID_);

CREATE INDEX ACT_IDX_PRIV_USER ON ACT_ID_PRIV_MAPPING(USER_ID_);
CREATE INDEX ACT_IDX_PRIV_GROUP ON ACT_ID_PRIV_MAPPING(GROUP_ID_);

CREATE UNIQUE NULL_FILTERED INDEX ACT_UNIQ_PRIV_NAME ON ACT_ID_PRIV(NAME_);

