[[IDM]]

== Identity management
（开源版与商业版逻辑不一样 盘古BPM）
从Flowable V6开始，身份管理（IDM）组件已经从Flowable engine模块中提取出来，逻辑转移到几个单独的模块：Flowable IDM api、Flowable IDM engine、Flowable IDM spring和Flowable IDM engine configurator。分离IDM逻辑的主要原因是它不是Flowable引擎的核心，在很多情况下，当Flowable引擎嵌入到应用程序中时，标识逻辑不被使用或不需要。
默认情况下，IDM引擎在可流动引擎启动时初始化并启动。这将导致在FlowableV5中执行和可用相同的标识逻辑。idm引擎管理自己的数据库架构和以下实体：
* User and UserEntity, the user information.
* Group and GroupEntity, the group information.
* MembershipEntity, the memberships of users in groups
* Privilege and PrivilegeEntity, a privilege definition (for example used for controlling access to the UI apps, such as the Flowable Modeler and Flowable Task app)
* PrivilegeMappingEntity, linking a user and/or group to a privilege
* Token and TokenEntity, an authentication token used by the UI apps  

由于数据库包含过去和正在进行的实例的历史实体，因此您可能需要考虑查询这些表，以尽量减少对运行时流程实例数据的访问，从而保持运行时执行的性能。

[[IDM engine configuration]]


=== IDM engine configuration

默认情况下，可流动发动机以+org.flowable.idm.engine.configurator.IdmEngineConfigurator+. 此配置程序使用与可流动流程引擎配置相同的数据源配置。使用标识组件不需要额外的配置，因为它是在Flowable v5中配置的。

当流程引擎中不需要标识逻辑时，可以在流程引擎配置中禁用IDM引擎。

[source,xml,linenums]
----
<bean id="processEngineConfiguration" class="org.flowable.engine.impl.cfg.StandaloneInMemProcessEngineConfiguration">
  <property name="disableIdmEngine" value="true" />
  ...
</bean>
----

这意味着不能使用任何用户和组查询，并且不能为用户检索任务查询中的候选组。


默认情况下，用户密码将以纯文本形式保存在IDM数据库表中。为了确保密码已编码，您可以在流程引擎配置中定义密码编码器。
[source,xml,linenums]
----
<bean id="bCryptEncoder"
      class="org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder"/>
      
<bean id="passwordEncoder" class="org.flowable.idm.spring.authentication.SpringEncoder">
    <constructor-arg ref="bCryptEncoder"/>
</bean>

<bean id="processEngineConfiguration" class="org.flowable.engine.impl.cfg.StandaloneInMemProcessEngineConfiguration">
  <property name="passwordEncoder" ref="passwordEncoder" />
  ...
</bean>
----

在本例中，使用了ShaPasswordEncoder，但也可以使用org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder 例如。不使用弹簧时，也可以使用org.flowable.idm.engine.impl.authentication.ApacheDigester 对密码进行编码。
默认的IDM引擎配置器也可以被重写，以自定义方式初始化IDM引擎。LDAPConfigurator就是一个很好的例子

重写默认IDM引擎以使用LDAP服务器而不是默认IDM数据库表的实现。process engine配置的+idmProcessEngineConfigurator+属性可用于设置自定义配置程序，如LDAPConfigurator

[source,xml,linenums]
----
<bean id="processEngineConfiguration" class="...SomeProcessEngineConfigurationClass">
    ...
    <property name="idmProcessEngineConfigurator">
      <bean class="org.flowable.ldap.LDAPConfigurator">

        <!-- Server connection params -->
        <property name="server" value="ldap://localhost" />
        <property name="port" value="33389" />
        <property name="user" value="uid=admin, ou=users, o=flowable" />
        <property name="password" value="pass" />

        <!-- Query params -->
        <property name="baseDn" value="o=flowable" />
        <property name="queryUserByUserId" value="(&(objectClass=inetOrgPerson)(uid={0}))" />
        <property name="queryUserByFullNameLike" value="(&(objectClass=inetOrgPerson)(|({0}=*{1}*)({2}=*{3}*)))" />
        <property name="queryGroupsForUser" value="(&(objectClass=groupOfUniqueNames)(uniqueMember={0}))" />

        <!-- Attribute config -->
        <property name="userIdAttribute" value="uid" />
        <property name="userFirstNameAttribute" value="cn" />
        <property name="userLastNameAttribute" value="sn" />
        <property name="userEmailAttribute" value="mail" />


        <property name="groupIdAttribute" value="cn" />
        <property name="groupNameAttribute" value="cn" />

      </bean>
    </property>
</bean>
----
