 alter table ACT_HI_TASKINST add SCOPE_ID_ NVARCHAR2(255);
alter table ACT_HI_TASKINST add SUB_SCOPE_ID_ NVARCHAR2(255);
alter table ACT_HI_TASKINST add SCOPE_TYPE_ NVARCHAR2(255);
alter table ACT_HI_TASKINST add SCOPE_DEFINITION_ID_ NVARCHAR2(255);

create index ACT_IDX_HI_TASK_SCOPE on ACT_HI_TASKINST(SCOPE_ID_, SCOPE_TYPE_);
create index ACT_IDX_HI_TASK_SUB_SCOPE on ACT_HI_TASKINST(SUB_SCOPE_ID_, SCOPE_TYPE_);
create index ACT_IDX_HI_TASK_SCOPE_DEF on ACT_HI_TASKINST(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);
alter table ACT_HI_VARINST add SCOPE_ID_ NVARCHAR2(255);
alter table ACT_HI_VARINST add SUB_SCOPE_ID_ NVARCHAR2(255);
alter table ACT_HI_VARINST add SCOPE_TYPE_ NVARCHAR2(255);

create index ACT_IDX_HI_VAR_SCOPE_ID_TYPE on ACT_HI_VARINST(SCOPE_ID_, SCOPE_TYPE_);
create index ACT_IDX_HI_VAR_SUB_ID_TYPE on ACT_HI_VARINST(SUB_SCOPE_ID_, SCOPE_TYPE_);

