
== Introduction

[[license]]

=== License

Flowable is distributed under link:$$http://www.apache.org/licenses/LICENSE-2.0.html$$[the Apache V2 license].

[[download]]

=== Download

link:$$http://www.flowable.org/downloads.html$$[http://www.flowable.org/downloads.html]

[[sources]]

=== Sources

The distribution contains most of the sources as JAR files. The source code of Flowable can be found on link:$$https://github.com/flowable/flowable-engine$$[https://github.com/flowable/flowable-engine]

[[experimental]]

=== Experimental Features

Sections marked with *[EXPERIMENTAL]* should not be considered stable.

All classes that have +.impl.+ in the package name are internal implementation classes and cannot be considered stable or guaranteed in any way.  However, if the User Guide mentions any classes as configuration values, they are supported and can be considered stable.

[[required.software]]

=== Required software

Flowable runs on a JDK higher than or equal to version 8. Go to link:$$http://www.oracle.com/technetwork/java/javase/downloads/index.html$$[Oracle Java SE downloads] and click on button "Download JDK".  There are installation instructions on that page as well. To verify that your installation was successful, run +java -version+ on the command line.  That should print the installed version of your JDK.


[[reporting.problems]]

=== Reporting problems


Questions and comments can be discussed on the on link:$$https://forum.flowable.org$$[the Flowable forum]. Issues can be created in link:$$https://github.com/flowable/flowable-engine/issues$$[our Github issue tracker].

[[internal]]

=== Internal implementation classes

In the JAR file, all classes in packages that have +.impl.+ in them are implementation classes and should be considered internal. No stability guarantees are given on classes or interfaces that are in implementation classes.
