version: '2'
services:
    flowable-idm-app:
        image: flowable/flowable-idm
        depends_on:
            - flowable-idm-db
        environment:
            - spring.datasource.driver-class-name=org.postgresql.Driver
            - spring.datasource.url=jdbc:postgresql://flowable-idm-db:5432/flowable
            - spring.datasource.username=flowable
            - spring.datasource.password=flowable
        ports:
            - 8080:8080
        entrypoint: ["./wait-for-something.sh", "flowable-idm-db", "5432", "PostgreSQL", "java", "-jar", "flowable-idm.jar", "-httpPort=8080", "-httpProtocol=org.apache.coyote.http11.Http11NioProtocol"]
    flowable-idm-db:
        extends:
            file: postgres.yml
            service: flowable-idm-postgres
