version: '2'
services:
    flowable-idm-app:
        image: flowable/flowable-idm
        depends_on:
            - flowable-idm-db
        environment:
            - SERVER_PORT=8080
            - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
            - SPRING_DATASOURCE_URL=jdbc:postgresql://flowable-idm-db:5432/flowable
            - SPRING_DATASOURCE_USERNAME=flowable
            - SPRING_DATASOURCE_PASSWORD=flowable
        ports:
            - 8080:8080
        entrypoint: ["./wait-for-something.sh", "flowable-idm-db", "5432", "PostgreSQL", "java", "-jar", "flowable-idm.war"]
    flowable-idm-db:
        extends:
            file: postgres.yml
            service: flowable-idm-postgres
