version: '3.6'
services:
    flowable-idm-app:
        image: flowable/flowable-idm
        depends_on:
            - flowable-idm-db
        environment:
            - SERVER_PORT=8080
            - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
            - SPRING_DATASOURCE_URL=jdbc:postgresql://flowable-idm-db:5432/flowable
            - SPRING_DATASOURCE_USERNAME=flowable
            - SPRING_DATASOURCE_PASSWORD=flowable
        ports:
            - 8080:8080
        entrypoint: ["./wait-for-something.sh", "flowable-idm-db", "5432", "PostgreSQL", "java", "-jar", "app.war"]
    flowable-idm-db:
        image: postgres:9.6-alpine
        container_name: flowable-idm-postgres
        environment:
            - POSTGRES_PASSWORD=flowable
            - POSTGRES_USER=flowable
            - POSTGRES_DB=flowable
        ports:
            - 5433:5432
        command: postgres