alter table ACT_HI_VARINST add SCOPE_ID_ NVARCHAR2(255);
alter table ACT_HI_VARINST add SCOPE_TYPE_ NVARCHAR2(255);

create index ACT_IDX_HI_VAR_SCOPE_ID_TYPE on ACT_HI_VARINST(SCOPE_ID_, SCOPE_TYPE_);
