
== Introduction

[[license]]

=== License

Flowable is distributed under link:$$http://www.apache.org/licenses/LICENSE-2.0.html$$[the Apache V2 license].

[[download]]

=== Download

link:$$http://flowable.org/downloads.html$$[http://flowable.org/downloads.html]

[[sources]]

=== Sources

The distribution contains most of the sources as jar files. The source code of Flowable can be found on
  link:$$https://github.com/Flowable/Flowable$$[https://github.com/Flowable/Flowable]


[[required.software]]

=== Required software

==== JDK 7+

Flowable runs on a JDK higher than or equal to version 7.  Go to link:$$http://www.oracle.com/technetwork/java/javase/downloads/index.html$$[Oracle Java SE downloads] and click on button "Download JDK".  There are installation instructions on that page as well. To verify that your installation was successful, run +java -version+ on the command line.  That should print the installed version of your JDK.


==== IDE

Flowable development can be done with the IDE of your choice. If you would like to use the Flowable Designer then you need Eclipse Mars or Neon.
Download the Eclipse distribution of your choice from link:$$http://www.eclipse.org/downloads/$$[the Eclipse download page]. Unzip the downloaded file and
then you should be able to start it with the eclipse file in the directory +eclipse+.
Further in this user guide, there is a section on <<eclipseDesignerInstallation,installing our eclipse designer plugin>>.


[[reporting.problems]]

=== Reporting problems

Every self-respecting developer should have read link:$$http://www.catb.org/~esr/faqs/smart-questions.html$$[How to ask questions the smart way].


After you've done that you can post questions and comments on link:$$http://forums.flowable.org$$[the Users forum] and create issues in link:$$https://github.com/Flowable/Flowable/issues$$[our Github issue tracker].


[[experimental]]

=== Experimental features

Sections marked with *[EXPERIMENTAL]* should
  not be considered stable.


All classes that have +.impl.+ in the package name are internal implementation classes and cannot be considered stable.  However, if the user guide mentions those classes as configuration values, they are supported and can be considered stable.


[[internal]]

=== Internal implementation classes

In the jar file, all classes in packages that have +.impl.+ (e.g. ++org.flowable.form.engine.impl.db++) in them are implementation classes and should be considered internal. No stability guarantees are given on classes or interfaces that are in implementation classes.
