ALTER TABLE ACT_APP_DEPLOYMENT_RESOURCE DROP CONSTRAINT ACT_FK_APP_RSRC_DPL;
ALTER TABLE ACT_APP_APPDEF DROP CONSTRAINT ACT_FK_APP_DEF_DPLY;

DROP INDEX IF EXISTS ACT_IDX_APP_RSRC_DPL;
DROP INDEX IF EXISTS ACT_IDX_APP_DEF_DPLY;
DROP INDEX IF EXISTS ACT_IDX_APP_DEF_UNIQ;

DROP TABLE IF EXISTS ACT_APP_APPDEF;
DROP TABLE IF EXISTS ACT_APP_DEPLOYMENT_RESOURCE;
DROP TABLE IF EXISTS ACT_APP_DEPLOYMENT;
