IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ACT_IDX_APP_RSRC_DPL') drop index ACT_APP_DEPLOYMENT_RESOURCE.ACT_IDX_APP_RSRC_DPL;
IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ACT_IDX_APP_DEF_DPLY') drop index ACT_APP_APPDEF.ACT_IDX_APP_DEF_DPLY;
IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ACT_IDX_APP_DEF_UNIQ') drop index ACT_APP_APPDEF.ACT_IDX_APP_DEF_UNIQ;
if exists (select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ACT_APP_APPDEF') alter table ACT_APP_APPDEF drop constraint ACT_FK_APP_DEF_DPLY;

if exists (select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ACT_APP_APPDEF') drop table ACT_APP_APPDEF;
if exists (select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ACT_APP_DEPLOYMENT_RESOURCE') drop table ACT_APP_DEPLOYMENT_RESOURCE;
if exists (select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ACT_APP_DEPLOYMENT') drop table ACT_APP_DEPLOYMENT;
