FLOWABLE_REMEMBER_ME=dlU4ZnZxTlA1JTJCc0NTTlZjR2t3aFlnJTNEJTNEOlhJQ0hpeXZWRE1LMENkbjBBSENsZWclM0QlM0Q;

###
# GET breakpoints
GET http://localhost:9999/flowable-task/app/rest/cmmn-debugger/breakpoints
Authorization: Basic admin test
Content-Type: application/json
Cookie: FLOWABLE_REMEMBER_ME=dlU4ZnZxTlA1JTJCc0NTTlZjR2t3aFlnJTNEJTNEOlhJQ0hpeXZWRE1LMENkbjBBSENsZWclM0QlM0Q;

###
# Add break point
POST http://localhost:9999/flowable-task/app/rest/cmmn-debugger/breakpoints
Authorization: Basic admin test
Content-Type: application/json
Cookie: FLOWABLE_REMEMBER_ME=dlU4ZnZxTlA1JTJCc0NTTlZjR2t3aFlnJTNEJTNEOlhJQ0hpeXZWRE1LMENkbjBBSENsZWclM0QlM0Q;

{
    "elementId": "humanTask1"
}

###
# add a breakpoint on sentry
POST http://localhost:9999/flowable-task/app/rest/cmmn-debugger/breakpoints
Authorization: Basic admin test
Content-Type: application/json
Cookie: FLOWABLE_REMEMBER_ME=dlU4ZnZxTlA1JTJCc0NTTlZjR2t3aFlnJTNEJTNEOlhJQ0hpeXZWRE1LMENkbjBBSENsZWclM0QlM0Q;

{
  "elementId": "sid-C22985EF-5BC6-4C4C-92D3-6A9CF23D4888"
}


###
# Delete breakpoint
DELETE http://localhost:9999/flowable-task/app/rest/cmmn-debugger/breakpoints
Authorization: Basic admin test
Content-Type: application/json
Cookie: FLOWABLE_REMEMBER_ME=dlU4ZnZxTlA1JTJCc0NTTlZjR2t3aFlnJTNEJTNEOlhJQ0hpeXZWRE1LMENkbjBBSENsZWclM0QlM0Q;

{
  "elementId": "humanTask1"
}

###
# Get broken plan items
GET http://localhost:9999/flowable-task/app/rest/cmmn-debugger/planitems/e0cf19fb-70f8-11e9-a8b9-b46bfcd9c998
Authorization: Basic admin test
Content-Type: application/json
Cookie: FLOWABLE_REMEMBER_ME=dlU4ZnZxTlA1JTJCc0NTTlZjR2t3aFlnJTNEJTNEOlhJQ0hpeXZWRE1LMENkbjBBSENsZWclM0QlM0Q;

###
# continue planitem
PUT http://localhost:9999/flowable-task/app/rest/cmmn-debugger/breakpoints/e0cf19ff-70f8-11e9-a8b9-b46bfcd9c998/continue
Authorization: Basic admin test
Content-Type: application/json
Cookie: FLOWABLE_REMEMBER_ME=dlU4ZnZxTlA1JTJCc0NTTlZjR2t3aFlnJTNEJTNEOlhJQ0hpeXZWRE1LMENkbjBBSENsZWclM0QlM0Q;

###
# evaluate expression
POST http://localhost:9999/flowable-task/app/rest/cmmn-debugger/evaluate/expression/e0cf19fe-70f8-11e9-a8b9-b46bfcd9c998
Authorization: Basic admin test
Content-Type: text/plain
Cookie: FLOWABLE_REMEMBER_ME=dlU4ZnZxTlA1JTJCc0NTTlZjR2t3aFlnJTNEJTNEOlhJQ0hpeXZWRE1LMENkbjBBSENsZWclM0QlM0Q;

${planItemInstance.getId()}

###
# evaluate script
POST http://localhost:9999/flowable-task/app/rest/cmmn-debugger/evaluate/groovy/e0cf19fe-70f8-11e9-a8b9-b46bfcd9c998
Authorization: Basic admin test
Content-Type: text/plain
Cookie: FLOWABLE_REMEMBER_ME=dlU4ZnZxTlA1JTJCc0NTTlZjR2t3aFlnJTNEJTNEOlhJQ0hpeXZWRE1LMENkbjBBSENsZWclM0QlM0Q;

println('hello world!')

###
# get test process template
GET http://localhost:9999/flowable-task/app/rest/debugger/test/0793b656-6b2a-11e9-9d32-b46bfcd9c998
Authorization: Basic admin test
Content-Type: application/json
Cookie: FLOWABLE_REMEMBER_ME=dlU4ZnZxTlA1JTJCc0NTTlZjR2t3aFlnJTNEJTNEOlhJQ0hpeXZWRE1LMENkbjBBSENsZWclM0QlM0Q;

###
