version: '3.6'
services:
    flowable-rest-app:
        image: flowable/flowable-rest:6.8.1.10
        depends_on:
            - flowable-ui-db
        environment:
            - SERVER_PORT=8080
            - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
            - SPRING_DATASOURCE_URL=jdbc:postgresql://flowable-ui-db:5432/flowable
            - SPRING_DATASOURCE_USERNAME=flowable
            - SPRING_DATASOURCE_PASSWORD=flowable
            - FLOWABLE_COMMON_APP_IDM-ADMIN_USER=admin
            - FLOWABLE_COMMON_APP_IDM-ADMIN_PASSWORD=test
        ports:
            - 8080:8080
        entrypoint: ["./wait-for-something.sh", "flowable-ui-db", "5432", "PostgreSQL", "sh", "/flowable-entrypoint.sh"]
    flowable-ui-db:
        image: postgres:15.2-alpine
        container_name: flowable-ui-postgresql
        volumes:
            - ~/volumes/flowable/ui/postgresql/data/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_PASSWORD=flowable
            - POSTGRES_USER=flowable
            - POSTGRES_DB=flowable
        ports:
            - 5433:5432
        command: postgres