CREATE TABLE ACT_HI_PROCINST (
    ID_ STRING(64) NOT NULL,
    REV_ INT64 DEFAULT (1),
    PROC_INST_ID_ STRING(64) NOT NULL,
    BUSINESS_KEY_ STRING(255),
    PROC_DEF_ID_ STRING(64) NOT NULL,
    START_TIME_ TIMESTAMP NOT NULL,
    END_TIME_ TIMESTAMP,
    DURATION_ INT64,
    START_USER_ID_ STRING(255),
    START_ACT_ID_ STRING(255),
    END_ACT_ID_ STRING(255),
    SUPER_PROCESS_INSTANCE_ID_ STRING(64),
    DELETE_REASON_ STRING(4000),
    TENANT_ID_ STRING(255) DEFAULT (''),
    NAME_ STRING(255),
    CALLBACK_ID_ STRING(255),
    CALLBACK_TYPE_ STRING(255),
    REFERENCE_ID_ STRING(255),
    REFERENCE_TYPE_ STRING(255),
    PROPAGATED_STAGE_INST_ID_ STRING(255),
    BUSINESS_STATUS_ STRING(255),
    DUE_DATE_ TIMESTAMP,
    CLAIM_TIME_ TIMESTAMP,
    CLAIMED_BY_ STRING(255),
    END_USER_ID_ STRING(255),
    STATE_ STRING(255)
) PRIMARY KEY (ID_);

CREATE UNIQUE NULL_FILTERED INDEX ACT_UNIQ_HI_PROC_INST ON ACT_HI_PROCINST (PROC_INST_ID_);

CREATE TABLE ACT_HI_ACTINST (
    ID_ STRING(64) NOT NULL,
    REV_ INT64 DEFAULT (1),
    PROC_DEF_ID_ STRING(64) NOT NULL,
    PROC_INST_ID_ STRING(64) NOT NULL,
    EXECUTION_ID_ STRING(64) NOT NULL,
    ACT_ID_ STRING(255) NOT NULL,
    TASK_ID_ STRING(64),
    CALL_PROC_INST_ID_ STRING(64),
    ACT_NAME_ STRING(255),
    ACT_TYPE_ STRING(255) NOT NULL,
    ASSIGNEE_ STRING(255),
    COMPLETED_BY_ STRING(255),
    START_TIME_ TIMESTAMP NOT NULL,
    END_TIME_ TIMESTAMP,
    TRANSACTION_ORDER_ INT64,
    DURATION_ INT64,
    DELETE_REASON_ STRING(4000),
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_HI_DETAIL (
    ID_ STRING(64) NOT NULL,
    TYPE_ STRING(255) NOT NULL,
    PROC_INST_ID_ STRING(64),
    EXECUTION_ID_ STRING(64),
    TASK_ID_ STRING(64),
    ACT_INST_ID_ STRING(64),
    NAME_ STRING(255) NOT NULL,
    VAR_TYPE_ STRING(64),
    REV_ INT64,
    TIME_ TIMESTAMP NOT NULL,
    BYTEARRAY_ID_ STRING(64),
    DOUBLE_ FLOAT64,
    LONG_ INT64,
    TEXT_ STRING(4000),
    TEXT2_ STRING(4000)
) PRIMARY KEY (ID_);

CREATE TABLE ACT_HI_COMMENT (
    ID_ STRING(64) NOT NULL,
    TYPE_ STRING(255),
    TIME_ TIMESTAMP NOT NULL,
    USER_ID_ STRING(255),
    TASK_ID_ STRING(64),
    PROC_INST_ID_ STRING(64),
    ACTION_ STRING(255),
    MESSAGE_ STRING(4000),
    FULL_MSG_ BYTES(MAX)
) PRIMARY KEY (ID_);

CREATE TABLE ACT_HI_ATTACHMENT (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    USER_ID_ STRING(255),
    NAME_ STRING(255),
    DESCRIPTION_ STRING(4000),
    TYPE_ STRING(255),
    TASK_ID_ STRING(64),
    PROC_INST_ID_ STRING(64),
    URL_ STRING(4000),
    CONTENT_ID_ STRING(64),
    TIME_ TIMESTAMP
) PRIMARY KEY (ID_);

CREATE INDEX ACT_IDX_HI_PRO_INST_END ON ACT_HI_PROCINST(END_TIME_);
CREATE INDEX ACT_IDX_HI_PRO_I_BUSKEY ON ACT_HI_PROCINST(BUSINESS_KEY_);
CREATE INDEX ACT_IDX_HI_PRO_SUPER_PROCINST ON ACT_HI_PROCINST(SUPER_PROCESS_INSTANCE_ID_);
CREATE INDEX ACT_IDX_HI_ACT_INST_START ON ACT_HI_ACTINST(START_TIME_);
CREATE INDEX ACT_IDX_HI_ACT_INST_END ON ACT_HI_ACTINST(END_TIME_);
CREATE INDEX ACT_IDX_HI_DETAIL_PROC_INST ON ACT_HI_DETAIL(PROC_INST_ID_);
CREATE INDEX ACT_IDX_HI_DETAIL_ACT_INST ON ACT_HI_DETAIL(ACT_INST_ID_);
CREATE INDEX ACT_IDX_HI_DETAIL_TIME ON ACT_HI_DETAIL(TIME_);
CREATE INDEX ACT_IDX_HI_DETAIL_NAME ON ACT_HI_DETAIL(NAME_);
CREATE INDEX ACT_IDX_HI_DETAIL_TASK_ID ON ACT_HI_DETAIL(TASK_ID_);
CREATE INDEX ACT_IDX_HI_PROCVAR_PROC_INST ON ACT_HI_VARINST(PROC_INST_ID_);
CREATE INDEX ACT_IDX_HI_PROCVAR_TASK_ID ON ACT_HI_VARINST(TASK_ID_);
CREATE INDEX ACT_IDX_HI_PROCVAR_EXE ON ACT_HI_VARINST(EXECUTION_ID_);
CREATE INDEX ACT_IDX_HI_ACT_INST_PROCINST ON ACT_HI_ACTINST(PROC_INST_ID_, ACT_ID_);
CREATE INDEX ACT_IDX_HI_ACT_INST_EXEC ON ACT_HI_ACTINST(EXECUTION_ID_, ACT_ID_);
CREATE INDEX ACT_IDX_HI_IDENT_LNK_TASK ON ACT_HI_IDENTITYLINK(TASK_ID_);
CREATE INDEX ACT_IDX_HI_IDENT_LNK_PROCINST ON ACT_HI_IDENTITYLINK(PROC_INST_ID_);
CREATE INDEX ACT_IDX_HI_TASK_INST_PROCINST ON ACT_HI_TASKINST(PROC_INST_ID_);
