ALTER TABLE ACT_CMMN_RU_CASE_INST ADD DUE_DATE_ datetime(3) NULL, ADD CLAIM_TIME_ datetime(3) NULL, ADD CLAIMED_BY_ VARCHAR(255) NULL;

ALTER TABLE ACT_CMMN_HI_CASE_INST ADD DUE_DATE_ datetime(3) NULL, ADD CLAIM_TIME_ datetime(3) NULL, ADD CLAIMED_BY_ VARCHAR(255) NULL;

update ACT_GE_PROPERTY set VALUE_ = '8.1.0.1' where NAME_ = 'cmmn.schema.version';
