ALTER TABLE ACT_CMMN_DEPLOYMENT ALTER COLUMN NAME_ nvarchar(255);

ALTER TABLE ACT_CMMN_DEPLOYMENT_RESOURCE ALTER COLUMN NAME_ nvarchar(255);

ALTER TABLE ACT_CMMN_CASEDEF ALTER COLUMN NAME_ nvarchar(255);

ALTER TABLE ACT_CMMN_CASEDEF ALTER COLUMN RESOURCE_NAME_ nvarchar(255);

ALTER TABLE ACT_CMMN_CASEDEF ALTER COLUMN DGRM_RESOURCE_NAME_ nvarchar(255);

ALTER TABLE ACT_CMMN_RU_CASE_INST ALTER COLUMN NAME_ nvarchar(255);

ALTER TABLE ACT_CMMN_RU_CASE_INST ALTER COLUMN BUSINESS_KEY_ nvarchar(255);

ALTER TABLE ACT_CMMN_RU_CASE_INST ALTER COLUMN BUSINESS_STATUS_ nvarchar(255);

ALTER TABLE ACT_CMMN_RU_MIL_INST ALTER COLUMN NAME_ nvarchar(255);

ALTER TABLE ACT_CMMN_RU_PLAN_ITEM_INST ALTER COLUMN NAME_ nvarchar(255);

ALTER TABLE ACT_CMMN_HI_MIL_INST ALTER COLUMN NAME_ nvarchar(255);

ALTER TABLE ACT_CMMN_HI_PLAN_ITEM_INST ALTER COLUMN NAME_ nvarchar(255);

ALTER TABLE ACT_CMMN_HI_CASE_INST ALTER COLUMN NAME_ nvarchar(255);

ALTER TABLE ACT_CMMN_HI_CASE_INST ALTER COLUMN BUSINESS_KEY_ nvarchar(255);

ALTER TABLE ACT_CMMN_HI_CASE_INST ALTER COLUMN BUSINESS_STATUS_ nvarchar(255);

ALTER TABLE ACT_CMMN_CASEDEF ALTER COLUMN DESCRIPTION_ nvarchar(4000);
