ALTER TABLE ACT_CMMN_RU_CASE_INST ADD DUE_DATE_ TIMESTAMP;
ALTER TABLE ACT_CMMN_RU_CASE_INST ADD CLAIM_TIME_ TIMESTAMP;
ALTER TABLE ACT_CMMN_RU_CASE_INST ADD CLAIMED_BY_ VARCHAR(255);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ACT_CMMN_RU_CASE_INST');

ALTER TABLE ACT_CMMN_HI_CASE_INST ADD DUE_DATE_ TIMESTAMP;
ALTER TABLE ACT_CMMN_HI_CASE_INST ADD CLAIM_TIME_ TIMESTAMP;
ALTER TABLE ACT_CMMN_HI_CASE_INST ADD CLAIMED_BY_ VARCHAR(255);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ACT_CMMN_HI_CASE_INST');

update ACT_GE_PROPERTY set VALUE_ = '8.1.0.1' where NAME_ = 'cmmn.schema.version';
