ALTER TABLE ACT_CMMN_RU_CASE_INST ADD DUE_DATE_ timestamp;
ALTER TABLE ACT_CMMN_RU_CASE_INST ADD CLAIM_TIME_ timestamp;
ALTER TABLE ACT_CMMN_RU_CASE_INST ADD CLAIMED_BY_ varchar(255);

ALTER TABLE ACT_CMMN_HI_CASE_INST ADD DUE_DATE_ timestamp;
ALTER TABLE ACT_CMMN_HI_CASE_INST ADD CLAIM_TIME_ timestamp;
ALTER TABLE ACT_CMMN_HI_CASE_INST ADD CLAIMED_BY_ varchar(255);

update ACT_GE_PROPERTY set VALUE_ = '8.1.0.1' where NAME_ = 'cmmn.schema.version';
