{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ include "flowable.template" . }}
  labels:
    {{ include "flowable.defaultlabels" . }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ include "flowable.template" . }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ include "flowable.template" . }}
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: {{ .Values.database.name }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.database.password }}
        - name: POSTGRES_USER
          value: {{ .Values.database.username }}
        image: {{ .Values.postgres.image }}
        name: {{ .Release.Name }}-{{ include "flowable.template" . }}
        resources:
{{ toYaml .Values.postgres.resources | indent 10 }}
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 5
          timeoutSeconds: 1
        ports:
        - containerPort: 5432
          name: "jdbc"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: {{ .Release.Name }}-{{ include "flowable.template" . }}
          subPath: data
      restartPolicy: Always
      volumes:
      - name: {{ .Release.Name }}-{{ include "flowable.template" . }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-{{ include "flowable.template" . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: {{ .Release.Name }}-{{ include "flowable.template" . }}
  name: {{ .Release.Name }}-{{ include "flowable.template" . }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.postgres.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.postgres.service.name }}
spec:
  selector:
    app: {{ .Release.Name }}-{{ include "flowable.template" . }}
  ports:
  - port: 5432
{{- end }}