apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowable-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flowable-admin
  template:
    metadata:
      labels:
        app: flowable-admin
    spec:
      containers:
        - name: flowable-admin
          image: flowable/flowable-admin:latest
          ports:
            - containerPort: 9988
          envFrom:
            - configMapRef:
                name: flowable-admin-config
          # resources:
          #   requests:
          #     memory: 400Mi
          #   limits:
          #     memory: 600Mi
          #     cpu: 500m
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: flowable-admin
spec:
  type: NodePort
  selector:
    app: flowable-admin
  ports:
    - name: http
      protocol: TCP
      port: 9988
      targetPort: 9988
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flowable-admin-config
data:
  # SPRING_DATASOURCE_USERNAME: flowable
  # SPRING_DATASOURCE_PASSWORD: flowable
  FLOWABLE_COMMON_APP_IDM-URL: http://flowable-idm:8080/flowable-idm
  FLOWABLE_COMMON_APP_IDM-REDIRECT-URL: http://localhost:8080/flowable-idm
  FLOWABLE_COMMON_APP_IDM-ADMIN_USER: admin
  FLOWABLE_COMMON_APP_IDM-ADMIN_PASSWORD: test
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_SERVER-ADDRESS: http://flowable-task
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_PORT: "9999"
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_CONTEXT-ROOT: flowable-task
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_REST-ROOT: process-api
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_SERVER-ADDRESS: http://flowable-task
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_PORT: "9999"
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_CONTEXT-ROOT: flowable-task
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_REST-ROOT: cmmn-api
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_SERVER-ADDRESS: http://flowable-task
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_PORT: "9999"
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_CONTEXT-ROOT: flowable-task
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_REST-ROOT: dmn-api
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_SERVER-ADDRESS: http://flowable-task
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_PORT: "9999"
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_CONTEXT-ROOT: flowable-task
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_REST-ROOT: form-api
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_SERVER-ADDRESS: http://flowable-task
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_PORT: "9999"
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_CONTEXT-ROOT: flowable-task
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_REST-ROOT: content-api
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_SERVER-ADDRESS: http://flowable-task
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_PORT: "9999"
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_CONTEXT-ROOT: flowable-task
  FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_REST-ROOT: app-api

  