apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowable-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flowable-task
  template:
    metadata:
      labels:
        app: flowable-task
    spec:
      containers:
        - name: flowable-task
          image: flowable/flowable-task:latest
          ports:
            - containerPort: 9999
          envFrom:
            - configMapRef:
                name: flowable-task-config
          # resources:
          #   requests:
          #     memory: 400Mi
          #   limits:
          #     memory: 600Mi
          #     cpu: 500m
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: flowable-task
spec:
  type: NodePort
  selector:
    app: flowable-task
  ports:
    - name: http
      protocol: TCP
      port: 9999
      targetPort: 9999
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flowable-task-config
data:
  # SPRING_DATASOURCE_USERNAME: flowable
  # SPRING_DATASOURCE_PASSWORD: flowable
  FLOWABLE_COMMON_APP_IDM-URL: http://flowable-idm:8080/flowable-idm
  FLOWABLE_COMMON_APP_IDM-REDIRECT-URL: http://localhost:8080/flowable-idm
  FLOWABLE_COMMON_APP_IDM-ADMIN_USER: admin
  FLOWABLE_COMMON_APP_IDM-ADMIN_PASSWORD: test
  