apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowable-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flowable-rest
  template:
    metadata:
      labels:
        app: flowable-rest
    spec:
      containers:
        - name: flowable-rest
          image: flowable/flowable-rest:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: flowable-rest-config
          resources:
            requests:
              memory: 400Mi
            limits:
              memory: 600Mi
              cpu: 500m
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: flowable-rest
spec:
  type: NodePort
  selector:
    app: flowable-rest
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flowable-rest-config