apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowable-modeler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flowable-modeler
  template:
    metadata:
      labels:
        app: flowable-modeler
    spec:
      containers:
        - name: flowable-task
          image: flowable/flowable-modeler:latest
          ports:
            - containerPort: 8888
          envFrom:
            - configMapRef:
                name: flowable-modeler-config
          # resources:
          #   requests:
          #     memory: 400Mi
          #   limits:
          #     memory: 600Mi
          #     cpu: 500m
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: flowable-modeler
spec:
  type: NodePort
  selector:
    app: flowable-modeler
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: 8888
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flowable-modeler-config
data:
  # SPRING_DATASOURCE_USERNAME: flowable
  # SPRING_DATASOURCE_PASSWORD: flowable
  FLOWABLE_COMMON_APP_IDM-URL: http://flowable-idm:8080/flowable-idm
  FLOWABLE_COMMON_APP_IDM-REDIRECT-URL: http://localhost:8080/flowable-idm
  FLOWABLE_COMMON_APP_IDM-ADMIN_USER: admin
  FLOWABLE_COMMON_APP_IDM-ADMIN_PASSWORD: test
  FLOWABLE_MODELER_APP_DEPLOYMENT-API-URL: http://flowable-task:9999/flowable-task/app-api