CREATE TABLE ACT_DMN_DEPLOYMENT (
    ID_ STRING(255) NOT NULL,
    NAME_ STRING(255),
    CATEGORY_ STRING(255),
    DEPLOY_TIME_ TIMESTAMP,
    TENANT_ID_ STRING(255),
    PARENT_DEPLOYMENT_ID_ STRING(255)
) PRIMARY KEY (ID_);

CREATE TABLE ACT_DMN_DEPLOYMENT_RESOURCE (
    ID_ STRING(255) NOT NULL,
    NAME_ STRING(255),
    DEPLOYMENT_ID_ STRING(255),
    RESOURCE_BYTES_ BYTES(MAX)
) PRIMARY KEY (ID_);

CREATE TABLE ACT_DMN_DECISION (
    ID_ STRING(255) NOT NULL,
    NAME_ STRING(255),
    VERSION_ INT64,
    KEY_ STRING(255),
    CATEGORY_ STRING(255),
    DECISION_TYPE_ STRING(255),
    DEPLOYMENT_ID_ STRING(255),
    TENANT_ID_ STRING(255),
    RESOURCE_NAME_ STRING(255),
    DESCRIPTION_ STRING(255)
) PRIMARY KEY (ID_);

CREATE TABLE ACT_DMN_HI_DECISION_EXECUTION (
    ID_ STRING(255) NOT NULL,
    DECISION_DEFINITION_ID_ STRING(255),
    DEPLOYMENT_ID_ STRING(255),
    START_TIME_ TIMESTAMP,
    END_TIME_ TIMESTAMP,
    INSTANCE_ID_ STRING(255),
    EXECUTION_ID_ STRING(255),
    ACTIVITY_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    FAILED_ BOOL DEFAULT (FALSE),
    TENANT_ID_ STRING(255),
    EXECUTION_JSON_ STRING(MAX)
) PRIMARY KEY (ID_);

ALTER TABLE ACT_DMN_DEPLOYMENT_RESOURCE
    ADD CONSTRAINT ACT_FK_DMN_RSRC_DPL
    FOREIGN KEY (DEPLOYMENT_ID_)
    REFERENCES ACT_DMN_DEPLOYMENT (ID_);

CREATE INDEX ACT_IDX_DMN_RSRC_DPL ON ACT_DMN_DEPLOYMENT_RESOURCE (DEPLOYMENT_ID_);

CREATE UNIQUE NULL_FILTERED INDEX ACT_IDX_DMN_DEC_UNIQ ON ACT_DMN_DECISION(KEY_, VERSION_, TENANT_ID_);

CREATE INDEX ACT_IDX_DMN_INSTANCE_ID ON ACT_DMN_HI_DECISION_EXECUTION(INSTANCE_ID_);

INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_) VALUES ('dmn.schema.version', '8.1.0.1', 1);
