CREATE TABLE FLW_EVENT_DEPLOYMENT (
    ID_ STRING(255) NOT NULL,
    NAME_ STRING(255),
    CATEGORY_ STRING(255),
    DEPLOY_TIME_ TIMESTAMP,
    TENANT_ID_ STRING(255),
    PARENT_DEPLOYMENT_ID_ STRING(255)
) PRIMARY KEY (ID_);

CREATE TABLE FLW_EVENT_RESOURCE (
    ID_ STRING(255) NOT NULL,
    NAME_ STRING(255),
    DEPLOYMENT_ID_ STRING(255),
    RESOURCE_BYTES_ BYTES(MAX)
) PRIMARY KEY (ID_);

CREATE TABLE FLW_EVENT_DEFINITION (
    ID_ STRING(255) NOT NULL,
    NAME_ STRING(255),
    VERSION_ INT64,
    KEY_ STRING(255),
    CATEGORY_ STRING(255),
    DEPLOYMENT_ID_ STRING(255),
    TENANT_ID_ STRING(255),
    RESOURCE_NAME_ STRING(255),
    DESCRIPTION_ STRING(255)
) PRIMARY KEY (ID_);

ALTER TABLE FLW_EVENT_RESOURCE
    ADD CONSTRAINT FLW_FK_EVENT_RSRC_DPL
    FOREIGN KEY (DEPLOYMENT_ID_)
    REFERENCES FLW_EVENT_DEPLOYMENT (ID_);

CREATE INDEX FLW_IDX_EVENT_RSRC_DPL ON FLW_EVENT_RESOURCE (DEPLOYMENT_ID_);

CREATE UNIQUE NULL_FILTERED INDEX ACT_IDX_EVENT_DEF_UNIQ ON FLW_EVENT_DEFINITION(KEY_, VERSION_, TENANT_ID_);

CREATE TABLE FLW_CHANNEL_DEFINITION (
    ID_ STRING(255) NOT NULL,
    NAME_ STRING(255),
    VERSION_ INT64,
    KEY_ STRING(255),
    CATEGORY_ STRING(255),
    TYPE_ STRING(255),
    IMPLEMENTATION_ STRING(255),
    DEPLOYMENT_ID_ STRING(255),
    CREATE_TIME_ TIMESTAMP,
    TENANT_ID_ STRING(255),
    RESOURCE_NAME_ STRING(255),
    DESCRIPTION_ STRING(255)
) PRIMARY KEY (ID_);

CREATE UNIQUE NULL_FILTERED INDEX ACT_IDX_CHANNEL_DEF_UNIQ ON FLW_CHANNEL_DEFINITION(KEY_, VERSION_, TENANT_ID_);

INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_) VALUES ('eventregistry.schema.version', '8.1.0.1', 1);
