CREATE TABLE ACT_ID_PROPERTY (
    NAME_ STRING(64) NOT NULL,
    VALUE_ STRING(300),
    REV_ INT64
) PRIMARY KEY (NAME_);

INSERT INTO ACT_ID_PROPERTY (NAME_, VALUE_, REV_) VALUES ('schema.version', '8.1.0.1', 1);

CREATE TABLE ACT_ID_BYTEARRAY (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    NAME_ STRING(255),
    BYTES_ BYTES(MAX)
) PRIMARY KEY (ID_);

CREATE TABLE ACT_ID_GROUP (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    NAME_ STRING(255),
    TYPE_ STRING(255)
) PRIMARY KEY (ID_);

CREATE TABLE ACT_ID_MEMBERSHIP (
    USER_ID_ STRING(64) NOT NULL,
    GROUP_ID_ STRING(64) NOT NULL
) PRIMARY KEY (USER_ID_, GROUP_ID_);

CREATE TABLE ACT_ID_USER (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    FIRST_ STRING(255),
    LAST_ STRING(255),
    DISPLAY_NAME_ STRING(255),
    EMAIL_ STRING(255),
    PWD_ STRING(255),
    PICTURE_ID_ STRING(64),
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_ID_INFO (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    USER_ID_ STRING(64),
    TYPE_ STRING(64),
    KEY_ STRING(255),
    VALUE_ STRING(255),
    PASSWORD_ BYTES(MAX),
    PARENT_ID_ STRING(255)
) PRIMARY KEY (ID_);

CREATE TABLE ACT_ID_TOKEN (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    TOKEN_VALUE_ STRING(255),
    TOKEN_DATE_ TIMESTAMP,
    IP_ADDRESS_ STRING(255),
    USER_AGENT_ STRING(255),
    USER_ID_ STRING(255),
    TOKEN_DATA_ STRING(2000)
) PRIMARY KEY (ID_);

CREATE TABLE ACT_ID_PRIV (
    ID_ STRING(64) NOT NULL,
    NAME_ STRING(255) NOT NULL
) PRIMARY KEY (ID_);

CREATE TABLE ACT_ID_PRIV_MAPPING (
    ID_ STRING(64) NOT NULL,
    PRIV_ID_ STRING(64) NOT NULL,
    USER_ID_ STRING(255),
    GROUP_ID_ STRING(255)
) PRIMARY KEY (ID_);

CREATE INDEX ACT_IDX_MEMB_GROUP ON ACT_ID_MEMBERSHIP(GROUP_ID_);
ALTER TABLE ACT_ID_MEMBERSHIP
    ADD CONSTRAINT ACT_FK_MEMB_GROUP
    FOREIGN KEY (GROUP_ID_)
    REFERENCES ACT_ID_GROUP (ID_);

CREATE INDEX ACT_IDX_MEMB_USER ON ACT_ID_MEMBERSHIP(USER_ID_);
ALTER TABLE ACT_ID_MEMBERSHIP
    ADD CONSTRAINT ACT_FK_MEMB_USER
    FOREIGN KEY (USER_ID_)
    REFERENCES ACT_ID_USER (ID_);

CREATE INDEX ACT_IDX_PRIV_MAPPING ON ACT_ID_PRIV_MAPPING(PRIV_ID_);
ALTER TABLE ACT_ID_PRIV_MAPPING
    ADD CONSTRAINT ACT_FK_PRIV_MAPPING
    FOREIGN KEY (PRIV_ID_)
    REFERENCES ACT_ID_PRIV (ID_);

CREATE INDEX ACT_IDX_PRIV_USER ON ACT_ID_PRIV_MAPPING(USER_ID_);
CREATE INDEX ACT_IDX_PRIV_GROUP ON ACT_ID_PRIV_MAPPING(GROUP_ID_);

CREATE UNIQUE NULL_FILTERED INDEX ACT_UNIQ_PRIV_NAME ON ACT_ID_PRIV(NAME_);
