ALTER TABLE ACT_RU_EXECUTION ADD DUE_DATE_ TIMESTAMP;
ALTER TABLE ACT_RU_EXECUTION ADD CLAIM_TIME_ TIMESTAMP;
ALTER TABLE ACT_RU_EXECUTION ADD CLAIMED_BY_ VARCHAR(255);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ACT_RU_EXECUTION');

update ACT_GE_PROPERTY set VALUE_ = '8.1.0.1' where NAME_ = 'schema.version';
