create index ACT_IDX_HI_PRO_I_SUP_INST on ACT_HI_PROCINST(SUPER_PROCESS_INSTANCE_ID_);
create index ACT_IDX_HI_PRO_I_DEF_ID on ACT_HI_PROCINST(PROC_DEF_ID_);
create index ACT_IDX_HI_ACT_I_DEF_ID on ACT_HI_ACTINST(PROC_DEF_ID_);
create index ACT_IDX_HI_PRO_TENANT_ID on ACT_HI_PROCINST(TENANT_ID_);
create index ACT_IDX_HI_TASK_TENANT_ID on ACT_HI_TASKINST(TENANT_ID_);
