ALTER TABLE ACT_HI_PROCINST ADD DUE_DATE_ TIMESTAMP;
ALTER TABLE ACT_HI_PROCINST ADD CLAIM_TIME_ TIMESTAMP;
ALTER TABLE ACT_HI_PROCINST ADD CLAIMED_BY_ VARCHAR(255);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ACT_HI_PROCINST');
