ALTER TABLE ACT_HI_PROCINST ADD DUE_DATE_ datetime;
ALTER TABLE ACT_HI_PROCINST ADD IN_PROGRESS_DUE_DATE_ datetime;
ALTER TABLE ACT_HI_PROCINST ADD IN_PROGRESS_TIME_ datetime;
ALTER TABLE ACT_HI_PROCINST ADD IN_PROGRESS_STARTED_BY_ nvarchar(255);
ALTER TABLE ACT_HI_PROCINST ADD CLAIM_TIME_ datetime;
ALTER TABLE ACT_HI_PROCINST ADD CLAIMED_BY_ nvarchar(255);

update ACT_GE_PROPERTY set VALUE_ = '8.0.0.1' where NAME_ = 'history.schema.version';
