ALTER TABLE ACT_RU_EXECUTION ADD DUE_DATE_ datetime(3) NULL, ADD CLAIM_TIME_ datetime(3) NULL, ADD CLAIMED_BY_ VARCHAR(255) NULL;

update ACT_GE_PROPERTY set VALUE_ = '8.1.0.1' where NAME_ = 'schema.version';
