alter table ACT_HI_TASKINST
    add CATEGORY_ NVARCHAR2(255);
    
alter table ACT_HI_TASKINST
  add FORM_KEY_ NVARCHAR2(255);

alter table ACT_HI_TASKINST add CLAIM_TIME_ TIMESTAMP(6);
    
alter table ACT_HI_VARINST
    add LAST_UPDATED_TIME_ TIMESTAMP(6);

alter table ACT_HI_ACTINST modify ASSIGNEE_ NVARCHAR2(255);
