alter table ACT_RU_ENTITYLINK add column ROOT_SCOPE_ID_ NVARCHAR2(255);
alter table ACT_RU_ENTITYLINK add column ROOT_SCOPE_TYPE_ NVARCHAR2(255);
alter table ACT_RU_ENTITYLINK add column ROOT_SCOPE_DEFINITION_ID_ NVARCHAR2(255);