version: '2'
services:
    flowable-rest-app:
        image: flowable/flowable-rest
        depends_on:
            - flowable-rest-db
        environment:
            - spring.datasource.driver-class-name=org.postgresql.Driver
            - spring.datasource.url=jdbc:postgresql://flowable-rest-db:5432/flowable
            - spring.datasource.username=flowable
            - spring.datasource.password=flowable
            - flowable.rest.app.admin.user-id=rest-admin
            - flowable.rest.app.admin.password=test
            - flowable.rest.app.admin.first-name=Rest
            - flowable.rest.app.admin.last-name=Admin
        ports:
            - 8080:8080
        depends_on:
            - flowable-rest-db
        entrypoint: ["./wait-for-something.sh", "flowable-rest-db", "5432", "PostgreSQL", "java", "-jar", "flowable-rest.jar", "-httpPort=8080", "-httpProtocol=org.apache.coyote.http11.Http11NioProtocol"]
    flowable-rest-db:
        extends:
            file: postgres.yml
            service: flowable-rest-postgres
