ALTER TABLE ACT_ID_MEMBERSHIP DROP CONSTRAINT ACT_FK_MEMB_GROUP;
ALTER TABLE ACT_ID_MEMBERSHIP DROP CONSTRAINT ACT_FK_MEMB_USER;
ALTER TABLE ACT_ID_PRIV_MAPPING DROP CONSTRAINT ACT_FK_PRIV_MAPPING;

DROP INDEX IF EXISTS ACT_IDX_MEMB_GROUP;
DROP INDEX IF EXISTS ACT_IDX_MEMB_USER;
DROP INDEX IF EXISTS ACT_IDX_PRIV_MAPPING;
DROP INDEX IF EXISTS ACT_IDX_PRIV_USER;
DROP INDEX IF EXISTS ACT_IDX_PRIV_GROUP;
DROP INDEX IF EXISTS ACT_UNIQ_PRIV_NAME;

DROP TABLE IF EXISTS ACT_ID_PRIV_MAPPING;
DROP TABLE IF EXISTS ACT_ID_PRIV;
DROP TABLE IF EXISTS ACT_ID_TOKEN;
DROP TABLE IF EXISTS ACT_ID_MEMBERSHIP;
DROP TABLE IF EXISTS ACT_ID_USER;
DROP TABLE IF EXISTS ACT_ID_GROUP;
DROP TABLE IF EXISTS ACT_ID_INFO;
DROP TABLE IF EXISTS ACT_ID_BYTEARRAY;
DROP TABLE IF EXISTS ACT_ID_PROPERTY;
