
=== 部署


*当使用tomcat时, 请参考在<<restTomcat,Tomcat>>中的用法。*

==== 部署列表

----
GET form-repository/deployments
----

.URL查询参数
[options="header"]
|===============
|参数名称|是否必须|参数类型|描述

|name|否|字符串|仅返回根据名称查询返回的部署结果集.

|name模糊查询|否|字符串|仅返回根据名称模糊匹配的部署结果集.

|category|否|字符串|仅返回符合类别的部署结果集.

|不等于category|否|字符串|仅返回不等于该类别的其他部署结果集.

|tenantId|否|字符串|仅返回给符合租户ID的部署结果集.

|模糊匹配tenantId值|否|字符串|仅返回模糊匹配到租户ID值的部署结果集.

|withoutTenantId|否|布尔|如果为 true 则仅返回未设置tenantId的部署。如果为 false 则忽略参数租户ID。

|sort|否|'id' (默认), '名称', '部署时间' or '租户ID'|要排序的属性要与 'order' 一起使用.

|普通的分页和排序可以用这个URL.

|===============


.REST 响应编码
[options="header"]
|===============
|响应编码|描述
|200|表示请求成功.

|===============


*成功响应正文:*

[source,json,linenums]
----
{
  "data": [
    {
      "id": "10",
      "name": "flowable-form-examples",
      "deploymentTime": "2010-10-13T14:54:26.750+02:00",
      "category": "examples",
      "url": "http://localhost:8081/form-api/form-repository/deployments/10",
      "tenantId": null
    }
  ],
  "total": 1,
  "start": 0,
  "sort": "id",
  "order": "asc",
  "size": 1
}
----



==== 获取单个部署

----
GET form-repository/deployments/{deploymentId}
----

.获取单个部署信息 - 请求参数
[options="header"]
|===============
|参数名称|是否必须|值类型|描述

|部署ID|是|字符串|根据部署ID获取部署信息.

|===============



.获取部署信息 - 响应编码
[options="header"]
|===============
|响应编码|描述

|200|表示该部署信息已经找到并且返回.

|404|表示请求的部署信息未找到.

|===============


*成功响应体:*

[source,json,linenums]
----
{
  "id": "10",
  "name": "flowable-form-examples",
  "deploymentTime": "2010-10-13T14:54:26.750+02:00",
  "category": "examples",
  "url": "http://localhost:8081/form-api/form-repository/deployments/10",
  "tenantId" : null
}
----



==== 创建部署信息

----
POST form-repository/deployments
----


*请求正文:*


请求正文应包含multipart / form-data类型的数据。 请求中应该只有一个文件，任何其他文件都将被忽略。 部署名称是传入的文件字段的名称。


可以在名称为tenantId的请求正文中传递附加参数（表单字段）。 此字段的值将用作完成此部署的租户的标识符。


.创建新的部署信息 - 响应编码

[options="header"]
|===============
|响应编码|描述

|201|表示已经部署成功.

|400|表示请求正文中不存在任何内容，或者部署不支持内容mime-type。 状态描述包含其他信息。

|===============


*成功响应正文:*


[source,json,linenums]
----
{
  "id": "10",
  "name": "simple.form",
  "deploymentTime": "2010-10-13T14:54:26.750+02:00",
  "category": null,
  "url": "http://localhost:8081/form-api/form-repository/deployments/10",
  "tenantId" : "myTenant"
}
----


==== 删除部署信息

----
DELETE form-repository/deployments/{deploymentId}
----

.删除一个部署信息 - 传输参数
[options="header"]
|===============
|参数|是否必须|值类型|描述
|部署ID|是|字符串|要删除的部署的标识符。

|===============


.删除某个部署 - 响应编码
[options="header"]
|===============
|响应编码|描述
|204|表示已找到部署并已删除。 响应体是空的。

|404|表示未找到请求的部署。

|===============



==== 获取部署资源内容

----
GET form-repository/deployments/{deploymentId}/resourcedata/{resourceId}
----

.获取部署资源内容 - 请求参数
[options="header"]
|===============
|参数|是否必须|值类型|描述

|部署ID|是|字符串|请求的资源所属的部署标识符。

|资源ID|必须|字符串|获取数据的资源的标识符。 *确保对resourceId进行URL编码，以防它包含正斜杠。 举个例子, 比如 'forms%2Fmy-form.form' 代替 'forms/my-form.form'.*

|===============



.获取部署资源内容 - 响应编码

[options="header"]
|===============
|响应编码|描述
|200|表示已找到部署和资源，并且已返回资源数据。

|404|表示未找到请求的部署，或者部署中不存在具有给定ID的资源。 状态描述包含其他信息。

|===============


*成功响应正文:*


响应正文将包含所请求资源的二进制资源内容。 响应内容类型将与资源'mimeType'属性中返回的类型相同。 此外，还设置了内容处置标题，允许浏览器下载文件而不是显示文件。

=== 表单定义


==== 表单定义列表

----
GET form-repository/form-definitions
----

.表单定义列表 - 请求参数
[options="header"]
|===============
|参数|是否必须|参数类型|描述
|version|否|整型|仅返回给定版本定义的表单.

|name|否|字符串|仅返回给定名称的定义的表单。

|根据name模糊匹配|否|字符串|仅返会根据名称模糊匹配到的定义表单

|key|否|字符串|仅返回具有给定键的表单定义。

|模糊匹配key|否|字符串|仅返回模糊匹配给定键的表单定义.

|resourceName|否|字符串|仅返回具有给定资源名称的表单定义

|模糊匹配resourceName|否|字符串|仅返回具有模糊匹配资源名称的表单定义

|category|否|字符串|仅返回给定类别的表单定义。

|模糊匹配category|否|字符串|仅返回模糊匹配给定类别的表单定义。

|不等于category|否|字符串|仅返回非给定类别的表单定义。

|deploymentId|否|字符串|仅返回作为具有给定标识符的部署的一部分的表单定义。

|latest|否|布尔|仅返回最新的表单定义版本。 只能与'key'和'keyLike'参数一起使用，使用任何其他参数将导致400响应。

|sort|否|'name' (default), 'id', 'key', 'category', 'deploymentId' 和 'version'|要排序的属性，与“order”一起使用。

|一般 <<restPagingAndSort,分页和排序请求参数>>可以用在这个请求.

|===============


.表单定义列表 - 响应编码

[options="header"]
|===============
|响应编码|描述
|200|表示请求成功，并返回表单定义

|400|表示参数以错误的格式传递，或者“latest”与“key”和“keyLike”以外的其他参数一起使用。 状态消息包含其他信息。

|===============



*成功响应正文:*

[source,json,linenums]
----
{
  "data": [
    {
      "id" : "818e4703-f1d2-11e6-8549-acde48001122",
      "url" : "http://localhost:8182/form-repository/form-definitions/simpleForm",
      "version" : 1,
      "key" : "simpleForm",
      "category" : "Examples",
      "deploymentId" : "818e4703-f1d2-11e6-8549-acde48001121",
      "parentDeploymentId" : "2",
      "name" : "The Simple Form",
      "description" : "This is a form for testing purposes",
    }
  ],
  "total": 1,
  "start": 0,
  "sort": "name",
  "order": "asc",
  "size": 1
}
----


==== 获取定义的表单


----
GET repository/form-definitions/{formDefinitionId}
----


.获取表单 - 请求参数
[options="header"]
|===============
|参数|是否必须|值类型|描述
|formDefinitionId|是|字符串|要获取的流程定义的标识符。

|===============


.获取定义的表单 - 响应编码
[options="header"]
|===============
|Response code|Description
|响应编码|描述
|200|表示已找到并返回表单定义。

|404|表示找不到请求的表单定义。

|===============


*成功返回例子:*

[source,json,linenums]
----
{
  "id" : "818e4703-f1d2-11e6-8549-acde48001122",
  "url" : "http://localhost:8182/form-repository/form-definitions/simpleForm",
  "version" : 1,
  "key" : "simpleForm",
  "category" : "Examples",
  "deploymentId" : "818e4703-f1d2-11e6-8549-acde48001121",
  "parentDeploymentId" : "2",
  "name" : "The Simple Form",
  "description" : "This is a form for testing purposes",
}
----


==== 获取表单定义资源内容

----
GET repository/form-definitions/{formDefinitionId}/resourcedata
----

.获取表单定义资源内容 - 请求参数
[options="header"]
|===============
|参数名|是否必须|参数类型|描述

|formDefinitionId|是|字符串|用于获取资源数据的表单定义的标识符。

|===============

*返回值:*

返回的编码和响应体与+GET form-repository/deployment/{deploymentId}/resourcedata/{resourceId}+ 一样.


==== 获取定义表单的表单模型

----
GET form-repository/form-definitions/{formDefinitionId}/model
----

.获取定义表单的表单模型 - 请求参数
[options="header"]
|===============
|请求参数|是否必须|参数类型|描述

|formDefinitionId|是|字符串|获取模型的表单定义的标识符。
|===============


.获取定义表单的表单模型 - 响应编码
[options="header"]
|===============
|响应编码|描述
|200|表示找到了表单定义并返回了模型.

|404|表示找不到请求的表单定义。

|===============


*响应正文:*
响应主体是+ org.flowable.form.model.FormModel +的JSON表示，并包含完整的表单定义模型。

=== 表单实例


==== 获取表单实例


----
GET form/form-instances/{formInstanceId}
----

.获取表单实例 - 请求参数
[options="header"]
|===============
|请求参数|是否必须|参数类型|描述

|formInstanceId|是|字符串|要获取的表单实例的标识符。

|===============


.获取表单实例 - 响应编码
[options="header"]
|===============
|响应编码|描述
|200|表示找到并返回了表单实例.

|404|表示找不到请求的表单实例。

|===============


*成功响应正文:*
[source,json,linenums]
----
{
   "id":"48b9ac82-f1d3-11e6-8549-acde48001122",
   "url":"http://localhost:8182/form/form-instances/48b9ac82-f1d3-11e6-8549-acde48001122",
   "formDefinitionId":"818e4703-f1d2-11e6-8549-acde48001122",
   "taskId":"88",
   "processInstanceId":"66",
   "processDefinitionId":"oneTaskProcess:1:158",
   "submittedDate":"2013-04-17T10:17:43.902+0000",
   "submittedBy":"testUser",
   "formValuesId":"818e4703-f1d2-11e6-8549-acde48001110",
   "tenantId": null
}
----


==== 存储表单实例

----
POST form/form-instances
----

*请求正文（以流程定义ID开头）:*

[source,json,linenums]
----
{
   "formDefinitionId":"818e4703-f1d2-11e6-8549-acde48001122",
   "taskId":"88",
   "processInstanceId":"66",
   "processDefinitionId":"oneTaskProcess:1:158",
   "variables": {
      "input1": "test"
   }
}
----

*请求正文（从表单定义键开始）：*

[source,json,linenums]
----
{
   "formDefinitionKey":"simpleForm",
   "taskId":"88",
   "processInstanceId":"66",
   "processDefinitionId":"oneTaskProcess:1:158",
   "variables": {
      "input1": "test"
   }
}
----



在请求正文中只能使用+ formDefinitionId +或+ formDefinitionKey +中的一个。 参数+变量+和+ tenantId +是可选的。 如果省略+ tenantId +，将使用默认租户。 有关变量格式的更多信息可以在<<restVariables,变量部分>>中找到。

.存储表单实例 - 响应代码
[options="header"]
|===============
|响应吗|描述
|201|表示已创建表单实例。

|400|表示未找到表单定义（基于标识符或键），通过发送给定消息未存储表单实例，或者已传递无效变量。 状态描述包含有关错误的其他信息。

|===============


*响应成功正文:*

[source,json,linenums]
----
{
   "id":"48b9ac82-f1d3-11e6-8549-acde48001122",
   "url":"http://localhost:8182/form/form-instances/48b9ac82-f1d3-11e6-8549-acde48001122",
   "formDefinitionId":"818e4703-f1d2-11e6-8549-acde48001122",
   "taskId":"88",
   "processInstanceId":"66",
   "processDefinitionId":"oneTaskProcess:1:158",
   "submittedDate":"2013-04-17T10:17:43.902+0000",
   "submittedBy":"testUser",
   "formValuesId":"818e4703-f1d2-11e6-8549-acde48001110",
   "tenantId": null
}
----


[[restProcessInstancesGet]]


==== 表单实例列表

----
GET form/form-instances
----

.表单实例列表 - 请求参数
[options="header"]
|===============
|请求参数|是否必须|值类型|描述

|id|否|字符串|仅返回具有给定标识符的流程实例。

|表单定义ID|否|字符串|仅返回具有给定表单定义标识符的表单实例。

|模糊匹配表单ID|否|字符串|仅返回具有表单定义标识符（模糊匹配给定值）的表单实例。

|任务ID|否|字符串|仅返回具有给定任务标识符的表单实例。
|模糊匹配任务ID|否|字符串|仅返回具有任务标识符（如模糊匹配给定值）的表单实例。

|流程实例ID|否|字符串|仅返回具有给定流程实例标识符的表单实例。

|模糊匹配表单实例ID|否|字符串|仅返回具有与给定值(模糊匹配流程实例标识符)的表单实例。

|流程定义ID|否|字符串|仅返回具有给定流程定义标识符的表单实例。

|模糊匹配流程定义ID|否|字符串|仅返回具有与给定值（模糊匹配的流程定义标识符）的表单实例。

|由...提交|否|字符串|仅返回由...提交的给定提交的表单实例。

|模糊匹配由...提交|否|字符串|只返回模糊匹配给定值的提交的表单实例。

|租户ID|否|字符串|仅返回具有给定租户ID的流程实例。

|模糊匹配租户ID|否|字符串|仅返回具有类似给定值的(模糊匹配租户ID)的流程实例。

|没有租户ID|否|布尔|如果 true，则仅返回没有设置租户ID的流程实例。 如果是false，则忽略 租户ID 参数。

|排序|否|字符串|排序字段，应该是 提交日期 （默认）或 租户ID。

一般<<restPagingAndSort,分页和排序 查询参数>>可以用在本链接
|===============


.表单实例列表 - 响应编码
[options="header"]
|===============
|响应编码|描述
|200|表示请求成功，并返回表单实例

|400|表示参数以错误的格式传递。 状态消息包含其他信息。

|===============


*成功响应正文:*

[source,json,linenums]
----
{
   "data":[
      {
	   "id":"48b9ac82-f1d3-11e6-8549-acde48001122",
	   "url":"http://localhost:8182/form/form-instances/48b9ac82-f1d3-11e6-8549-acde48001122",
	   "formDefinitionId":"818e4703-f1d2-11e6-8549-acde48001122",
	   "taskId":"88",
	   "processInstanceId":"66",
	   "processDefinitionId":"oneTaskProcess:1:158",
	   "submittedDate":"2013-04-17T10:17:43.902+0000",
	   "submittedBy":"testUser",
	   "formValuesId":"818e4703-f1d2-11e6-8549-acde48001110",
	   "tenantId": null
	  }
   ],
   "total":1,
   "start":0,
   "sort":"submittedDate",
   "order":"asc",
   "size":1
}
----


==== 查询表单实例

----
POST query/form-instances
----

*请求正文:*

[source,json,linenums]
----
{
  "formDefinitionId":"818e4703-f1d2-11e6-8549-acde48001122"
}
----

请求正文可以包含可以在查询<<restFormInstancesGet,流程实例列表>>中使用的所有可能的过滤器

普通 <<restPagingAndSort,分页和排序，查询参数>> 可用于此URL。


.查询表单实例 - 响应编码
[options="header"]
|===============
|响应编码|描述
|200|表示请求成功，并返回表单实例

|400|表示参数以错误的格式传递。 状态消息包含其他信息

|===============

*成功响正文:*

[source,json,linenums]
----
{
   "data":[
      {
	   "id":"48b9ac82-f1d3-11e6-8549-acde48001122",
	   "url":"http://localhost:8182/form/form-instances/48b9ac82-f1d3-11e6-8549-acde48001122",
	   "formDefinitionId":"818e4703-f1d2-11e6-8549-acde48001122",
	   "taskId":"88",
	   "processInstanceId":"66",
	   "processDefinitionId":"oneTaskProcess:1:158",
	   "submittedDate":"2013-04-17T10:17:43.902+0000",
	   "submittedBy":"testUser",
	   "formValuesId":"818e4703-f1d2-11e6-8549-acde48001110",
	   "tenantId": null
	  }
   ],
   "total":1,
   "start":0,
   "sort":"submittedDate",
   "order":"asc",
   "size":1
}
----


=== 表单引擎


==== 获取表单引擎信息

----
GET form-management/engine
----


返回此REST服务中使用的引擎的只读视图。


*成功响应正文:*

[source,json,linenums]
----
{
   "name":"default",
   "version":"6.5.0.event-SNAPSHOT",
   "resourceUrl":"file://flowable/flowable.form.cfg.xml",
   "exception":null
}
----


.获取引擎信息 - 响应编码
[options="header"]
|===============
|响应编码|描述

|200|表示返回表单引擎信息。

|===============

