
UPDATE ".ACT_CMMN_DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = '192.168.68.111 (192.168.68.111)', LOCKGRANTED = TIMESTAMP('2021-11-11 16:06:32.338') WHERE ID = 1 AND LOCKED = 0;

ALTER TABLE ".ACT_CMMN_RU_CASE_INST ADD BUSINESS_STATUS_ VARCHAR(255);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ".ACT_CMMN_RU_CASE_INST');

ALTER TABLE ".ACT_CMMN_HI_CASE_INST ADD BUSINESS_STATUS_ VARCHAR(255);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ".ACT_CMMN_HI_CASE_INST');

INSERT INTO ".ACT_CMMN_DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('16', 'flowable', 'org/flowable/cmmn/db/liquibase/flowable-cmmn-db-changelog.xml', CURRENT TIMESTAMP, 14, '8:a697a222ddd99dd15b36516a252f1c63', 'addColumn tableName=ACT_CMMN_RU_CASE_INST; addColumn tableName=ACT_CMMN_HI_CASE_INST', '', 'EXECUTED', NULL, NULL, '4.3.5', '6643192527');

UPDATE ".ACT_CMMN_DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;

