IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ACT_IDX_HI_ENT_LNK_SCOPE') drop index ACT_HI_ENTITYLINK.ACT_IDX_HI_ENT_LNK_SCOPE;
IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ACT_IDX_HI_ENT_LNK_SCOPE_DEF') drop index ACT_HI_ENTITYLINK.ACT_IDX_HI_ENT_LNK_SCOPE_DEF;

if exists (select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ACT_HI_ENTITYLINK') drop table ACT_HI_ENTITYLINK;