
CREATE TABLE PUBLIC.ACT_APP_DATABASECHANGELOG (ID varchar(191) NOT NULL, AUTHOR varchar(191) NOT NULL, FILENAME varchar(191) NOT NULL, DATEEXECUTED TIMESTAMP NOT NULL, ORDEREXECUTED INT NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35), DESCRIPTION varchar(191), COMMENTS varchar(191), TAG varchar(191), LIQUIBASE VARCHAR(20), CONTEXTS varchar(191), LABELS varchar(191), DEPLOYMENT_ID VARCHAR(10));

CREATE TABLE PUBLIC.ACT_APP_DEPLOYMENT (ID_ varchar(191) NOT NULL, NAME_ varchar(191), CATEGORY_ varchar(191), KEY_ varchar(191), DEPLOY_TIME_ TIMESTAMP, TENANT_ID_ varchar(191) DEFAULT '', CONSTRAINT PK_ACT_APP_DEPLOYMENT PRIMARY KEY (ID_));

CREATE TABLE PUBLIC.ACT_APP_DEPLOYMENT_RESOURCE (ID_ varchar(191) NOT NULL, NAME_ varchar(191), DEPLOYMENT_ID_ varchar(191), RESOURCE_BYTES_ BLOB, CONSTRAINT PK_APP_DEPLOYMENT_RESOURCE PRIMARY KEY (ID_));

ALTER TABLE PUBLIC.ACT_APP_DEPLOYMENT_RESOURCE ADD CONSTRAINT ACT_FK_APP_RSRC_DPL FOREIGN KEY (DEPLOYMENT_ID_) REFERENCES PUBLIC.ACT_APP_DEPLOYMENT (ID_);

CREATE INDEX PUBLIC.ACT_IDX_APP_RSRC_DPL ON PUBLIC.ACT_APP_DEPLOYMENT_RESOURCE(DEPLOYMENT_ID_);

CREATE TABLE PUBLIC.ACT_APP_APPDEF (ID_ varchar(191) NOT NULL, REV_ INT NOT NULL, NAME_ varchar(191), KEY_ varchar(191) NOT NULL, VERSION_ INT NOT NULL, CATEGORY_ varchar(191), DEPLOYMENT_ID_ varchar(191), RESOURCE_NAME_ VARCHAR(4000), DESCRIPTION_ VARCHAR(4000), TENANT_ID_ varchar(191) DEFAULT '', CONSTRAINT PK_ACT_APP_APPDEF PRIMARY KEY (ID_));

ALTER TABLE PUBLIC.ACT_APP_APPDEF ADD CONSTRAINT ACT_FK_APP_DEF_DPLY FOREIGN KEY (DEPLOYMENT_ID_) REFERENCES PUBLIC.ACT_APP_DEPLOYMENT (ID_);

CREATE INDEX PUBLIC.ACT_IDX_APP_DEF_DPLY ON PUBLIC.ACT_APP_APPDEF(DEPLOYMENT_ID_);

INSERT INTO PUBLIC.ACT_APP_DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1', 'flowable', 'org/flowable/app/db/liquibase/flowable-app-db-changelog.xml', NOW(), 1, '8:496fc778bdf2ab13f2e1926d0e63e0a2', 'createTable tableName=ACT_APP_DEPLOYMENT; createTable tableName=ACT_APP_DEPLOYMENT_RESOURCE; addForeignKeyConstraint baseTableName=ACT_APP_DEPLOYMENT_RESOURCE, constraintName=ACT_FK_APP_RSRC_DPL, referencedTableName=ACT_APP_DEPLOYMENT; createIndex...', '', 'EXECUTED', NULL, NULL, '3.6.1', '6986083340');

