alter table ACT_HI_TASKINST 
  add STATE_ nvarchar(255),
  add IN_PROGRESS_TIME_ datetime,
  add IN_PROGRESS_STARTED_BY_ nvarchar(255),
  add CLAIMED_BY_ nvarchar(255),
  add SUSPENDED_TIME_ datetime,
  add SUSPENDED_BY_ nvarchar(255),
  add COMPLETED_BY_ nvarchar(255),
  add IN_PROGRESS_DUE_DATE_ datetime;
