CREATE TABLE ACT_GE_PROPERTY (
    NAME_ STRING(64) NOT NULL,
    VALUE_ STRING(300),
    REV_ INT64
) PRIMARY KEY (NAME_);

CREATE TABLE ACT_GE_BYTEARRAY (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    NAME_ STRING(255),
    DEPLOYMENT_ID_ STRING(64),
    BYTES_ BYTES(MAX),
    GENERATED_ BOOL
) PRIMARY KEY (ID_);

INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_) VALUES ('common.schema.version', '8.1.0.1', 1);
INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_) VALUES ('next.dbid', '1', 1);

CREATE TABLE ACT_RU_ENTITYLINK (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    CREATE_TIME_ TIMESTAMP,
    LINK_TYPE_ STRING(255),
    SCOPE_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    SCOPE_DEFINITION_ID_ STRING(255),
    PARENT_ELEMENT_ID_ STRING(255),
    REF_SCOPE_ID_ STRING(255),
    REF_SCOPE_TYPE_ STRING(255),
    REF_SCOPE_DEFINITION_ID_ STRING(255),
    ROOT_SCOPE_ID_ STRING(255),
    ROOT_SCOPE_TYPE_ STRING(255),
    HIERARCHY_TYPE_ STRING(255)
) PRIMARY KEY (ID_);

CREATE INDEX ACT_IDX_ENT_LNK_SCOPE ON ACT_RU_ENTITYLINK(SCOPE_ID_, SCOPE_TYPE_, LINK_TYPE_);
CREATE INDEX ACT_IDX_ENT_LNK_REF_SCOPE ON ACT_RU_ENTITYLINK(REF_SCOPE_ID_, REF_SCOPE_TYPE_, LINK_TYPE_);
CREATE INDEX ACT_IDX_ENT_LNK_ROOT_SCOPE ON ACT_RU_ENTITYLINK(ROOT_SCOPE_ID_, ROOT_SCOPE_TYPE_, LINK_TYPE_);
CREATE INDEX ACT_IDX_ENT_LNK_SCOPE_DEF ON ACT_RU_ENTITYLINK(SCOPE_DEFINITION_ID_, SCOPE_TYPE_, LINK_TYPE_);

CREATE TABLE ACT_HI_ENTITYLINK (
    ID_ STRING(64) NOT NULL,
    LINK_TYPE_ STRING(255),
    CREATE_TIME_ TIMESTAMP,
    SCOPE_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    SCOPE_DEFINITION_ID_ STRING(255),
    PARENT_ELEMENT_ID_ STRING(255),
    REF_SCOPE_ID_ STRING(255),
    REF_SCOPE_TYPE_ STRING(255),
    REF_SCOPE_DEFINITION_ID_ STRING(255),
    ROOT_SCOPE_ID_ STRING(255),
    ROOT_SCOPE_TYPE_ STRING(255),
    HIERARCHY_TYPE_ STRING(255)
) PRIMARY KEY (ID_);

CREATE INDEX ACT_IDX_HI_ENT_LNK_SCOPE ON ACT_HI_ENTITYLINK(SCOPE_ID_, SCOPE_TYPE_, LINK_TYPE_);
CREATE INDEX ACT_IDX_HI_ENT_LNK_REF_SCOPE ON ACT_HI_ENTITYLINK(REF_SCOPE_ID_, REF_SCOPE_TYPE_, LINK_TYPE_);
CREATE INDEX ACT_IDX_HI_ENT_LNK_ROOT_SCOPE ON ACT_HI_ENTITYLINK(ROOT_SCOPE_ID_, ROOT_SCOPE_TYPE_, LINK_TYPE_);
CREATE INDEX ACT_IDX_HI_ENT_LNK_SCOPE_DEF ON ACT_HI_ENTITYLINK(SCOPE_DEFINITION_ID_, SCOPE_TYPE_, LINK_TYPE_);

CREATE TABLE ACT_RU_IDENTITYLINK (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    GROUP_ID_ STRING(255),
    TYPE_ STRING(255),
    USER_ID_ STRING(255),
    TASK_ID_ STRING(64),
    PROC_INST_ID_ STRING(64),
    PROC_DEF_ID_ STRING(64),
    SCOPE_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    SCOPE_DEFINITION_ID_ STRING(255)
) PRIMARY KEY (ID_);

CREATE INDEX ACT_IDX_IDENT_LNK_USER ON ACT_RU_IDENTITYLINK(USER_ID_);
CREATE INDEX ACT_IDX_IDENT_LNK_GROUP ON ACT_RU_IDENTITYLINK(GROUP_ID_);
CREATE INDEX ACT_IDX_IDENT_LNK_SCOPE ON ACT_RU_IDENTITYLINK(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_IDENT_LNK_SUB_SCOPE ON ACT_RU_IDENTITYLINK(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_IDENT_LNK_SCOPE_DEF ON ACT_RU_IDENTITYLINK(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);

CREATE TABLE ACT_HI_IDENTITYLINK (
    ID_ STRING(64) NOT NULL,
    GROUP_ID_ STRING(255),
    TYPE_ STRING(255),
    USER_ID_ STRING(255),
    TASK_ID_ STRING(64),
    CREATE_TIME_ TIMESTAMP,
    PROC_INST_ID_ STRING(64),
    SCOPE_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    SCOPE_DEFINITION_ID_ STRING(255)
) PRIMARY KEY (ID_);

CREATE INDEX ACT_IDX_HI_IDENT_LNK_USER ON ACT_HI_IDENTITYLINK(USER_ID_);
CREATE INDEX ACT_IDX_HI_IDENT_LNK_SCOPE ON ACT_HI_IDENTITYLINK(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_HI_IDENT_LNK_SUB_SCOPE ON ACT_HI_IDENTITYLINK(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_HI_IDENT_LNK_SCOPE_DEF ON ACT_HI_IDENTITYLINK(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);

CREATE TABLE ACT_RU_JOB (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    CATEGORY_ STRING(255),
    TYPE_ STRING(255) NOT NULL,
    LOCK_EXP_TIME_ TIMESTAMP,
    LOCK_OWNER_ STRING(255),
    EXCLUSIVE_ BOOL,
    EXECUTION_ID_ STRING(64),
    PROCESS_INSTANCE_ID_ STRING(64),
    PROC_DEF_ID_ STRING(64),
    ELEMENT_ID_ STRING(255),
    ELEMENT_NAME_ STRING(255),
    SCOPE_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    SCOPE_DEFINITION_ID_ STRING(255),
    CORRELATION_ID_ STRING(255),
    RETRIES_ INT64,
    EXCEPTION_STACK_ID_ STRING(64),
    EXCEPTION_MSG_ STRING(4000),
    DUEDATE_ TIMESTAMP,
    REPEAT_ STRING(255),
    HANDLER_TYPE_ STRING(255),
    HANDLER_CFG_ STRING(4000),
    CUSTOM_VALUES_ID_ STRING(64),
    CREATE_TIME_ TIMESTAMP,
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_RU_TIMER_JOB (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    CATEGORY_ STRING(255),
    TYPE_ STRING(255) NOT NULL,
    LOCK_EXP_TIME_ TIMESTAMP,
    LOCK_OWNER_ STRING(255),
    EXCLUSIVE_ BOOL,
    EXECUTION_ID_ STRING(64),
    PROCESS_INSTANCE_ID_ STRING(64),
    PROC_DEF_ID_ STRING(64),
    ELEMENT_ID_ STRING(255),
    ELEMENT_NAME_ STRING(255),
    SCOPE_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    SCOPE_DEFINITION_ID_ STRING(255),
    CORRELATION_ID_ STRING(255),
    RETRIES_ INT64,
    EXCEPTION_STACK_ID_ STRING(64),
    EXCEPTION_MSG_ STRING(4000),
    DUEDATE_ TIMESTAMP,
    REPEAT_ STRING(255),
    HANDLER_TYPE_ STRING(255),
    HANDLER_CFG_ STRING(4000),
    CUSTOM_VALUES_ID_ STRING(64),
    CREATE_TIME_ TIMESTAMP,
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_RU_SUSPENDED_JOB (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    CATEGORY_ STRING(255),
    TYPE_ STRING(255) NOT NULL,
    EXCLUSIVE_ BOOL,
    EXECUTION_ID_ STRING(64),
    PROCESS_INSTANCE_ID_ STRING(64),
    PROC_DEF_ID_ STRING(64),
    ELEMENT_ID_ STRING(255),
    ELEMENT_NAME_ STRING(255),
    SCOPE_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    SCOPE_DEFINITION_ID_ STRING(255),
    CORRELATION_ID_ STRING(255),
    RETRIES_ INT64,
    EXCEPTION_STACK_ID_ STRING(64),
    EXCEPTION_MSG_ STRING(4000),
    DUEDATE_ TIMESTAMP,
    REPEAT_ STRING(255),
    HANDLER_TYPE_ STRING(255),
    HANDLER_CFG_ STRING(4000),
    CUSTOM_VALUES_ID_ STRING(64),
    CREATE_TIME_ TIMESTAMP,
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_RU_DEADLETTER_JOB (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    CATEGORY_ STRING(255),
    TYPE_ STRING(255) NOT NULL,
    EXCLUSIVE_ BOOL,
    EXECUTION_ID_ STRING(64),
    PROCESS_INSTANCE_ID_ STRING(64),
    PROC_DEF_ID_ STRING(64),
    ELEMENT_ID_ STRING(255),
    ELEMENT_NAME_ STRING(255),
    SCOPE_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    SCOPE_DEFINITION_ID_ STRING(255),
    CORRELATION_ID_ STRING(255),
    EXCEPTION_STACK_ID_ STRING(64),
    EXCEPTION_MSG_ STRING(4000),
    DUEDATE_ TIMESTAMP,
    REPEAT_ STRING(255),
    HANDLER_TYPE_ STRING(255),
    HANDLER_CFG_ STRING(4000),
    CUSTOM_VALUES_ID_ STRING(64),
    CREATE_TIME_ TIMESTAMP,
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_RU_HISTORY_JOB (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    LOCK_EXP_TIME_ TIMESTAMP,
    LOCK_OWNER_ STRING(255),
    RETRIES_ INT64,
    EXCEPTION_STACK_ID_ STRING(64),
    EXCEPTION_MSG_ STRING(4000),
    HANDLER_TYPE_ STRING(255),
    HANDLER_CFG_ STRING(4000),
    CUSTOM_VALUES_ID_ STRING(64),
    ADV_HANDLER_CFG_ID_ STRING(64),
    CREATE_TIME_ TIMESTAMP,
    SCOPE_TYPE_ STRING(255),
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_RU_EXTERNAL_JOB (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    CATEGORY_ STRING(255),
    TYPE_ STRING(255) NOT NULL,
    LOCK_EXP_TIME_ TIMESTAMP,
    LOCK_OWNER_ STRING(255),
    EXCLUSIVE_ BOOL,
    EXECUTION_ID_ STRING(64),
    PROCESS_INSTANCE_ID_ STRING(64),
    PROC_DEF_ID_ STRING(64),
    ELEMENT_ID_ STRING(255),
    ELEMENT_NAME_ STRING(255),
    SCOPE_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    SCOPE_DEFINITION_ID_ STRING(255),
    CORRELATION_ID_ STRING(255),
    RETRIES_ INT64,
    EXCEPTION_STACK_ID_ STRING(64),
    EXCEPTION_MSG_ STRING(4000),
    DUEDATE_ TIMESTAMP,
    REPEAT_ STRING(255),
    HANDLER_TYPE_ STRING(255),
    HANDLER_CFG_ STRING(4000),
    CUSTOM_VALUES_ID_ STRING(64),
    CREATE_TIME_ TIMESTAMP,
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE INDEX ACT_IDX_JOB_EXCEPTION_STACK_ID ON ACT_RU_JOB(EXCEPTION_STACK_ID_);
CREATE INDEX ACT_IDX_JOB_CUSTOM_VALUES_ID ON ACT_RU_JOB(CUSTOM_VALUES_ID_);
CREATE INDEX ACT_IDX_JOB_CORRELATION_ID ON ACT_RU_JOB(CORRELATION_ID_);

CREATE INDEX ACT_IDX_TIMER_JOB_EXCEPTION_STACK_ID ON ACT_RU_TIMER_JOB(EXCEPTION_STACK_ID_);
CREATE INDEX ACT_IDX_TIMER_JOB_CUSTOM_VALUES_ID ON ACT_RU_TIMER_JOB(CUSTOM_VALUES_ID_);
CREATE INDEX ACT_IDX_TIMER_JOB_CORRELATION_ID ON ACT_RU_TIMER_JOB(CORRELATION_ID_);
CREATE INDEX ACT_IDX_TIMER_JOB_DUEDATE ON ACT_RU_TIMER_JOB(DUEDATE_);

CREATE INDEX ACT_IDX_SUSPENDED_JOB_EXCEPTION_STACK_ID ON ACT_RU_SUSPENDED_JOB(EXCEPTION_STACK_ID_);
CREATE INDEX ACT_IDX_SUSPENDED_JOB_CUSTOM_VALUES_ID ON ACT_RU_SUSPENDED_JOB(CUSTOM_VALUES_ID_);
CREATE INDEX ACT_IDX_SUSPENDED_JOB_CORRELATION_ID ON ACT_RU_SUSPENDED_JOB(CORRELATION_ID_);

CREATE INDEX ACT_IDX_DEADLETTER_JOB_EXCEPTION_STACK_ID ON ACT_RU_DEADLETTER_JOB(EXCEPTION_STACK_ID_);
CREATE INDEX ACT_IDX_DEADLETTER_JOB_CUSTOM_VALUES_ID ON ACT_RU_DEADLETTER_JOB(CUSTOM_VALUES_ID_);
CREATE INDEX ACT_IDX_DEADLETTER_JOB_CORRELATION_ID ON ACT_RU_DEADLETTER_JOB(CORRELATION_ID_);

CREATE INDEX ACT_IDX_EXTERNAL_JOB_EXCEPTION_STACK_ID ON ACT_RU_EXTERNAL_JOB(EXCEPTION_STACK_ID_);
CREATE INDEX ACT_IDX_EXTERNAL_JOB_CUSTOM_VALUES_ID ON ACT_RU_EXTERNAL_JOB(CUSTOM_VALUES_ID_);
CREATE INDEX ACT_IDX_EXTERNAL_JOB_CORRELATION_ID ON ACT_RU_EXTERNAL_JOB(CORRELATION_ID_);

ALTER TABLE ACT_RU_JOB
    ADD CONSTRAINT ACT_FK_JOB_EXCEPTION
    FOREIGN KEY (EXCEPTION_STACK_ID_)
    REFERENCES ACT_GE_BYTEARRAY (ID_);

ALTER TABLE ACT_RU_JOB
    ADD CONSTRAINT ACT_FK_JOB_CUSTOM_VALUES
    FOREIGN KEY (CUSTOM_VALUES_ID_)
    REFERENCES ACT_GE_BYTEARRAY (ID_);

ALTER TABLE ACT_RU_TIMER_JOB
    ADD CONSTRAINT ACT_FK_TIMER_JOB_EXCEPTION
    FOREIGN KEY (EXCEPTION_STACK_ID_)
    REFERENCES ACT_GE_BYTEARRAY (ID_);

ALTER TABLE ACT_RU_TIMER_JOB
    ADD CONSTRAINT ACT_FK_TIMER_JOB_CUSTOM_VALUES
    FOREIGN KEY (CUSTOM_VALUES_ID_)
    REFERENCES ACT_GE_BYTEARRAY (ID_);

ALTER TABLE ACT_RU_SUSPENDED_JOB
    ADD CONSTRAINT ACT_FK_SUSPENDED_JOB_EXCEPTION
    FOREIGN KEY (EXCEPTION_STACK_ID_)
    REFERENCES ACT_GE_BYTEARRAY (ID_);

ALTER TABLE ACT_RU_SUSPENDED_JOB
    ADD CONSTRAINT ACT_FK_SUSPENDED_JOB_CUSTOM_VALUES
    FOREIGN KEY (CUSTOM_VALUES_ID_)
    REFERENCES ACT_GE_BYTEARRAY (ID_);

ALTER TABLE ACT_RU_DEADLETTER_JOB
    ADD CONSTRAINT ACT_FK_DEADLETTER_JOB_EXCEPTION
    FOREIGN KEY (EXCEPTION_STACK_ID_)
    REFERENCES ACT_GE_BYTEARRAY (ID_);

ALTER TABLE ACT_RU_DEADLETTER_JOB
    ADD CONSTRAINT ACT_FK_DEADLETTER_JOB_CUSTOM_VALUES
    FOREIGN KEY (CUSTOM_VALUES_ID_)
    REFERENCES ACT_GE_BYTEARRAY (ID_);

ALTER TABLE ACT_RU_EXTERNAL_JOB
    ADD CONSTRAINT ACT_FK_EXTERNAL_JOB_EXCEPTION
    FOREIGN KEY (EXCEPTION_STACK_ID_)
    REFERENCES ACT_GE_BYTEARRAY (ID_);

ALTER TABLE ACT_RU_EXTERNAL_JOB
    ADD CONSTRAINT ACT_FK_EXTERNAL_JOB_CUSTOM_VALUES
    FOREIGN KEY (CUSTOM_VALUES_ID_)
    REFERENCES ACT_GE_BYTEARRAY (ID_);

CREATE INDEX ACT_IDX_JOB_SCOPE ON ACT_RU_JOB(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_JOB_SUB_SCOPE ON ACT_RU_JOB(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_JOB_SCOPE_DEF ON ACT_RU_JOB(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);

CREATE INDEX ACT_IDX_TJOB_SCOPE ON ACT_RU_TIMER_JOB(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_TJOB_SUB_SCOPE ON ACT_RU_TIMER_JOB(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_TJOB_SCOPE_DEF ON ACT_RU_TIMER_JOB(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);

CREATE INDEX ACT_IDX_SJOB_SCOPE ON ACT_RU_SUSPENDED_JOB(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_SJOB_SUB_SCOPE ON ACT_RU_SUSPENDED_JOB(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_SJOB_SCOPE_DEF ON ACT_RU_SUSPENDED_JOB(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);

CREATE INDEX ACT_IDX_DJOB_SCOPE ON ACT_RU_DEADLETTER_JOB(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_DJOB_SUB_SCOPE ON ACT_RU_DEADLETTER_JOB(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_DJOB_SCOPE_DEF ON ACT_RU_DEADLETTER_JOB(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);

CREATE INDEX ACT_IDX_EJOB_SCOPE ON ACT_RU_EXTERNAL_JOB(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_EJOB_SUB_SCOPE ON ACT_RU_EXTERNAL_JOB(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_EJOB_SCOPE_DEF ON ACT_RU_EXTERNAL_JOB(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);

CREATE TABLE FLW_RU_BATCH (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    TYPE_ STRING(64) NOT NULL,
    SEARCH_KEY_ STRING(255),
    SEARCH_KEY2_ STRING(255),
    CREATE_TIME_ TIMESTAMP NOT NULL,
    COMPLETE_TIME_ TIMESTAMP,
    STATUS_ STRING(255),
    BATCH_DOC_ID_ STRING(64),
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE FLW_RU_BATCH_PART (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    BATCH_ID_ STRING(64),
    TYPE_ STRING(64) NOT NULL,
    SCOPE_ID_ STRING(64),
    SUB_SCOPE_ID_ STRING(64),
    SCOPE_TYPE_ STRING(64),
    SEARCH_KEY_ STRING(255),
    SEARCH_KEY2_ STRING(255),
    CREATE_TIME_ TIMESTAMP NOT NULL,
    COMPLETE_TIME_ TIMESTAMP,
    STATUS_ STRING(255),
    RESULT_DOC_ID_ STRING(64),
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE INDEX FLW_IDX_BATCH_PART ON FLW_RU_BATCH_PART(BATCH_ID_);

ALTER TABLE FLW_RU_BATCH_PART
    ADD CONSTRAINT FLW_FK_BATCH_PART_PARENT
    FOREIGN KEY (BATCH_ID_)
    REFERENCES FLW_RU_BATCH (ID_);

CREATE TABLE ACT_RU_TASK (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    EXECUTION_ID_ STRING(64),
    PROC_INST_ID_ STRING(64),
    PROC_DEF_ID_ STRING(64),
    TASK_DEF_ID_ STRING(64),
    SCOPE_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    SCOPE_DEFINITION_ID_ STRING(255),
    PROPAGATED_STAGE_INST_ID_ STRING(255),
    STATE_ STRING(255),
    NAME_ STRING(255),
    PARENT_TASK_ID_ STRING(64),
    DESCRIPTION_ STRING(4000),
    TASK_DEF_KEY_ STRING(255),
    OWNER_ STRING(255),
    ASSIGNEE_ STRING(255),
    DELEGATION_ STRING(64),
    PRIORITY_ INT64,
    CREATE_TIME_ TIMESTAMP,
    IN_PROGRESS_TIME_ TIMESTAMP,
    IN_PROGRESS_STARTED_BY_ STRING(255),
    CLAIM_TIME_ TIMESTAMP,
    CLAIMED_BY_ STRING(255),
    SUSPENDED_TIME_ TIMESTAMP,
    SUSPENDED_BY_ STRING(255),
    IN_PROGRESS_DUE_DATE_ TIMESTAMP,
    DUE_DATE_ TIMESTAMP,
    CATEGORY_ STRING(255),
    SUSPENSION_STATE_ INT64,
    TENANT_ID_ STRING(255) DEFAULT (''),
    FORM_KEY_ STRING(255),
    IS_COUNT_ENABLED_ BOOL,
    VAR_COUNT_ INT64,
    ID_LINK_COUNT_ INT64,
    SUB_TASK_COUNT_ INT64
) PRIMARY KEY (ID_);

CREATE INDEX ACT_IDX_TASK_CREATE ON ACT_RU_TASK(CREATE_TIME_);
CREATE INDEX ACT_IDX_TASK_SCOPE ON ACT_RU_TASK(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_TASK_SUB_SCOPE ON ACT_RU_TASK(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_TASK_SCOPE_DEF ON ACT_RU_TASK(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);

CREATE TABLE ACT_HI_TASKINST (
    ID_ STRING(64) NOT NULL,
    REV_ INT64 DEFAULT (1),
    PROC_DEF_ID_ STRING(64),
    TASK_DEF_ID_ STRING(64),
    TASK_DEF_KEY_ STRING(255),
    PROC_INST_ID_ STRING(64),
    EXECUTION_ID_ STRING(64),
    SCOPE_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    SCOPE_DEFINITION_ID_ STRING(255),
    PROPAGATED_STAGE_INST_ID_ STRING(255),
    STATE_ STRING(255),
    NAME_ STRING(255),
    PARENT_TASK_ID_ STRING(64),
    DESCRIPTION_ STRING(4000),
    OWNER_ STRING(255),
    ASSIGNEE_ STRING(255),
    START_TIME_ TIMESTAMP NOT NULL,
    IN_PROGRESS_TIME_ TIMESTAMP,
    IN_PROGRESS_STARTED_BY_ STRING(255),
    CLAIM_TIME_ TIMESTAMP,
    CLAIMED_BY_ STRING(255),
    SUSPENDED_TIME_ TIMESTAMP,
    SUSPENDED_BY_ STRING(255),
    END_TIME_ TIMESTAMP,
    COMPLETED_BY_ STRING(255),
    DURATION_ INT64,
    DELETE_REASON_ STRING(4000),
    PRIORITY_ INT64,
    IN_PROGRESS_DUE_DATE_ TIMESTAMP,
    DUE_DATE_ TIMESTAMP,
    FORM_KEY_ STRING(255),
    CATEGORY_ STRING(255),
    TENANT_ID_ STRING(255) DEFAULT (''),
    LAST_UPDATED_TIME_ TIMESTAMP
) PRIMARY KEY (ID_);

CREATE TABLE ACT_HI_TSK_LOG (
    ID_ INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE),
    TYPE_ STRING(64),
    TASK_ID_ STRING(64) NOT NULL,
    TIME_STAMP_ TIMESTAMP NOT NULL,
    USER_ID_ STRING(255),
    DATA_ STRING(4000),
    EXECUTION_ID_ STRING(64),
    PROC_INST_ID_ STRING(64),
    PROC_DEF_ID_ STRING(64),
    SCOPE_ID_ STRING(255),
    SCOPE_DEFINITION_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE INDEX ACT_IDX_HI_TASK_SCOPE ON ACT_HI_TASKINST(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_HI_TASK_SUB_SCOPE ON ACT_HI_TASKINST(SUB_SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_HI_TASK_SCOPE_DEF ON ACT_HI_TASKINST(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_ACT_HI_TSK_LOG_TASK ON ACT_HI_TSK_LOG(TASK_ID_);

CREATE TABLE ACT_RU_VARIABLE (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    TYPE_ STRING(255) NOT NULL,
    NAME_ STRING(255) NOT NULL,
    EXECUTION_ID_ STRING(64),
    PROC_INST_ID_ STRING(64),
    TASK_ID_ STRING(64),
    SCOPE_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    BYTEARRAY_ID_ STRING(64),
    DOUBLE_ FLOAT64,
    LONG_ INT64,
    TEXT_ STRING(4000),
    TEXT2_ STRING(4000),
    META_INFO_ STRING(4000)
) PRIMARY KEY (ID_);

CREATE INDEX ACT_IDX_RU_VAR_SCOPE_ID_TYPE ON ACT_RU_VARIABLE(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_RU_VAR_SUB_ID_TYPE ON ACT_RU_VARIABLE(SUB_SCOPE_ID_, SCOPE_TYPE_);

CREATE INDEX ACT_IDX_VAR_BYTEARRAY ON ACT_RU_VARIABLE(BYTEARRAY_ID_);
ALTER TABLE ACT_RU_VARIABLE 
    ADD CONSTRAINT ACT_FK_VAR_BYTEARRAY 
    FOREIGN KEY (BYTEARRAY_ID_) 
    REFERENCES ACT_GE_BYTEARRAY (ID_);

CREATE TABLE ACT_HI_VARINST (
    ID_ STRING(64) NOT NULL,
    REV_ INT64 DEFAULT (1),
    PROC_INST_ID_ STRING(64),
    EXECUTION_ID_ STRING(64),
    TASK_ID_ STRING(64),
    NAME_ STRING(255) NOT NULL,
    VAR_TYPE_ STRING(100),
    SCOPE_ID_ STRING(255),
    SUB_SCOPE_ID_ STRING(255),
    SCOPE_TYPE_ STRING(255),
    BYTEARRAY_ID_ STRING(64),
    DOUBLE_ FLOAT64,
    LONG_ INT64,
    TEXT_ STRING(4000),
    TEXT2_ STRING(4000),
    META_INFO_ STRING(4000),
    CREATE_TIME_ TIMESTAMP,
    LAST_UPDATED_TIME_ TIMESTAMP
) PRIMARY KEY (ID_);

CREATE INDEX ACT_IDX_HI_PROCVAR_NAME_TYPE ON ACT_HI_VARINST(NAME_, VAR_TYPE_);
CREATE INDEX ACT_IDX_HI_VAR_SCOPE_ID_TYPE ON ACT_HI_VARINST(SCOPE_ID_, SCOPE_TYPE_);
CREATE INDEX ACT_IDX_HI_VAR_SUB_ID_TYPE ON ACT_HI_VARINST(SUB_SCOPE_ID_, SCOPE_TYPE_);

CREATE TABLE ACT_RU_EVENT_SUBSCR (
    ID_ STRING(64) NOT NULL,
    REV_ INT64,
    EVENT_TYPE_ STRING(255) NOT NULL,
    EVENT_NAME_ STRING(255),
    EXECUTION_ID_ STRING(64),
    PROC_INST_ID_ STRING(64),
    ACTIVITY_ID_ STRING(255),
    CONFIGURATION_ STRING(255),
    CREATED_ TIMESTAMP NOT NULL,
    PROC_DEF_ID_ STRING(64),
    SUB_SCOPE_ID_ STRING(64),
    SCOPE_ID_ STRING(64),
    SCOPE_DEFINITION_ID_ STRING(64),
    SCOPE_DEFINITION_KEY_ STRING(255),
    SCOPE_TYPE_ STRING(64),
    LOCK_TIME_ TIMESTAMP,
    LOCK_OWNER_ STRING(255),
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE INDEX ACT_IDX_EVENT_SUBSCR_CONFIG_ ON ACT_RU_EVENT_SUBSCR(CONFIGURATION_);
CREATE INDEX ACT_IDX_EVENT_SUBSCR ON ACT_RU_EVENT_SUBSCR(EXECUTION_ID_);
CREATE INDEX ACT_IDX_EVENT_SUBSCR_PROC_ID ON ACT_RU_EVENT_SUBSCR(PROC_INST_ID_);
CREATE INDEX ACT_IDX_EVENT_SUBSCR_SCOPEREF_ ON ACT_RU_EVENT_SUBSCR(SCOPE_ID_, SCOPE_TYPE_);
