create table ACT_HI_TASKINST (
    ID_ NVARCHAR(64) not null,
    REV_ INTEGER default 1,
    PROC_DEF_ID_ NVARCHAR(64),
    TASK_DEF_ID_ NVARCHAR(64),
    TASK_DEF_KEY_ NVARCHAR(255),
    PROC_INST_ID_ NVARCHAR(64),
    EXECUTION_ID_ NVARCHAR(64),
    SCOPE_ID_ NVARCHAR(255),
    SUB_SCOPE_ID_ NVARCHAR(255),
    SCOPE_TYPE_ NVARCHAR(255),
    SCOPE_DEFINITION_ID_ NVARCHAR(255),
    PARENT_TASK_ID_ NVARCHAR(64),
    NAME_ NVARCHAR(255),
    DESCRIPTION_ NVARCHAR(2000),
    OWNER_ NVARCHAR(255),
    ASSIGNEE_ NVARCHAR(255),
    START_TIME_ TIMESTAMP not null,
    CLAIM_TIME_ TIMESTAMP,
    END_TIME_ TIMESTAMP,
    DURATION_ INTEGER,
    DELETE_REASON_ NVARCHAR(2000),
    PRIORITY_ INTEGER,
    DUE_DATE_ TIMESTAMP,
    FORM_KEY_ NVARCHAR(255),
    CATEGORY_ NVARCHAR(255),
    TENANT_ID_ NVARCHAR(255) default '',
    LAST_UPDATED_TIME_ TIMESTAMP,
    primary key ("ID_")
);

create index ACT_IDX_HI_TASK_SCOPE on ACT_HI_TASKINST(SCOPE_ID_, SCOPE_TYPE_);
create index ACT_IDX_HI_TASK_SUB_SCOPE on ACT_HI_TASKINST(SUB_SCOPE_ID_, SCOPE_TYPE_);
create index ACT_IDX_HI_TASK_SCOPE_DEF on ACT_HI_TASKINST(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);