server:
  port: 8090
  use-forward-headers: true


spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  servlet:
    multipart:
      max-file-size: 104MB
      max-request-size: 104MB
  cloud:
    gateway:
        routes:
          - id: flowable-admin
            uri: http://localhost:9988/flowable-admin/
            predicates:
              - Path=/flowable-admin/**
          - id: flowable-idm
            uri: http://localhost:8080/flowable-idm/
            predicates:
              - Path=/flowable-idm/**
          - id: flowable-modeler
            uri: http://localhost:8888/flowable-modeler/
            predicates:
              - Path=/flowable-modeler/**
          - id: flowable-task
            uri: http://localhost:9988/flowable-task/
            predicates:
              - Path=/flowable-task/**

management:
  endpoints:
    web:
      exposure:
        # Expose all actuator endpoints to the web
        # They are exposed, but only authenticated users can see /info and /health abd users with access-admin can see the others
        include: "*"
  endpoint:
    health:
      # Full health details should only be displayed when a user is authorized
      show-details: when_authorized
      # Only users with role access-admin can access full health details
      roles: access-admin

ribbon:
  eureka:
    enabled: false
