CREATE TABLE ACT_APP_DEPLOYMENT (
    ID_ STRING(255) NOT NULL,
    NAME_ STRING(255),
    CATEGORY_ STRING(255),
    KEY_ STRING(255),
    DEPLOY_TIME_ TIMESTAMP,
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_APP_DEPLOYMENT_RESOURCE (
    ID_ STRING(255) NOT NULL,
    NAME_ STRING(255),
    DEPLOYMENT_ID_ STRING(255),
    RESOURCE_BYTES_ BYTES(MAX)
) PRIMARY KEY (ID_);

ALTER TABLE ACT_APP_DEPLOYMENT_RESOURCE
    ADD CONSTRAINT ACT_FK_APP_RSRC_DPL
    FOREIGN KEY (DEPLOYMENT_ID_)
    REFERENCES ACT_APP_DEPLOYMENT (ID_);

CREATE INDEX ACT_IDX_APP_RSRC_DPL ON ACT_APP_DEPLOYMENT_RESOURCE(DEPLOYMENT_ID_);

CREATE TABLE ACT_APP_APPDEF (
    ID_ STRING(255) NOT NULL,
    REV_ INT64 NOT NULL,
    NAME_ STRING(255),
    KEY_ STRING(255) NOT NULL,
    VERSION_ INT64 NOT NULL,
    CATEGORY_ STRING(255),
    DEPLOYMENT_ID_ STRING(255),
    RESOURCE_NAME_ STRING(4000),
    DESCRIPTION_ STRING(4000),
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

ALTER TABLE ACT_APP_APPDEF
    ADD CONSTRAINT ACT_FK_APP_DEF_DPLY
    FOREIGN KEY (DEPLOYMENT_ID_)
    REFERENCES ACT_APP_DEPLOYMENT (ID_);

CREATE INDEX ACT_IDX_APP_DEF_DPLY ON ACT_APP_APPDEF(DEPLOYMENT_ID_);

CREATE UNIQUE NULL_FILTERED INDEX ACT_IDX_APP_DEF_UNIQ ON ACT_APP_APPDEF(KEY_, VERSION_, TENANT_ID_);

INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_) VALUES ('app.schema.version', '8.1.0.1', 1);
