CREATE TABLE ACT_CMMN_DEPLOYMENT (
    ID_ STRING(255) NOT NULL,
    NAME_ STRING(255),
    CATEGORY_ STRING(255),
    KEY_ STRING(255),
    DEPLOY_TIME_ TIMESTAMP,
    PARENT_DEPLOYMENT_ID_ STRING(255),
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_CMMN_DEPLOYMENT_RESOURCE (
    ID_ STRING(255) NOT NULL,
    NAME_ STRING(255),
    DEPLOYMENT_ID_ STRING(255),
    RESOURCE_BYTES_ BYTES(MAX),
    GENERATED_ BOOL
) PRIMARY KEY (ID_);

CREATE TABLE ACT_CMMN_CASEDEF (
    ID_ STRING(255) NOT NULL,
    REV_ INT64 NOT NULL,
    NAME_ STRING(255),
    KEY_ STRING(255) NOT NULL,
    VERSION_ INT64 NOT NULL,
    CATEGORY_ STRING(255),
    DEPLOYMENT_ID_ STRING(255),
    RESOURCE_NAME_ STRING(4000),
    DESCRIPTION_ STRING(4000),
    HAS_GRAPHICAL_NOTATION_ BOOL,
    DGRM_RESOURCE_NAME_ STRING(4000),
    HAS_START_FORM_KEY_ BOOL,
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_CMMN_RU_CASE_INST (
    ID_ STRING(255) NOT NULL,
    REV_ INT64 NOT NULL,
    BUSINESS_KEY_ STRING(255),
    NAME_ STRING(255),
    PARENT_ID_ STRING(255),
    CASE_DEF_ID_ STRING(255),
    STATE_ STRING(255),
    START_TIME_ TIMESTAMP,
    START_USER_ID_ STRING(255),
    CALLBACK_ID_ STRING(255),
    CALLBACK_TYPE_ STRING(255),
    LOCK_TIME_ TIMESTAMP,
    LOCK_OWNER_ STRING(255),
    IS_COMPLETEABLE_ BOOL,
    REFERENCE_ID_ STRING(255),
    REFERENCE_TYPE_ STRING(255),
    LAST_REACTIVATION_TIME_ TIMESTAMP,
    LAST_REACTIVATION_USER_ID_ STRING(255),
    BUSINESS_STATUS_ STRING(255),
    DUE_DATE_ TIMESTAMP,
    CLAIM_TIME_ TIMESTAMP,
    CLAIMED_BY_ STRING(255),
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_CMMN_RU_PLAN_ITEM_INST (
    ID_ STRING(255) NOT NULL,
    REV_ INT64 NOT NULL,
    CASE_DEF_ID_ STRING(255),
    CASE_INST_ID_ STRING(255),
    STAGE_INST_ID_ STRING(255),
    IS_STAGE_ BOOL,
    ELEMENT_ID_ STRING(255),
    NAME_ STRING(255),
    STATE_ STRING(255),
    CREATE_TIME_ TIMESTAMP,
    START_USER_ID_ STRING(255),
    ASSIGNEE_ STRING(255),
    COMPLETED_BY_ STRING(255),
    REFERENCE_ID_ STRING(255),
    REFERENCE_TYPE_ STRING(255),
    ITEM_DEFINITION_ID_ STRING(255),
    ITEM_DEFINITION_TYPE_ STRING(255),
    IS_COMPLETEABLE_ BOOL,
    IS_COUNT_ENABLED_ BOOL,
    VAR_COUNT_ INT64,
    SENTRY_PART_INST_COUNT_ INT64,
    LAST_AVAILABLE_TIME_ TIMESTAMP,
    LAST_ENABLED_TIME_ TIMESTAMP,
    LAST_DISABLED_TIME_ TIMESTAMP,
    LAST_STARTED_TIME_ TIMESTAMP,
    LAST_SUSPENDED_TIME_ TIMESTAMP,
    COMPLETED_TIME_ TIMESTAMP,
    OCCURRED_TIME_ TIMESTAMP,
    TERMINATED_TIME_ TIMESTAMP,
    FAILED_TIME_ TIMESTAMP,
    EXIT_TIME_ TIMESTAMP,
    ENDED_TIME_ TIMESTAMP,
    ENTRY_CRITERION_ID_ STRING(255),
    EXIT_CRITERION_ID_ STRING(255),
    EXTRA_VALUE_ STRING(255),
    DERIVED_CASE_DEF_ID_ STRING(255),
    LAST_UNAVAILABLE_TIME_ TIMESTAMP,
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_CMMN_RU_SENTRY_PART_INST (
    ID_ STRING(255) NOT NULL,
    REV_ INT64 NOT NULL,
    CASE_DEF_ID_ STRING(255),
    CASE_INST_ID_ STRING(255),
    PLAN_ITEM_INST_ID_ STRING(255),
    ON_PART_ID_ STRING(255),
    IF_PART_ID_ STRING(255),
    TIME_STAMP_ TIMESTAMP
) PRIMARY KEY (ID_);

CREATE TABLE ACT_CMMN_RU_MIL_INST (
    ID_ STRING(255) NOT NULL,
    NAME_ STRING(255) NOT NULL,
    TIME_STAMP_ TIMESTAMP NOT NULL,
    CASE_INST_ID_ STRING(255) NOT NULL,
    CASE_DEF_ID_ STRING(255) NOT NULL,
    ELEMENT_ID_ STRING(255) NOT NULL,
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_CMMN_HI_CASE_INST (
    ID_ STRING(255) NOT NULL,
    REV_ INT64 NOT NULL,
    BUSINESS_KEY_ STRING(255),
    NAME_ STRING(255),
    PARENT_ID_ STRING(255),
    CASE_DEF_ID_ STRING(255),
    STATE_ STRING(255),
    START_TIME_ TIMESTAMP,
    END_TIME_ TIMESTAMP,
    START_USER_ID_ STRING(255),
    CALLBACK_ID_ STRING(255),
    CALLBACK_TYPE_ STRING(255),
    REFERENCE_ID_ STRING(255),
    REFERENCE_TYPE_ STRING(255),
    LAST_REACTIVATION_TIME_ TIMESTAMP,
    LAST_REACTIVATION_USER_ID_ STRING(255),
    BUSINESS_STATUS_ STRING(255),
    DUE_DATE_ TIMESTAMP,
    CLAIM_TIME_ TIMESTAMP,
    CLAIMED_BY_ STRING(255),
    TENANT_ID_ STRING(255) DEFAULT (''),
    END_USER_ID_ STRING(255)
) PRIMARY KEY (ID_);

CREATE TABLE ACT_CMMN_HI_MIL_INST (
    ID_ STRING(255) NOT NULL,
    REV_ INT64 NOT NULL,
    NAME_ STRING(255) NOT NULL,
    TIME_STAMP_ TIMESTAMP NOT NULL,
    CASE_INST_ID_ STRING(255) NOT NULL,
    CASE_DEF_ID_ STRING(255) NOT NULL,
    ELEMENT_ID_ STRING(255) NOT NULL,
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

CREATE TABLE ACT_CMMN_HI_PLAN_ITEM_INST (
    ID_ STRING(255) NOT NULL,
    REV_ INT64 NOT NULL,
    NAME_ STRING(255),
    STATE_ STRING(255),
    CASE_DEF_ID_ STRING(255),
    CASE_INST_ID_ STRING(255),
    STAGE_INST_ID_ STRING(255),
    IS_STAGE_ BOOL,
    ELEMENT_ID_ STRING(255),
    ITEM_DEFINITION_ID_ STRING(255),
    ITEM_DEFINITION_TYPE_ STRING(255),
    CREATE_TIME_ TIMESTAMP,
    LAST_AVAILABLE_TIME_ TIMESTAMP,
    LAST_ENABLED_TIME_ TIMESTAMP,
    LAST_DISABLED_TIME_ TIMESTAMP,
    LAST_STARTED_TIME_ TIMESTAMP,
    LAST_SUSPENDED_TIME_ TIMESTAMP,
    COMPLETED_TIME_ TIMESTAMP,
    OCCURRED_TIME_ TIMESTAMP,
    TERMINATED_TIME_ TIMESTAMP,
    FAILED_TIME_ TIMESTAMP,
    EXIT_TIME_ TIMESTAMP,
    ENDED_TIME_ TIMESTAMP,
    LAST_UPDATED_TIME_ TIMESTAMP,
    START_USER_ID_ STRING(255),
    ASSIGNEE_ STRING(255),
    COMPLETED_BY_ STRING(255),
    REFERENCE_ID_ STRING(255),
    REFERENCE_TYPE_ STRING(255),
    ENTRY_CRITERION_ID_ STRING(255),
    EXIT_CRITERION_ID_ STRING(255),
    SHOW_IN_OVERVIEW_ BOOL,
    EXTRA_VALUE_ STRING(255),
    DERIVED_CASE_DEF_ID_ STRING(255),
    LAST_UNAVAILABLE_TIME_ TIMESTAMP,
    TENANT_ID_ STRING(255) DEFAULT ('')
) PRIMARY KEY (ID_);

ALTER TABLE ACT_CMMN_DEPLOYMENT_RESOURCE
    ADD CONSTRAINT ACT_FK_CMMN_RSRC_DPL
    FOREIGN KEY (DEPLOYMENT_ID_)
    REFERENCES ACT_CMMN_DEPLOYMENT (ID_);

CREATE INDEX ACT_IDX_CMMN_RSRC_DPL ON ACT_CMMN_DEPLOYMENT_RESOURCE (DEPLOYMENT_ID_);

ALTER TABLE ACT_CMMN_CASEDEF
    ADD CONSTRAINT ACT_FK_CASE_DEF_DPLY
    FOREIGN KEY (DEPLOYMENT_ID_)
    REFERENCES ACT_CMMN_DEPLOYMENT (ID_);

CREATE INDEX ACT_IDX_CASE_DEF_DPLY ON ACT_CMMN_CASEDEF (DEPLOYMENT_ID_);

CREATE UNIQUE NULL_FILTERED INDEX ACT_IDX_CASE_DEF_UNIQ ON ACT_CMMN_CASEDEF (KEY_, VERSION_, TENANT_ID_);

ALTER TABLE ACT_CMMN_RU_CASE_INST
    ADD CONSTRAINT ACT_FK_CASE_INST_CASE_DEF
    FOREIGN KEY (CASE_DEF_ID_)
    REFERENCES ACT_CMMN_CASEDEF (ID_);

CREATE INDEX ACT_IDX_CASE_INST_CASE_DEF ON ACT_CMMN_RU_CASE_INST (CASE_DEF_ID_);
CREATE INDEX ACT_IDX_CASE_INST_PARENT ON ACT_CMMN_RU_CASE_INST (PARENT_ID_);
CREATE INDEX ACT_IDX_CASE_INST_REF_ID_ ON ACT_CMMN_RU_CASE_INST (REFERENCE_ID_);

ALTER TABLE ACT_CMMN_RU_PLAN_ITEM_INST
    ADD CONSTRAINT ACT_FK_PLAN_ITEM_CASE_DEF
    FOREIGN KEY (CASE_DEF_ID_)
    REFERENCES ACT_CMMN_CASEDEF (ID_);

CREATE INDEX ACT_IDX_PLAN_ITEM_CASE_DEF ON ACT_CMMN_RU_PLAN_ITEM_INST (CASE_DEF_ID_);

ALTER TABLE ACT_CMMN_RU_PLAN_ITEM_INST
    ADD CONSTRAINT ACT_FK_PLAN_ITEM_CASE_INST
    FOREIGN KEY (CASE_INST_ID_)
    REFERENCES ACT_CMMN_RU_CASE_INST (ID_);

CREATE INDEX ACT_IDX_PLAN_ITEM_CASE_INST ON ACT_CMMN_RU_PLAN_ITEM_INST (CASE_INST_ID_);
CREATE INDEX ACT_IDX_PLAN_ITEM_STAGE_INST ON ACT_CMMN_RU_PLAN_ITEM_INST (STAGE_INST_ID_);

ALTER TABLE ACT_CMMN_RU_SENTRY_PART_INST
    ADD CONSTRAINT ACT_FK_SENTRY_CASE_DEF
    FOREIGN KEY (CASE_DEF_ID_)
    REFERENCES ACT_CMMN_CASEDEF (ID_);

CREATE INDEX ACT_IDX_SENTRY_CASE_DEF ON ACT_CMMN_RU_SENTRY_PART_INST (CASE_DEF_ID_);

ALTER TABLE ACT_CMMN_RU_SENTRY_PART_INST
    ADD CONSTRAINT ACT_FK_SENTRY_CASE_INST
    FOREIGN KEY (CASE_INST_ID_)
    REFERENCES ACT_CMMN_RU_CASE_INST (ID_);

CREATE INDEX ACT_IDX_SENTRY_CASE_INST ON ACT_CMMN_RU_SENTRY_PART_INST (CASE_INST_ID_);

ALTER TABLE ACT_CMMN_RU_SENTRY_PART_INST
    ADD CONSTRAINT ACT_FK_SENTRY_PLAN_ITEM
    FOREIGN KEY (PLAN_ITEM_INST_ID_)
    REFERENCES ACT_CMMN_RU_PLAN_ITEM_INST (ID_);

CREATE INDEX ACT_IDX_SENTRY_PLAN_ITEM ON ACT_CMMN_RU_SENTRY_PART_INST (PLAN_ITEM_INST_ID_);

ALTER TABLE ACT_CMMN_RU_MIL_INST
    ADD CONSTRAINT ACT_FK_MIL_CASE_DEF
    FOREIGN KEY (CASE_DEF_ID_)
    REFERENCES ACT_CMMN_CASEDEF (ID_);

CREATE INDEX ACT_IDX_MIL_CASE_DEF ON ACT_CMMN_RU_MIL_INST (CASE_DEF_ID_);

ALTER TABLE ACT_CMMN_RU_MIL_INST
    ADD CONSTRAINT ACT_FK_MIL_CASE_INST
    FOREIGN KEY (CASE_INST_ID_)
    REFERENCES ACT_CMMN_RU_CASE_INST (ID_);

CREATE INDEX ACT_IDX_MIL_CASE_INST ON ACT_CMMN_RU_MIL_INST (CASE_INST_ID_);

CREATE INDEX ACT_IDX_HI_CASE_INST_END ON ACT_CMMN_HI_CASE_INST (END_TIME_);
CREATE INDEX ACT_IDX_HI_PLAN_ITEM_INST_CASE ON ACT_CMMN_HI_PLAN_ITEM_INST (CASE_INST_ID_);

INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_) VALUES ('cmmn.schema.version', '8.1.0.1', 1);
