drop table if exists ACT_ID_PROPERTY cascade;
drop table if exists ACT_ID_BYTEARRAY cascade;
drop table if exists ACT_ID_INFO cascade;
drop table if exists ACT_ID_GROUP cascade;
drop table if exists ACT_ID_MEMBERSHIP cascade;
drop table if exists ACT_ID_USER cascade;
drop table if exists ACT_ID_TOKEN cascade;
drop table if exists ACT_ID_PRIV cascade;
drop table if exists ACT_ID_PRIV_MAPPING cascade;
