ALTER TABLE FLW_EVENT_RESOURCE DROP CONSTRAINT FLW_FK_EVENT_RSRC_DPL;

DROP INDEX IF EXISTS FLW_IDX_EVENT_RSRC_DPL;
DROP INDEX IF EXISTS ACT_IDX_EVENT_DEF_UNIQ;
DROP INDEX IF EXISTS ACT_IDX_CHANNEL_DEF_UNIQ;

DROP TABLE IF EXISTS FLW_CHANNEL_DEFINITION;
DROP TABLE IF EXISTS FLW_EVENT_DEFINITION;
DROP TABLE IF EXISTS FLW_EVENT_RESOURCE;
DROP TABLE IF EXISTS FLW_EVENT_DEPLOYMENT;
