drop index ACT_IDX_HI_PROCVAR_NAME_TYPE on ACT_HI_VARINST;
drop index ACT_IDX_HI_VAR_SCOPE_ID_TYPE on ACT_HI_VARINST;
drop index ACT_IDX_HI_VAR_SUB_ID_TYPE on ACT_HI_VARINST;

drop table if exists ACT_HI_VARINST;
