alter table ACT_RU_VARIABLE
    drop FOREIGN KEY ACT_FK_VAR_BYTEARRAY;
    
drop index ACT_IDX_RU_VAR_SCOPE_ID_TYPE on ACT_RU_VARIABLE;
drop index ACT_IDX_RU_VAR_SUB_ID_TYPE on ACT_RU_VARIABLE;    

drop table if exists ACT_RU_VARIABLE;
