
CREATE TABLE PUBLIC.ACT_CO_DATABASECHANGELOG (ID varchar(191) NOT NULL, AUTHOR varchar(191) NOT NULL, FILENAME varchar(191) NOT NULL, DATEEXECUTED TIMESTAMP NOT NULL, ORDEREXECUTED INT NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35), DESCRIPTION varchar(191), COMMENTS varchar(191), TAG varchar(191), LIQUIBASE VARCHAR(20), CONTEXTS varchar(191), LABELS varchar(191), DEPLOYMENT_ID VARCHAR(10));

CREATE TABLE PUBLIC.ACT_CO_CONTENT_ITEM (ID_ varchar(191) NOT NULL, NAME_ varchar(191) NOT NULL, MIME_TYPE_ varchar(191), TASK_ID_ varchar(191), PROC_INST_ID_ varchar(191), CONTENT_STORE_ID_ varchar(191), CONTENT_STORE_NAME_ varchar(191), FIELD_ VARCHAR(400), CONTENT_AVAILABLE_ BOOLEAN DEFAULT FALSE, CREATED_ TIMESTAMP(6), CREATED_BY_ varchar(191), LAST_MODIFIED_ TIMESTAMP(6), LAST_MODIFIED_BY_ varchar(191), CONTENT_SIZE_ BIGINT DEFAULT 0, TENANT_ID_ varchar(191), CONSTRAINT PK_ACT_CO_CONTENT_ITEM PRIMARY KEY (ID_));

CREATE INDEX PUBLIC.idx_contitem_taskid ON PUBLIC.ACT_CO_CONTENT_ITEM(TASK_ID_);

CREATE INDEX PUBLIC.idx_contitem_procid ON PUBLIC.ACT_CO_CONTENT_ITEM(PROC_INST_ID_);

INSERT INTO PUBLIC.ACT_CO_DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1', 'activiti', 'org/flowable/content/db/liquibase/flowable-content-db-changelog.xml', NOW(), 1, '8:7644d7165cfe799200a2abdd3419e8b6', 'createTable tableName=ACT_CO_CONTENT_ITEM; createIndex indexName=idx_contitem_taskid, tableName=ACT_CO_CONTENT_ITEM; createIndex indexName=idx_contitem_procid, tableName=ACT_CO_CONTENT_ITEM', '', 'EXECUTED', NULL, NULL, '3.6.1', '6986083299');

ALTER TABLE PUBLIC.ACT_CO_CONTENT_ITEM ADD SCOPE_ID_ varchar(191);

ALTER TABLE PUBLIC.ACT_CO_CONTENT_ITEM ADD SCOPE_TYPE_ varchar(191);

CREATE INDEX PUBLIC.idx_contitem_scope ON PUBLIC.ACT_CO_CONTENT_ITEM(SCOPE_ID_, SCOPE_TYPE_);

INSERT INTO PUBLIC.ACT_CO_DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('2', 'flowable', 'org/flowable/content/db/liquibase/flowable-content-db-changelog.xml', NOW(), 3, '8:fe7b11ac7dbbf9c43006b23bbab60bab', 'addColumn tableName=ACT_CO_CONTENT_ITEM; createIndex indexName=idx_contitem_scope, tableName=ACT_CO_CONTENT_ITEM', '', 'EXECUTED', NULL, NULL, '3.6.1', '6986083299');

