ALTER TABLE FLW_EVENT_DEPLOYMENT ALTER COLUMN NAME_ nvarchar(255);

ALTER TABLE FLW_EVENT_RESOURCE ALTER COLUMN NAME_ nvarchar(255);

ALTER TABLE FLW_CHANNEL_DEFINITION ALTER COLUMN NAME_ nvarchar(255);

ALTER TABLE FLW_CHANNEL_DEFINITION ALTER COLUMN CATEGORY_ nvarchar(255);

ALTER TABLE FLW_CHANNEL_DEFINITION ALTER COLUMN RESOURCE_NAME_ nvarchar(255);

ALTER TABLE FLW_EVENT_DEFINITION ALTER COLUMN NAME_ nvarchar(255);

ALTER TABLE FLW_EVENT_DEFINITION ALTER COLUMN CATEGORY_ nvarchar(255);

ALTER TABLE FLW_EVENT_DEFINITION ALTER COLUMN RESOURCE_NAME_ nvarchar(255);

ALTER TABLE FLW_CHANNEL_DEFINITION ALTER COLUMN DESCRIPTION_ nvarchar(255);

ALTER TABLE FLW_EVENT_DEFINITION ALTER COLUMN DESCRIPTION_ nvarchar(255);
