ALTER TABLE ACT_DMN_DEPLOYMENT ALTER COLUMN NAME_ nvarchar(255);

ALTER TABLE ACT_DMN_DEPLOYMENT_RESOURCE ALTER COLUMN NAME_ nvarchar(255);

ALTER TABLE ACT_DMN_DECISION ALTER COLUMN NAME_ nvarchar(255);

ALTER TABLE ACT_DMN_DECISION ALTER COLUMN CATEGORY_ nvarchar(255);

ALTER TABLE ACT_DMN_DECISION ALTER COLUMN RESOURCE_NAME_ nvarchar(255);

ALTER TABLE ACT_DMN_DECISION ALTER COLUMN DESCRIPTION_ nvarchar(255);
