IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ACT_IDX_DMN_INSTANCE_ID') drop index ACT_DMN_HI_DECISION_EXECUTION.ACT_IDX_DMN_INSTANCE_ID;
IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ACT_IDX_DMN_DEC_UNIQ') drop index ACT_DMN_DECISION.ACT_IDX_DMN_DEC_UNIQ;

if exists (select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ACT_DMN_HI_DECISION_EXECUTION') drop table ACT_DMN_HI_DECISION_EXECUTION;
if exists (select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ACT_DMN_DECISION') drop table ACT_DMN_DECISION;
if exists (select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ACT_DMN_DEPLOYMENT_RESOURCE') drop table ACT_DMN_DEPLOYMENT_RESOURCE;
if exists (select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ACT_DMN_DEPLOYMENT') drop table ACT_DMN_DEPLOYMENT;
