drop index ACT_IDX_DMN_INSTANCE_ID;
drop index ACT_IDX_DMN_DEC_UNIQ;

drop table ACT_DMN_HI_DECISION_EXECUTION;
drop table ACT_DMN_DECISION;
drop table ACT_DMN_DEPLOYMENT_RESOURCE;
drop table ACT_DMN_DEPLOYMENT;
