ALTER TABLE ACT_DMN_DEPLOYMENT_RESOURCE DROP CONSTRAINT ACT_FK_DMN_RSRC_DPL;

DROP INDEX IF EXISTS ACT_IDX_DMN_RSRC_DPL;
DROP INDEX IF EXISTS ACT_IDX_DMN_DEC_UNIQ;
DROP INDEX IF EXISTS ACT_IDX_DMN_INSTANCE_ID;

DROP TABLE IF EXISTS ACT_DMN_HI_DECISION_EXECUTION;
DROP TABLE IF EXISTS ACT_DMN_DECISION;
DROP TABLE IF EXISTS ACT_DMN_DEPLOYMENT_RESOURCE;
DROP TABLE IF EXISTS ACT_DMN_DEPLOYMENT;
